'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import { Session } from '@supabase/supabase-js';
import { useDailyLog } from '@/hooks/useDailyLog';
import { useDashboardLayout } from '@/hooks/useDashboardLayout';

import WidgetGrid from '@/components/dashboard/WidgetGrid';
import LogMealModal from '@/components/meals/LogMealDialog';
import GoalsModal from '@/components/dashboard/GoalsModal';
import ProfileModal from '@/components/auth/ProfileModal';
import WeightHistoryModal from '@/components/dashboard/WeightHistoryModal';
import DetailedNutritionModal from '@/components/dashboard/DetailedNutritionModal';
import { ChevronLeft, ChevronRight, Settings } from 'lucide-react';
import OnboardingWizard from '@/components/onboarding/OnboardingWizard';
import { useCopilot } from '@/lib/context/CopilotContext';
import { onCopilotChange } from '@/lib/copilot/events';
import AccountSecurityModal from '@/components/auth/AccountSecurityModal';

export default function Dashboard() {
  const router = useRouter();
  const [session, setSession] = useState<Session | null>(null);
  const [authLoading, setAuthLoading] = useState(true);
  const [needsOnboarding, setNeedsOnboarding] = useState(false);

  // Modals
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedMealTypeForModal, setSelectedMealTypeForModal] =
    useState<string>('lunch');
  const [editingLog, setEditingLog] = useState<any>(null);
  const [isGoalsModalOpen, setIsGoalsModalOpen] = useState(false);
  const [isProfileModalOpen, setIsProfileModalOpen] = useState(false);
  const [isDetailedModalOpen, setIsDetailedModalOpen] = useState(false);
  const [isWeightModalOpen, setIsWeightModalOpen] = useState(false);
  const [isSecurityModalOpen, setIsSecurityModalOpen] = useState(false);

  // Layout & Global State
  const [isEditingLayout, setIsEditingLayout] = useState(false);
  const [avatarUrl, setAvatarUrl] = useState('');

  const getTodayString = () => new Date().toISOString().split('T')[0];
  const [selectedDate, setSelectedDate] = useState(getTodayString());

  const {
    dailyLog,
    loading: logLoading,
    addMeal,
    removeMeal,
    updateMeal,
    refreshLog,
  } = useDailyLog(session && !needsOnboarding ? selectedDate : '');

  const { layout, updateLayout, isLoaded: layoutLoaded } = useDashboardLayout();
  const { setLogDate } = useCopilot();

  /* The copilot answers about whichever day is on screen, not always today */
  useEffect(() => {
    setLogDate(selectedDate);
  }, [selectedDate, setLogDate]);

  /* The panel floats above this page and can log a meal from anywhere, so the
     rings have to be told rather than left showing stale totals */
  useEffect(() => {
    return onCopilotChange('nutrition', () => refreshLog && refreshLog());
  }, [refreshLog]);

  // Auth & Profile Fetching Logic
  useEffect(() => {
    let isMounted = true;

    const fetchDashboardProfile = async (token: string) => {
      try {
        const res = await fetch(
          `${process.env.NEXT_PUBLIC_API_URL}/profile/me?t=${Date.now()}`,
          {
            headers: { Authorization: `Bearer ${token}` },
            cache: 'no-store',
          },
        );

        if (res.ok) {
          const data = await res.json();
          if (isMounted && data.avatar_url) setAvatarUrl(data.avatar_url);

          const isAutoGenerated =
            !data.weight_kg ||
            (data.weight_kg === 75 &&
              data.height_cm === 175 &&
              data.activity_level === 1.2 &&
              data.goal_type === 'maintain');

          if (isMounted && isAutoGenerated) setNeedsOnboarding(true);
        } else {
          if (isMounted) setNeedsOnboarding(true);
        }
      } catch (err) {
        console.error('Error fetching profile:', err);
        if (isMounted) setNeedsOnboarding(true);
      }
    };

    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((event, session) => {
      if (isMounted) {
        setSession(session);
        if (session) {
          setAuthLoading(false);
          fetchDashboardProfile(session.access_token);
        } else if (event === 'SIGNED_OUT') {
          setAuthLoading(false);
        }
      }
    });

    supabase.auth.getSession().then(({ data: { session } }) => {
      if (isMounted) {
        setSession(session);
        if (session) {
          fetchDashboardProfile(session.access_token);
          setAuthLoading(false);
        } else {
          if (!window.location.hash.includes('access_token')) {
            setAuthLoading(false);
          }
        }
      }
    });

    return () => {
      isMounted = false;
      subscription.unsubscribe();
    };
  }, []);

  useEffect(() => {
    if (!authLoading && !session) router.replace('/login');
  }, [authLoading, session, router]);

  useEffect(() => {
    if (
      typeof window !== 'undefined' &&
      window.location.search.includes('profile=open')
    ) {
      setIsProfileModalOpen(true);
      window.history.replaceState(null, '', '/');
    }
  }, []);

  if (authLoading || !layoutLoaded)
    return <div className="p-8 text-white font-mono">Loading...</div>;
  if (!session) return null;

  return (
    <main className="min-h-screen bg-neutral-950 text-neutral-100 p-4 sm:p-6 md:p-12 pb-24 md:pb-12 relative">
      <div className="max-w-4xl mx-auto space-y-6 sm:space-y-8">
        <header className="border-b border-neutral-800 pb-6 flex flex-col md:flex-row md:justify-between md:items-start gap-4">
          <div className="flex items-start gap-3 sm:gap-4">
            <button
              onClick={() => setIsProfileModalOpen(true)}
              className="flex-shrink-0 w-12 h-12 sm:w-14 sm:h-14 rounded-full bg-neutral-900 border border-neutral-700 flex items-center justify-center hover:bg-emerald-400 transition-colors focus:outline-none focus:ring-2 focus:ring-emerald-500 overflow-hidden shadow-md mt-1"
            >
              {avatarUrl ? (
                <img
                  src={avatarUrl}
                  alt="Profile"
                  className="w-full h-full object-cover"
                />
              ) : (
                <svg
                  className="w-6 h-6 sm:w-7 sm:h-7 text-neutral-400"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z"
                    clipRule="evenodd"
                  />
                </svg>
              )}
            </button>
            <div>
              <div className="flex flex-wrap items-center gap-2 sm:gap-3 mb-2 sm:mb-3">
                <h1 className="text-2xl sm:text-3xl font-bold tracking-tight">
                  Daily Nutrition
                </h1>
                <button
                  onClick={() => setIsGoalsModalOpen(true)}
                  className="text-[10px] sm:text-xs bg-neutral-900 border border-neutral-800 text-neutral-400 hover:text-emerald-500 px-2 sm:px-2.5 py-1 rounded transition-colors"
                >
                  Goals
                </button>
                <button
                  onClick={() => router.push('/workouts')}
                  className="text-[10px] sm:text-xs bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 hover:bg-indigo-500 hover:text-white px-2 sm:px-2.5 py-1 rounded transition-colors ml-2"
                >
                  Training
                </button>
              </div>
              <div className="flex items-center gap-2 sm:gap-3 flex-wrap">
                <div className="flex items-center bg-neutral-900 border border-neutral-800 rounded-lg p-0.5 shadow-sm">
                  <button
                    onClick={() => {
                      const d = new Date(selectedDate);
                      d.setUTCDate(d.getUTCDate() - 1);
                      setSelectedDate(d.toISOString().split('T')[0]);
                    }}
                    className="text-neutral-500 hover:text-emerald-400 p-1 sm:p-1.5 hover:bg-neutral-800 rounded-md transition-all active:scale-95"
                  >
                    <ChevronLeft size={18} strokeWidth={2.5} />
                  </button>
                  <input
                    type="date"
                    value={selectedDate}
                    onChange={(e) => setSelectedDate(e.target.value)}
                    className="bg-transparent border-none px-1 sm:px-2 py-1 text-[13px] sm:text-sm text-neutral-300 font-mono focus:outline-none focus:ring-0 [color-scheme:dark] cursor-pointer hover:text-emerald-500 transition-colors"
                  />
                  <button
                    onClick={() => {
                      const d = new Date(selectedDate);
                      d.setUTCDate(d.getUTCDate() + 1);
                      setSelectedDate(d.toISOString().split('T')[0]);
                    }}
                    className="text-neutral-500 hover:text-emerald-400 p-1 sm:p-1.5 hover:bg-neutral-800 rounded-md transition-all active:scale-95"
                  >
                    <ChevronRight size={18} strokeWidth={2.5} />
                  </button>
                </div>

                {selectedDate !== getTodayString() && (
                  <button
                    onClick={() => setSelectedDate(getTodayString())}
                    className="text-[10px] sm:text-xs font-mono font-medium text-emerald-400 hover:text-emerald-300 px-2.5 py-1.5 bg-emerald-500/10 hover:bg-emerald-500/20 rounded-md border border-emerald-500/20 transition-all active:scale-95"
                  >
                    Today
                  </button>
                )}
                <button
                  onClick={() => setIsEditingLayout(!isEditingLayout)}
                  className={`flex items-center gap-1.5 text-[10px] sm:text-xs font-mono font-medium px-2.5 py-1.5 rounded-md transition-all active:scale-95 border ${isEditingLayout ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-400' : 'bg-neutral-900 border-neutral-800 text-neutral-400 hover:border-neutral-700 hover:text-white'}`}
                >
                  <Settings size={14} />
                  {isEditingLayout ? 'Done Editing' : 'Edit Layout'}
                </button>
              </div>
            </div>
          </div>
        </header>

        {/* Widget grid section */}
        {logLoading && !needsOnboarding ? (
          <div className="py-12 text-center text-neutral-400 font-mono text-sm animate-pulse">
            Loading nutrition data for {selectedDate}...
          </div>
        ) : (
          <WidgetGrid
            layout={layout}
            updateLayout={updateLayout}
            isEditingLayout={isEditingLayout}
            dailyLog={dailyLog}
            selectedDate={selectedDate}
            addMeal={addMeal}
            removeMeal={removeMeal}
            refreshLog={refreshLog}
            setIsDetailedModalOpen={setIsDetailedModalOpen}
            setIsWeightModalOpen={setIsWeightModalOpen}
            setSelectedMealTypeForModal={setSelectedMealTypeForModal}
            setIsModalOpen={setIsModalOpen}
            onEditMeal={(meal) => {
              setEditingLog(meal);
              setIsModalOpen(true);
            }}
          />
        )}
      </div>

      <LogMealModal
        isOpen={isModalOpen}
        onClose={() => {
          setIsModalOpen(false);
          setEditingLog(null);
        }}
        onAddMeal={addMeal}
        initialMealType={selectedMealTypeForModal}
        editingLog={editingLog}
        onUpdateLog={updateMeal}
      />

      <GoalsModal
        isOpen={isGoalsModalOpen}
        onClose={() => setIsGoalsModalOpen(false)}
        onUpdateSuccess={() => refreshLog && refreshLog()}
      />
      <ProfileModal
        isOpen={isProfileModalOpen}
        onClose={() => setIsProfileModalOpen(false)}
        onProfileUpdate={(newUrl) => setAvatarUrl(newUrl)}
        onOpenSecurity={() => {
          setIsProfileModalOpen(false);
          setIsSecurityModalOpen(true);
        }}
      />
      <AccountSecurityModal
        isOpen={isSecurityModalOpen}
        onClose={() => {
          setIsSecurityModalOpen(false);
          setIsProfileModalOpen(true);
        }}
      />
      <DetailedNutritionModal
        isOpen={isDetailedModalOpen}
        onClose={() => setIsDetailedModalOpen(false)}
        dailyLog={dailyLog}
      />
      <WeightHistoryModal
        isOpen={isWeightModalOpen}
        onClose={() => setIsWeightModalOpen(false)}
      />

      {needsOnboarding && (
        <OnboardingWizard
          onComplete={() => {
            setNeedsOnboarding(false);
            if (refreshLog) refreshLog();
          }}
        />
      )}
    </main>
  );
}
