"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { Session } from "@supabase/supabase-js";
import { useDailyLog } from "@/hooks/useDailyLog";
import { MEAL_TYPES, MEAL_TYPE_LABELS } from "@/lib/constants";
import {
  useDashboardLayout,
  NUTRITION_METRICS,
  FEATURE_METRICS,
} from "@/hooks/useDashboardLayout";

import MealGroup from "@/components/dashboard/MealGroup";
import LogMealModal from "@/components/meals/LogMealModal";
import GoalsModal from "@/components/dashboard/GoalsModal";
import ProfileModal from "@/components/auth/ProfileModal";
import WaterTracker from "@/components/dashboard/WaterTracker";
import WeightChart from "@/components/dashboard/WeightChart";
import WeightHistoryModal from "@/components/dashboard/WeightHistoryModal";
import DetailedNutritionModal from "@/components/dashboard/DetailedNutritionModal";
import { ChevronLeft, ChevronRight, Settings } from "lucide-react";
import Copilot from "@/components/chat/Copilot";
import OnboardingWizard from "@/components/onboarding/OnboardingWizard";
import AccountSecurityModal from "@/components/auth/AccountSecurityModal";

export default function Dashboard() {
  const router = useRouter();
  const [session, setSession] = useState<Session | null>(null);
  const [authLoading, setAuthLoading] = useState(true);

  const [needsOnboarding, setNeedsOnboarding] = useState(false);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedMealTypeForModal, setSelectedMealTypeForModal] =
    useState<string>("lunch");
  const [isGoalsModalOpen, setIsGoalsModalOpen] = useState(false);
  const [isProfileModalOpen, setIsProfileModalOpen] = useState(false);
  const [isDetailedModalOpen, setIsDetailedModalOpen] = useState(false);
  const [isWeightModalOpen, setIsWeightModalOpen] = useState(false);

  const [isEditingLayout, setIsEditingLayout] = useState(false);
  const [avatarUrl, setAvatarUrl] = useState("");

  const getTodayString = () => new Date().toISOString().split("T")[0];
  const [selectedDate, setSelectedDate] = useState(getTodayString());

  const [isSecurityModalOpen, setIsSecurityModalOpen] = useState(false);

  const {
    dailyLog,
    loading: logLoading,
    addMeal,
    removeMeal,
    refreshLog,
  } = useDailyLog(session && !needsOnboarding ? selectedDate : "");

  const { layout, updateLayout, isLoaded: layoutLoaded } = useDashboardLayout();

  const [resizingIndex, setResizingIndex] = useState<number | null>(null);
  const [startMouseY, setStartMouseY] = useState(0);
  const [startHeight, setStartHeight] = useState(0);
  const [liveHeight, setLiveHeight] = useState<number | null>(null);

  // Auth & Profile Fetching Logic
  useEffect(() => {
    let isMounted = true;

    const fetchDashboardProfile = async (token: string) => {
      try {
        const res = await fetch(
          `${process.env.NEXT_PUBLIC_API_URL}/profile/me?t=${Date.now()}`,
          {
            headers: { Authorization: `Bearer ${token}` },
            cache: "no-store",
          },
        );

        if (res.ok) {
          const data = await res.json();
          if (isMounted && data.avatar_url) setAvatarUrl(data.avatar_url);

          // Detect if the profile is brand new by checking against the backend's hardcoded SQLAlchemy defaults
          const isAutoGenerated =
            !data.weight_kg ||
            (data.weight_kg === 75 &&
              data.height_cm === 175 &&
              data.activity_level === 1.2 &&
              data.goal_type === "maintain");

          if (isMounted && isAutoGenerated) {
            setNeedsOnboarding(true);
          }
        } else {
          // Trigger wizard on 404 (New Account) or fallback errors
          if (isMounted) setNeedsOnboarding(true);
        }
      } catch (err) {
        console.error("Error fetching profile:", err);
        if (isMounted) setNeedsOnboarding(true);
      }
    };

    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((event, session) => {
      if (isMounted) {
        setSession(session);
        if (session) {
          setAuthLoading(false);
          fetchDashboardProfile(session.access_token);
        } else if (event === "SIGNED_OUT") {
          setAuthLoading(false);
        }
      }
    });

    supabase.auth.getSession().then(({ data: { session } }) => {
      if (isMounted) {
        setSession(session);
        if (session) {
          fetchDashboardProfile(session.access_token);
          setAuthLoading(false);
        } else {
          if (!window.location.hash.includes("access_token")) {
            setAuthLoading(false);
          }
        }
      }
    });

    return () => {
      isMounted = false;
      subscription.unsubscribe();
    };
  }, []);

  // Redirect Logic
  useEffect(() => {
    if (!authLoading && !session) router.replace("/login");
  }, [authLoading, session, router]);

  const handlePrevDay = () => {
    const d = new Date(selectedDate);
    d.setUTCDate(d.getUTCDate() - 1);
    setSelectedDate(d.toISOString().split("T")[0]);
  };

  const handleNextDay = () => {
    const d = new Date(selectedDate);
    d.setUTCDate(d.getUTCDate() + 1);
    setSelectedDate(d.toISOString().split("T")[0]);
  };

  const handleJumpToToday = () => {
    setSelectedDate(getTodayString());
  };

  const handleResizeStart = (
    e: React.MouseEvent | React.TouchEvent,
    index: number,
  ) => {
    e.stopPropagation();
    e.preventDefault();
    const clientY =
      "touches" in e ? e.touches[0].clientY : (e as React.MouseEvent).clientY;
    const element = document.getElementById(`widget-${index}`);
    if (!element) return;
    setResizingIndex(index);
    setStartMouseY(clientY);
    const h = element.getBoundingClientRect().height;
    setStartHeight(h);
    setLiveHeight(h);
  };

  useEffect(() => {
    if (resizingIndex === null) return;
    const handleMove = (e: MouseEvent | TouchEvent) => {
      const clientY =
        "touches" in e ? e.touches[0].clientY : (e as MouseEvent).clientY;
      const delta = clientY - startMouseY;
      setLiveHeight(Math.max(80, startHeight + delta));
    };

    const handleEnd = () => {
      if (resizingIndex !== null && liveHeight !== null) {
        const newLayout = [...layout];
        newLayout[resizingIndex].height = liveHeight;
        updateLayout(newLayout);
      }
      setResizingIndex(null);
      setLiveHeight(null);
    };

    window.addEventListener("mousemove", handleMove);
    window.addEventListener("mouseup", handleEnd);
    window.addEventListener("touchmove", handleMove, { passive: false });
    window.addEventListener("touchend", handleEnd);

    return () => {
      window.removeEventListener("mousemove", handleMove);
      window.removeEventListener("mouseup", handleEnd);
      window.removeEventListener("touchmove", handleMove);
      window.removeEventListener("touchend", handleEnd);
    };
  }, [
    resizingIndex,
    startMouseY,
    startHeight,
    liveHeight,
    layout,
    updateLayout,
  ]);

  const handleDragStart = (
    e: React.DragEvent,
    source: "grid" | "palette",
    type: "goal" | "meal" | "feature",
    id: string,
    index?: number,
  ) => {
    e.dataTransfer.setData("source", source);
    e.dataTransfer.setData("type", type);
    e.dataTransfer.setData("id", id);
    if (index !== undefined) e.dataTransfer.setData("index", index.toString());
  };

  const handleDrop = (e: React.DragEvent, targetIndex: number) => {
    e.preventDefault();
    const source = e.dataTransfer.getData("source");
    const type = e.dataTransfer.getData("type") as "goal" | "meal" | "feature";
    const id = e.dataTransfer.getData("id");
    const newLayout = [...layout];

    if (source === "palette") {
      newLayout.splice(targetIndex, 0, {
        id,
        type,
        size: type === "goal" ? "half" : "full",
      });
      updateLayout(newLayout);
    } else if (source === "grid") {
      const sourceIndex = parseInt(e.dataTransfer.getData("index"));
      if (sourceIndex === targetIndex) return;
      const [moved] = newLayout.splice(sourceIndex, 1);
      let adjustedTarget = targetIndex;
      if (sourceIndex < targetIndex) adjustedTarget -= 1;
      newLayout.splice(adjustedTarget, 0, moved);
      updateLayout(newLayout);
    }
  };

  const toggleSize = (index: number) => {
    const newLayout = [...layout];
    newLayout[index].size = newLayout[index].size === "full" ? "half" : "full";
    updateLayout(newLayout);
  };

  const removeWidget = (index: number) => {
    const newLayout = [...layout];
    newLayout.splice(index, 1);
    updateLayout(newLayout);
  };

  const unusedMetrics = Object.keys(NUTRITION_METRICS).filter(
    (k) => !layout.some((w) => w.type === "goal" && w.id === k),
  );
  const unusedMeals = MEAL_TYPES.filter(
    (t) => !layout.some((w) => w.type === "meal" && w.id === t),
  );
  const unusedFeatures = Object.keys(FEATURE_METRICS).filter(
    (k) => !layout.some((w) => w.type === "feature" && w.id === k),
  );

  if (authLoading || !layoutLoaded)
    return <div className="p-8 text-white font-mono">Loading...</div>;
  if (!session) return null;

  return (
    <main className="min-h-screen bg-neutral-950 text-neutral-100 p-4 sm:p-6 md:p-12 pb-24 md:pb-12 relative">
      <div className="max-w-4xl mx-auto space-y-6 sm:space-y-8">
        <header className="border-b border-neutral-800 pb-6 flex flex-col md:flex-row md:justify-between md:items-start gap-4">
          <div className="flex items-start gap-3 sm:gap-4">
            <button
              onClick={() => setIsProfileModalOpen(true)}
              className="flex-shrink-0 w-12 h-12 sm:w-14 sm:h-14 rounded-full bg-neutral-900 border border-neutral-700 flex items-center justify-center hover:bg-emerald-400 transition-colors focus:outline-none focus:ring-2 focus:ring-emerald-500 overflow-hidden shadow-md mt-1"
            >
              {avatarUrl ? (
                <img
                  src={avatarUrl}
                  alt="Profile"
                  className="w-full h-full object-cover"
                />
              ) : (
                <svg
                  className="w-6 h-6 sm:w-7 sm:h-7 text-neutral-400"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z"
                    clipRule="evenodd"
                  />
                </svg>
              )}
            </button>
            <div>
              <div className="flex flex-wrap items-center gap-2 sm:gap-3 mb-2 sm:mb-3">
                <h1 className="text-2xl sm:text-3xl font-bold tracking-tight">
                  Daily Nutrition
                </h1>
                <button
                  onClick={() => setIsGoalsModalOpen(true)}
                  className="text-[10px] sm:text-xs bg-neutral-900 border border-neutral-800 text-neutral-400 hover:text-emerald-500 px-2 sm:px-2.5 py-1 rounded transition-colors"
                >
                  Goals
                </button>
              </div>

              <div className="flex items-center gap-2 sm:gap-3 flex-wrap">
                <div className="flex items-center bg-neutral-900 border border-neutral-800 rounded-lg p-0.5 shadow-sm">
                  <button
                    onClick={handlePrevDay}
                    className="text-neutral-500 hover:text-emerald-400 p-1 sm:p-1.5 hover:bg-neutral-800 rounded-md transition-all active:scale-95"
                  >
                    <ChevronLeft size={18} strokeWidth={2.5} />
                  </button>
                  <input
                    type="date"
                    value={selectedDate}
                    onChange={(e) => setSelectedDate(e.target.value)}
                    className="bg-transparent border-none px-1 sm:px-2 py-1 text-[13px] sm:text-sm text-neutral-300 font-mono focus:outline-none focus:ring-0 [color-scheme:dark] cursor-pointer hover:text-emerald-500 transition-colors"
                  />
                  <button
                    onClick={handleNextDay}
                    className="text-neutral-500 hover:text-emerald-400 p-1 sm:p-1.5 hover:bg-neutral-800 rounded-md transition-all active:scale-95"
                  >
                    <ChevronRight size={18} strokeWidth={2.5} />
                  </button>
                </div>
                {selectedDate !== getTodayString() && (
                  <button
                    onClick={handleJumpToToday}
                    className="text-[10px] sm:text-xs font-mono font-medium text-emerald-400 hover:text-emerald-300 px-2.5 py-1.5 bg-emerald-500/10 hover:bg-emerald-500/20 rounded-md border border-emerald-500/20 transition-all active:scale-95"
                  >
                    Today
                  </button>
                )}
                <button
                  onClick={() => setIsEditingLayout(!isEditingLayout)}
                  className={`flex items-center gap-1.5 text-[10px] sm:text-xs font-mono font-medium px-2.5 py-1.5 rounded-md transition-all active:scale-95 border ${
                    isEditingLayout
                      ? "bg-emerald-500/20 border-emerald-500/50 text-emerald-400"
                      : "bg-neutral-900 border-neutral-800 text-neutral-400 hover:border-neutral-700 hover:text-white"
                  }`}
                >
                  <Settings size={14} />
                  {isEditingLayout ? "Done Editing" : "Edit Layout"}
                </button>
              </div>
            </div>
          </div>
        </header>

        {logLoading && !needsOnboarding ? (
          <div className="py-12 text-center text-neutral-400 font-mono text-sm animate-pulse">
            Loading nutrition data for {selectedDate}...
          </div>
        ) : (
          <section className="mb-6 sm:mb-8">
            {isEditingLayout && (
              <div className="bg-neutral-900 border border-emerald-500/30 rounded-xl p-5 shadow-lg mb-6 animate-in fade-in slide-in-from-top-4">
                <h3 className="text-sm font-semibold text-emerald-400 mb-3 flex items-center gap-2">
                  <span className="animate-pulse">●</span> Widget Palette (Drag
                  into the grid)
                </h3>
                <div className="flex flex-wrap gap-2">
                  {unusedMetrics.map((key) => (
                    <div
                      key={`pal-goal-${key}`}
                      draggable
                      onDragStart={(e) =>
                        handleDragStart(e, "palette", "goal", key)
                      }
                      className="bg-neutral-950 border border-neutral-700 px-3 py-1.5 rounded-full text-xs font-mono cursor-grab active:cursor-grabbing hover:border-emerald-500 transition-colors shadow-sm"
                    >
                      + {NUTRITION_METRICS[key].label}
                    </div>
                  ))}
                  {unusedMeals.map((key) => (
                    <div
                      key={`pal-meal-${key}`}
                      draggable
                      onDragStart={(e) =>
                        handleDragStart(e, "palette", "meal", key)
                      }
                      className="bg-neutral-950 border border-neutral-700 px-3 py-1.5 rounded-full text-xs font-mono cursor-grab active:cursor-grabbing hover:border-blue-500 transition-colors shadow-sm"
                    >
                      + {MEAL_TYPE_LABELS[key] || key} Meal
                    </div>
                  ))}
                  {unusedFeatures.map((key) => (
                    <div
                      key={`pal-feat-${key}`}
                      draggable
                      onDragStart={(e) =>
                        handleDragStart(e, "palette", "feature", key)
                      }
                      className="bg-neutral-950 border border-neutral-700 px-3 py-1.5 rounded-full text-xs font-mono cursor-grab active:cursor-grabbing hover:border-indigo-500 transition-colors shadow-sm"
                    >
                      + {FEATURE_METRICS[key].label}
                    </div>
                  ))}
                  {unusedMetrics.length === 0 &&
                    unusedMeals.length === 0 &&
                    unusedFeatures.length === 0 && (
                      <span className="text-xs text-neutral-500 font-mono">
                        All available widgets are on your dashboard!
                      </span>
                    )}
                </div>
              </div>
            )}

            <div
              className={`grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4 ${isEditingLayout ? "pb-8 bg-neutral-950/40 p-2 sm:p-4 rounded-xl border border-dashed border-neutral-800" : ""}`}
            >
              {layout.map((widget, index) => {
                const isFull = widget.size === "full";
                const colSpanClass = isFull
                  ? "col-span-2 lg:col-span-4"
                  : "col-span-1 lg:col-span-2";

                const currentHeight =
                  resizingIndex === index ? liveHeight : widget.height;

                return (
                  <div
                    id={`widget-${index}`}
                    key={`${widget.type}-${widget.id}-${index}`}
                    draggable={isEditingLayout && resizingIndex === null}
                    onDragStart={(e) =>
                      handleDragStart(e, "grid", widget.type, widget.id, index)
                    }
                    onDragOver={(e) => {
                      e.preventDefault();
                      e.dataTransfer.dropEffect = "move";
                    }}
                    onDrop={(e) => handleDrop(e, index)}
                    style={{
                      minHeight: currentHeight
                        ? `${currentHeight}px`
                        : undefined,
                    }}
                    className={`${colSpanClass} flex flex-col relative group transition-all duration-200 ${isEditingLayout ? "ring-1 ring-emerald-500/30 hover:ring-emerald-500 rounded-xl bg-neutral-900/50" : ""} ${isEditingLayout && resizingIndex === null ? "cursor-grab active:cursor-grabbing" : ""}`}
                  >
                    {isEditingLayout && (
                      <div
                        onMouseDown={(e) => handleResizeStart(e, index)}
                        onTouchStart={(e) => handleResizeStart(e, index)}
                        className="absolute bottom-0 left-0 right-0 h-5 hover:h-6 bg-emerald-500/10 hover:bg-emerald-500/30 cursor-ns-resize flex items-end justify-center rounded-b-xl z-40 transition-all opacity-0 group-hover:opacity-100"
                      >
                        <div className="w-12 h-1 bg-emerald-500 rounded-full mb-1.5 opacity-80" />
                      </div>
                    )}

                    <div className="absolute -top-2 -right-2 flex gap-1 z-30 opacity-0 group-hover:opacity-100 transition-opacity">
                      {isEditingLayout && (
                        <>
                          <button
                            type="button"
                            onClick={(e) => {
                              e.stopPropagation();
                              toggleSize(index);
                            }}
                            className="bg-neutral-800 hover:bg-neutral-700 text-white w-6 h-6 rounded-md flex items-center justify-center text-[10px] font-mono border border-neutral-600 shadow-md"
                          >
                            {isFull ? "><" : "<>"}
                          </button>
                          <button
                            type="button"
                            onClick={(e) => {
                              e.stopPropagation();
                              removeWidget(index);
                            }}
                            className="bg-rose-900/90 hover:bg-rose-600 text-white w-6 h-6 rounded-md flex items-center justify-center text-[10px] font-bold border border-rose-700 shadow-md"
                          >
                            ✕
                          </button>
                        </>
                      )}
                    </div>

                    <div
                      className={`flex-1 w-full [&>div]:h-full ${isEditingLayout && widget.type === "meal" ? "pointer-events-none opacity-60 pl-8 sm:pl-12 transition-all" : ""} ${isEditingLayout && widget.type === "goal" ? "pointer-events-none opacity-60 transition-all" : ""} ${isEditingLayout && widget.type === "feature" ? "pointer-events-none opacity-60 transition-all" : ""} ${isEditingLayout && resizingIndex !== null ? "select-none" : ""}`}
                    >
                      {widget.type === "feature" &&
                        widget.id === "weight_chart" && (
                          <WeightChart
                            selectedDate={selectedDate}
                            onClick={() =>
                              !isEditingLayout && setIsWeightModalOpen(true)
                            }
                          />
                        )}

                      {widget.type === "goal" &&
                        (widget.id === "water" ? (
                          <WaterTracker
                            summary={dailyLog}
                            onWaterUpdated={() => refreshLog && refreshLog()}
                          />
                        ) : (
                          (() => {
                            const config = NUTRITION_METRICS[widget.id];
                            if (!config) return null;
                            const currentVal =
                              (dailyLog as any)?.[config.key] || 0;
                            const targetVal =
                              (dailyLog as any)?.[config.targetKey] ||
                              config.defaultTarget;
                            const progress =
                              Math.min((currentVal / targetVal) * 100, 100) ||
                              0;

                            return (
                              <div
                                onClick={() =>
                                  !isEditingLayout &&
                                  setIsDetailedModalOpen(true)
                                }
                                className={`bg-neutral-900 p-4 sm:p-6 rounded-xl border border-neutral-800 space-y-2 sm:space-y-3 flex flex-col justify-center shadow-sm ${!isEditingLayout ? "cursor-pointer hover:border-emerald-700" : ""}`}
                              >
                                <div className="flex flex-col sm:flex-row sm:justify-between text-xs sm:text-sm gap-1">
                                  <span className="text-neutral-400">
                                    {config.label}
                                  </span>
                                  <span className="font-mono font-bold">
                                    {currentVal} / {targetVal} {config.unit}
                                  </span>
                                </div>
                                <div className="w-full bg-neutral-800 h-2.5 sm:h-3 rounded-full overflow-hidden">
                                  <div
                                    className={`${config.color} h-full transition-all duration-500 shadow-sm`}
                                    style={{ width: `${progress}%` }}
                                  />
                                </div>
                              </div>
                            );
                          })()
                        ))}

                      {widget.type === "meal" && (
                        <MealGroup
                          label={MEAL_TYPE_LABELS[widget.id] || widget.id}
                          mealType={widget.id}
                          selectedDate={selectedDate}
                          isToday={selectedDate === getTodayString()}
                          meals={(dailyLog?.meals || []).filter(
                            (m: any) =>
                              m.meal_type?.toLowerCase() === widget.id,
                          )}
                          onDeleteMeal={removeMeal}
                          onAddMeal={addMeal}
                          onAddMealClick={() => {
                            setSelectedMealTypeForModal(widget.id);
                            setIsModalOpen(true);
                          }}
                        />
                      )}
                    </div>
                  </div>
                );
              })}

              {isEditingLayout && (
                <div
                  onDragOver={(e) => {
                    e.preventDefault();
                    e.dataTransfer.dropEffect = "copy";
                  }}
                  onDrop={(e) => handleDrop(e, layout.length)}
                  className="col-span-2 lg:col-span-4 h-16 border-2 border-dashed border-neutral-800 hover:border-emerald-500/50 hover:bg-emerald-500/5 rounded-xl flex items-center justify-center text-neutral-500 font-mono text-xs transition-colors mt-2"
                >
                  + Drop here to add to bottom
                </div>
              )}
            </div>
          </section>
        )}
      </div>

      <Copilot
        selectedDate={selectedDate}
        onUpdateSuccess={() => {
          if (refreshLog) refreshLog();
        }}
        onAddMeal={addMeal}
      />

      <LogMealModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onAddMeal={addMeal}
        initialMealType={selectedMealTypeForModal}
      />

      <GoalsModal
        isOpen={isGoalsModalOpen}
        onClose={() => setIsGoalsModalOpen(false)}
        onUpdateSuccess={() => {
          if (refreshLog) refreshLog();
        }}
      />

      <ProfileModal
     isOpen={isProfileModalOpen}
     onClose={() => setIsProfileModalOpen(false)}
     onProfileUpdate={(newUrl) => setAvatarUrl(newUrl)}
     onOpenSecurity={() => {
       setIsProfileModalOpen(false);
       setIsSecurityModalOpen(true);
     }}
   />

      <AccountSecurityModal
        isOpen={isSecurityModalOpen}
        onClose={() => setIsSecurityModalOpen(false)}
      />

      <DetailedNutritionModal
        isOpen={isDetailedModalOpen}
        onClose={() => setIsDetailedModalOpen(false)}
        dailyLog={dailyLog}
      />

      <WeightHistoryModal
        isOpen={isWeightModalOpen}
        onClose={() => setIsWeightModalOpen(false)}
      />

      {needsOnboarding && (
        <OnboardingWizard
          onComplete={() => {
            setNeedsOnboarding(false);
            if (refreshLog) refreshLog();
          }}
        />
      )}
    </main>
  );
}
