"""Back entries for the global exercise database."""

BACK_EXERCISES = [
    {
        "name": "Barbell Row",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Lower Back", "Biceps", "Forearms", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Pendlay Row",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Lower Back", "Traps", "Biceps", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Deficit Barbell Row",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Lower Back", "Biceps", "Forearms", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "T-Bar Row",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Lower Back", "Traps", "Biceps", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Seal Row",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Traps", "Biceps", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single Arm Dumbbell Row",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Posterior Delt", "Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Bench Chest Supported Dumbbell Row",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Posterior Delt", "Traps", "Biceps", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single-Arm Landmine Row (Meadows Row)",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Posterior Delt", "Traps", "Biceps", "Forearms", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Renegade Row",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Biceps", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Pull-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Weighted Pull-Ups",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Assisted Pull-Ups",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Chin-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Weighted Chin-Ups",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Assisted Chin-Ups",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Neutral Grip Pull-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Neutral Grip Weighted Pull-Ups",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Neutral Grip Assisted Pull-Ups",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Wide-Grip Pull-Downs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Close-Grip Pull-Downs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Neutral Grip Pull-Downs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Medium Width Pull-Downs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Reverse Grip Pull-Downs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single Hand Pull-Downs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Pull-Down Machine (Plate / Pin Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Wide Grip Cable Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Posterior Delt", "Traps", "Biceps", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Close Grip Cable Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Neutral Grip Cable Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single Hand Cable Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Chest Supported Iso-Lateral Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Posterior Delt", "Traps", "Biceps", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Low to High Chest Supported Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Traps",
        "secondary_muscles": ["Posterior Delt", "Biceps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "High to Low Chest Supported Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Chest Supported Rows (Pin Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Traps", "Biceps", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Chest Supported T-Bar Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Traps", "Biceps", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Lower Back", "Biceps", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Bench Chest Supported Smith Machine Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Traps", "Biceps", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Rope Pull-Over",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Straight Bar Pull-Over",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "V-Bar Pull-Over",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Wide Grip Pull-Over",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Pull-Over Machine (Plate / Pin Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Pullover (Lat-Focused)",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Conventional Deadlift",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Lower Back",
        "secondary_muscles": ["Traps", "Forearms", "Glutes", "Hamstrings", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Sumo Deadlift",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Lower Back",
        "secondary_muscles": ["Traps", "Glutes", "Hamstrings", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Rack Pulls / Block Pulls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Lower Back",
        "secondary_muscles": ["Traps", "Forearms", "Glutes", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Back Extensions (45-Degree)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lower Back",
        "secondary_muscles": ["Glutes", "Hamstrings"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Lower Back Machine",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lower Back",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Good Mornings",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Lower Back",
        "secondary_muscles": ["Glutes", "Hamstrings"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Shrugs",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Traps",
        "secondary_muscles": ["Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Shrugs",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Traps",
        "secondary_muscles": ["Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Shrug Machine (Plate Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Traps",
        "secondary_muscles": ["Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Trap Bar Shrugs",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Traps",
        "secondary_muscles": ["Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Upright Rows",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Traps",
        "secondary_muscles": ["Biceps", "Lateral Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Upright Rows (Shoulder Focus / Wide Grip)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Traps",
        "secondary_muscles": ["Biceps", "Lateral Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Face Pulls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Posterior Delt", "Traps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Deficit Deadlift",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Lower Back",
        "secondary_muscles": ["Traps", "Forearms", "Glutes", "Hamstrings", "Lats"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
]