"""Back entries for the global exercise database."""

BACK_EXERCISES = [
    {
        "name": "Barbell Row",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg",
        "instructions": [
            "Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.",
            "Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.",
            "Then inhale and slowly lower the barbell back to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Lower Back",
            "Biceps",
            "Forearms",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Pendlay Row",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg",
        "instructions": [
            "Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.",
            "Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.",
            "Then inhale and slowly lower the barbell back to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Lower Back",
            "Traps",
            "Biceps",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Deficit Barbell Row",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg",
        "instructions": [
            "Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.",
            "Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.",
            "Then inhale and slowly lower the barbell back to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Lower Back",
            "Biceps",
            "Forearms",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "T-Bar Row",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_T-Bar_Row/0.jpg",
        "instructions": [
            "Load up the T-bar Row Machine with the desired weight and adjust the leg height so that your upper chest is at the top of the pad. Tip: In some machines all you can do is stand on the appropriate step that allows you to be at a height that has the upper chest at the top of the pad.",
            "Lay face down on the pad and grab the handles. You can either use a palms down, palms up, or palms in position depending on what part of your back you want to emphasize.",
            "Lift the bar off the rack and extend your arms in front of you. This will be your starting position.",
            "As you exhale slowly pull the weight up and squeeze your back at the top of the movement. Tip: Keep the upper arms as close to the torso as possible throughout the movement in order to better engage the back muscles. Also, do not lift your body off of the pad at any time and refrain from using the biceps to lift the weight.",
            "After a second contraction at the top of the movement, as you inhale, slowly go back down to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Lower Back",
            "Traps",
            "Biceps",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Barbell Seal Row",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg",
        "instructions": [
            "Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.",
            "Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.",
            "Then inhale and slowly lower the barbell back to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Traps",
            "Biceps",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Single Arm Dumbbell Row",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg",
        "instructions": [
            "Choose a flat bench and place a dumbbell on each side of it.",
            "Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support.",
            "Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position.",
            "Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. Also, make sure that the force is performed with the back muscles and not the arms. Finally, the upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the dumbbell; therefore do not try to pull the dumbbell up using the forearms.",
            "Lower the resistance straight down to the starting position. Breathe in as you perform this step.",
            "Repeat the movement for the specified amount of repetitions.",
            "Switch sides and repeat again with the other arm.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Posterior Delt",
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Bench Chest Supported Dumbbell Row",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Two-Dumbbell_Row/0.jpg",
        "instructions": [
            "With a dumbbell in each hand (palms facing your torso), bend your knees slightly and bring your torso forward by bending at the waist; as you bend make sure to keep your back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The weights should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.",
            "While keeping the torso stationary, lift the dumbbells to your side (as you breathe out), keeping the elbows close to the body (do not exert any force with the forearm other than holding the weights). On the top contracted position, squeeze the back muscles and hold for a second.",
            "Slowly lower the weight again to the starting position as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Posterior Delt",
            "Traps",
            "Biceps",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Single-Arm Landmine Row (Meadows Row)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Long_Bar_Row/0.jpg",
        "instructions": [
            "Position a bar into a landmine or in a corner to keep it from moving. Load an appropriate weight onto your end.",
            "Stand next to the bar, and take a grip with one hand close to the collar. Using your hips and legs, rise to a standing position.",
            "Assume a bent-knee stance with your hips back and your chest up. Your arm should be extended. This will be your starting position.",
            "Pull the weight to your side by retracting the shoulder and flexing the elbow. Do not jerk the weight or cheat during the movement.",
            "After a brief pause, return to the starting position.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Posterior Delt",
            "Traps",
            "Biceps",
            "Forearms",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Renegade Row",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Renegade_Row/0.jpg",
        "instructions": [
            "Place two kettlebells on the floor about shoulder width apart. Position yourself on your toes and your hands as though you were doing a pushup, with the body straight and extended. Use the handles of the kettlebells to support your upper body. You may need to position your feet wide for support.",
            "Push one kettlebell into the floor and row the other kettlebell, retracting the shoulder blade of the working side as you flex the elbow, pulling it to your side.",
            "Then lower the kettlebell to the floor and begin the kettlebell in the opposite hand. Repeat for several reps.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Biceps",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Pull-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Weighted_Pull_Ups/0.jpg",
        "instructions": [
            "Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.",
            "You'll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.",
            "Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.",
            "After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched.",
        ],
        "equipment": "None",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Weighted Pull-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Weighted_Pull_Ups/0.jpg",
        "instructions": [
            "Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.",
            "You'll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.",
            "Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.",
            "After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Assisted Pull-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Assisted_Pull-Up/0.jpg",
        "instructions": [
            "Choke the band around the center of the pullup bar. You can use different bands to provide varying levels of assistance.",
            "Pull the end of the band down, and place one bent knee into the loop, ensuring it won't slip out. Take a medium to wide grip on the bar. This will be your starting position.",
            "Pull yourself upward by contracting the lats as you flex the elbow. The elbow should be driven to your side. Pull to the front, attempting to get your chin over the bar. Avoid swinging or jerking movements.",
            "After a brief pause, return to the starting position.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Chin-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg",
        "instructions": [
            "Grab the pull-up bar with the palms facing your torso and a grip closer than the shoulder width.",
            "As you have both arms extended in front of you holding the bar at the chosen grip width, keep your torso as straight as possible while creating a curvature on your lower back and sticking your chest out. This is your starting position. Tip: Keeping the torso as straight as possible maximizes biceps stimulation while minimizing back involvement.",
            "As you breathe out, pull your torso up until your head is around the level of the pull-up bar. Concentrate on using the biceps muscles in order to perform the movement. Keep the elbows close to your body. Tip: The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.",
            "After a second of squeezing the biceps in the contracted position, slowly lower your torso back to the starting position; when your arms are fully extended. Breathe in as you perform this portion of the movement.",
            "Repeat this motion for the prescribed amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Weighted Chin-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Weighted_Pull_Ups/0.jpg",
        "instructions": [
            "Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.",
            "You'll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.",
            "Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.",
            "After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Assisted Chin-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Assisted_Pull-Up/0.jpg",
        "instructions": [
            "Choke the band around the center of the pullup bar. You can use different bands to provide varying levels of assistance.",
            "Pull the end of the band down, and place one bent knee into the loop, ensuring it won't slip out. Take a medium to wide grip on the bar. This will be your starting position.",
            "Pull yourself upward by contracting the lats as you flex the elbow. The elbow should be driven to your side. Pull to the front, attempting to get your chin over the bar. Avoid swinging or jerking movements.",
            "After a brief pause, return to the starting position.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Neutral Grip Pull-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Neutral Grip Weighted Pull-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Weighted_Pull_Ups/0.jpg",
        "instructions": [
            "Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.",
            "You'll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.",
            "Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.",
            "After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Neutral Grip Assisted Pull-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Assisted_Pull-Up/0.jpg",
        "instructions": [
            "Choke the band around the center of the pullup bar. You can use different bands to provide varying levels of assistance.",
            "Pull the end of the band down, and place one bent knee into the loop, ensuring it won't slip out. Take a medium to wide grip on the bar. This will be your starting position.",
            "Pull yourself upward by contracting the lats as you flex the elbow. The elbow should be driven to your side. Pull to the front, attempting to get your chin over the bar. Avoid swinging or jerking movements.",
            "After a brief pause, return to the starting position.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Wide-Grip Pull-Downs",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg",
        "instructions": [
            "Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.",
            "Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.",
            "As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.",
            "As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.",
            "After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.",
            "Repeat this motion for the prescribed amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Close-Grip Pull-Downs",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/0.jpg",
        "instructions": [
            "Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.",
            "Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.",
            "As you have both arms extended in front of you - while holding the bar at the chosen grip width - bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.",
            "As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary (only the arms should move). The forearms should do no other work except for holding the bar; therefore do not try to pull the bar down using the forearms.",
            "After a second in the contracted position, while squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.",
            "6. Repeat this motion for the prescribed amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Neutral Grip Pull-Downs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Medium Width Pull-Downs",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Full_Range-Of-Motion_Lat_Pulldown/0.jpg",
        "instructions": [
            "Either standing or seated on a high bench, grasp two stirrup cables that are attached to the high pulleys. Grab with the opposing hand so your arms are crisscrossed about you and your palms are facing forward.",
            "Keeping your chest up and maintaining a slight arch in your lower back, pull the handles down as if you were doing a regular pulldown. The range of motion will be more of an arc. During the movement, rotate your hands so that in the bottom position your palms face each other rather than forward. Return slowly to the starting position and repeat.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Reverse Grip Pull-Downs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Single Hand Pull-Downs",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One_Arm_Lat_Pulldown/0.jpg",
        "instructions": [
            "Select an appropriate weight and adjust the knee pad to help keep you down. Grasp the handle with a pronated grip. This will be your starting position.",
            "Pull the handle down, squeezing your elbow to your side as you flex the elbow.",
            "Pause at the bottom of the motion, and then slowly return the handle to the starting position.",
            "For multiple repetitions, avoid completely returning the weight to keep tension on the muscles being worked.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Pull-Down Machine (Plate / Pin Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Full_Range-Of-Motion_Lat_Pulldown/0.jpg",
        "instructions": [
            "Either standing or seated on a high bench, grasp two stirrup cables that are attached to the high pulleys. Grab with the opposing hand so your arms are crisscrossed about you and your palms are facing forward.",
            "Keeping your chest up and maintaining a slight arch in your lower back, pull the handles down as if you were doing a regular pulldown. The range of motion will be more of an arc. During the movement, rotate your hands so that in the bottom position your palms face each other rather than forward. Return slowly to the starting position and repeat.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Wide Grip Cable Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Posterior Delt",
            "Traps",
            "Biceps",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Close Grip Cable Rows",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elevated_Cable_Rows/0.jpg",
        "instructions": [
            "Get a platform of some sort (it can be an aerobics or calf raise platform) that is around 4-6 inches in height.",
            "Place it on the seat of the cable row machine.",
            "Sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked.",
            "Lean over as you keep the natural alignment of your back and grab the V-bar handles.",
            "With your arms extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lats as you hold the bar in front of you. This is the starting position of the exercise.",
            "Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it until you touch the abdominals. Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard. Hold that contraction for a second and slowly go back to the original position while breathing in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Neutral Grip Cable Rows",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Iso_Row/0.jpg",
        "instructions": [
            "Load an appropriate weight onto the pins and adjust the seat height so that the handles are at chest level. Grasp the handles with either a neutral or pronated grip. This will be your starting position.",
            "Pull the handles towards your torso, retracting your shoulder blades as you flex the elbow.",
            "Pause at the bottom of the motion, and then slowly return the handles to the starting position. For multiple repetitions, avoid completely returning the weight to the stops to keep tension on the muscles being worked.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Single Hand Cable Rows",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_One-arm_Cable_Pulley_Rows/0.jpg",
        "instructions": [
            "To get into the starting position, first sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked.",
            "Lean over as you keep the natural alignment of your back and grab the single handle attachment with your left arm using a palms-down grip.",
            "With your arm extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lat as you hold the bar in front of you. The right arm can be kept by the waist. This is the starting position of the exercise.",
            "Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it as you rotate the wrist, so that by the time your hand is by your abdominals it is in a neutral position (palms facing the torso). Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard.",
            "Hold that contraction for a second and slowly go back to the original position while breathing in. Tip: Remember to rotate the wrist as you go back to the starting position so that the palms are facing down again.",
            "Repeat for the recommended amount of repetitions and then perform the same movement with the right hand.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Chest Supported Iso-Lateral Rows",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Iso_Row/0.jpg",
        "instructions": [
            "Load an appropriate weight onto the pins and adjust the seat height so that the handles are at chest level. Grasp the handles with either a neutral or pronated grip. This will be your starting position.",
            "Pull the handles towards your torso, retracting your shoulder blades as you flex the elbow.",
            "Pause at the bottom of the motion, and then slowly return the handles to the starting position. For multiple repetitions, avoid completely returning the weight to the stops to keep tension on the muscles being worked.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Posterior Delt",
            "Traps",
            "Biceps",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Low to High Chest Supported Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Traps",
        "secondary_muscles": [
            "Posterior Delt",
            "Biceps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "High to Low Chest Supported Rows",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [
            "Biceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Chest Supported Rows (Pin Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_T-Bar_Row/0.jpg",
        "instructions": [
            "Load up the T-bar Row Machine with the desired weight and adjust the leg height so that your upper chest is at the top of the pad. Tip: In some machines all you can do is stand on the appropriate step that allows you to be at a height that has the upper chest at the top of the pad.",
            "Lay face down on the pad and grab the handles. You can either use a palms down, palms up, or palms in position depending on what part of your back you want to emphasize.",
            "Lift the bar off the rack and extend your arms in front of you. This will be your starting position.",
            "As you exhale slowly pull the weight up and squeeze your back at the top of the movement. Tip: Keep the upper arms as close to the torso as possible throughout the movement in order to better engage the back muscles. Also, do not lift your body off of the pad at any time and refrain from using the biceps to lift the weight.",
            "After a second contraction at the top of the movement, as you inhale, slowly go back down to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Traps",
            "Biceps",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Chest Supported T-Bar Rows",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_T-Bar_Row/0.jpg",
        "instructions": [
            "Load up the T-bar Row Machine with the desired weight and adjust the leg height so that your upper chest is at the top of the pad. Tip: In some machines all you can do is stand on the appropriate step that allows you to be at a height that has the upper chest at the top of the pad.",
            "Lay face down on the pad and grab the handles. You can either use a palms down, palms up, or palms in position depending on what part of your back you want to emphasize.",
            "Lift the bar off the rack and extend your arms in front of you. This will be your starting position.",
            "As you exhale slowly pull the weight up and squeeze your back at the top of the movement. Tip: Keep the upper arms as close to the torso as possible throughout the movement in order to better engage the back muscles. Also, do not lift your body off of the pad at any time and refrain from using the biceps to lift the weight.",
            "After a second contraction at the top of the movement, as you inhale, slowly go back down to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Traps",
            "Biceps",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Smith Machine Rows",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Upright_Row/0.jpg",
        "instructions": [
            "To begin, set the bar on the smith machine to a height that is around the middle of your thighs. Once the correct height is chosen and the bar is loaded, grasp the bar using a pronated (palms forward) grip that is shoulder width apart. You may need some wrist wraps if using a significant amount of weight.",
            "Lift the barbell up and fully extend your arms with your back straight. There should be a slight bend at the elbows. This is the starting position.",
            "Use your side shoulders to lift the bar as you exhale. The bar should be close to the body as you move it up. Continue to lift it until it nearly touches your chin. Tip: Your elbows should drive the motion. As you lift the bar, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement.",
            "Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Lower Back",
            "Biceps",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Bench Chest Supported Smith Machine Rows",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_T-Bar_Row/0.jpg",
        "instructions": [
            "Load up the T-bar Row Machine with the desired weight and adjust the leg height so that your upper chest is at the top of the pad. Tip: In some machines all you can do is stand on the appropriate step that allows you to be at a height that has the upper chest at the top of the pad.",
            "Lay face down on the pad and grab the handles. You can either use a palms down, palms up, or palms in position depending on what part of your back you want to emphasize.",
            "Lift the bar off the rack and extend your arms in front of you. This will be your starting position.",
            "As you exhale slowly pull the weight up and squeeze your back at the top of the movement. Tip: Keep the upper arms as close to the torso as possible throughout the movement in order to better engage the back muscles. Also, do not lift your body off of the pad at any time and refrain from using the biceps to lift the weight.",
            "After a second contraction at the top of the movement, as you inhale, slowly go back down to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Traps",
            "Biceps",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Rope Pull-Over",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/0.jpg",
        "instructions": [
            "You will start by grabbing the wide bar from the top pulley of a pulldown machine and using a wider than shoulder-width pronated (palms down) grip. Step backwards two feet or so.",
            "Bend your torso forward at the waist by around 30-degrees with your arms fully extended in front of you and a slight bend at the elbows. If your arms are not fully extended then you need to step a bit more backwards until they are. Once your arms are fully extended and your torso is slightly bent at the waist, tighten the lats and then you are ready to begin.",
            "While keeping the arms straight, pull the bar down by contracting the lats until your hands are next to the side of the thighs. Breathe out as you perform this step.",
            "While keeping the arms straight, go back to the starting position while breathing in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Straight Bar Pull-Over",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/0.jpg",
        "instructions": [
            "You will start by grabbing the wide bar from the top pulley of a pulldown machine and using a wider than shoulder-width pronated (palms down) grip. Step backwards two feet or so.",
            "Bend your torso forward at the waist by around 30-degrees with your arms fully extended in front of you and a slight bend at the elbows. If your arms are not fully extended then you need to step a bit more backwards until they are. Once your arms are fully extended and your torso is slightly bent at the waist, tighten the lats and then you are ready to begin.",
            "While keeping the arms straight, pull the bar down by contracting the lats until your hands are next to the side of the thighs. Breathe out as you perform this step.",
            "While keeping the arms straight, go back to the starting position while breathing in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "V-Bar Pull-Over",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/0.jpg",
        "instructions": [
            "You will start by grabbing the wide bar from the top pulley of a pulldown machine and using a wider than shoulder-width pronated (palms down) grip. Step backwards two feet or so.",
            "Bend your torso forward at the waist by around 30-degrees with your arms fully extended in front of you and a slight bend at the elbows. If your arms are not fully extended then you need to step a bit more backwards until they are. Once your arms are fully extended and your torso is slightly bent at the waist, tighten the lats and then you are ready to begin.",
            "While keeping the arms straight, pull the bar down by contracting the lats until your hands are next to the side of the thighs. Breathe out as you perform this step.",
            "While keeping the arms straight, go back to the starting position while breathing in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Wide Grip Pull-Over",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/0.jpg",
        "instructions": [
            "You will start by grabbing the wide bar from the top pulley of a pulldown machine and using a wider than shoulder-width pronated (palms down) grip. Step backwards two feet or so.",
            "Bend your torso forward at the waist by around 30-degrees with your arms fully extended in front of you and a slight bend at the elbows. If your arms are not fully extended then you need to step a bit more backwards until they are. Once your arms are fully extended and your torso is slightly bent at the waist, tighten the lats and then you are ready to begin.",
            "While keeping the arms straight, pull the bar down by contracting the lats until your hands are next to the side of the thighs. Breathe out as you perform this step.",
            "While keeping the arms straight, go back to the starting position while breathing in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Pull-Over Machine (Plate / Pin Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/0.jpg",
        "instructions": [
            "You will start by grabbing the wide bar from the top pulley of a pulldown machine and using a wider than shoulder-width pronated (palms down) grip. Step backwards two feet or so.",
            "Bend your torso forward at the waist by around 30-degrees with your arms fully extended in front of you and a slight bend at the elbows. If your arms are not fully extended then you need to step a bit more backwards until they are. Once your arms are fully extended and your torso is slightly bent at the waist, tighten the lats and then you are ready to begin.",
            "While keeping the arms straight, pull the bar down by contracting the lats until your hands are next to the side of the thighs. Breathe out as you perform this step.",
            "While keeping the arms straight, go back to the starting position while breathing in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Pullover (Lat-Focused)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent-Arm_Dumbbell_Pullover/0.jpg",
        "instructions": [
            "Place a dumbbell standing up on a flat bench.",
            "Ensuring that the dumbbell stays securely placed at the top of the bench, lie perpendicular to the bench (torso across it as in forming a cross) with only your shoulders lying on the surface. Hips should be below the bench and legs bent with feet firmly on the floor. The head will be off the bench as well.",
            "Grasp the dumbbell with both hands and hold it straight over your chest with a bend in your arms. Both palms should be pressing against the underside one of the sides of the dumbbell. This will be your starting position. Caution: Always ensure that the dumbbell used for this exercise is secure. Using a dumbbell with loose plates can result in the dumbbell falling apart and falling on your face.",
            "While keeping your arms locked in the bent arm position, lower the weight slowly in an arc behind your head while breathing in until you feel a stretch on the chest.",
            "At that point, bring the dumbbell back to the starting position using the arc through which the weight was lowered and exhale as you perform this movement.",
            "Hold the weight on the initial position for a second and repeat the motion for the prescribed number of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Lats",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Conventional Deadlift",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean_Deadlift/0.jpg",
        "instructions": [
            "Begin standing with a barbell close to your shins. Your feet should be directly under your hips with your feet turned out slightly. Grip the bar with a double overhand grip or hook grip, about shoulder width apart. Squat down to the bar. Your spine should be in full extension, with a back angle that places your shoulders in front of the bar and your back as vertical as possible.",
            "Begin by driving through the floor through the front of your heels. As the bar travels upward, maintain a constant back angle. Flare your knees out to the side to help keep them out of the bar's path.",
            "After the bar crosses the knees, complete the lift by driving the hips into the bar until your hips and knees are extended.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Lower Back",
        "secondary_muscles": [
            "Traps",
            "Forearms",
            "Glutes",
            "Hamstrings",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Sumo Deadlift",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/0.jpg",
        "instructions": [
            "Begin with a bar loaded on the ground. Approach the bar so that the bar intersects the middle of the feet. The feet should be set very wide, near the collars. Bend at the hips to grip the bar. The arms should be directly below the shoulders, inside the legs, and you can use a pronated grip, a mixed grip, or hook grip. Relax the shoulders, which in effect lengthens your arms.",
            "Take a breath, and then lower your hips, looking forward with your head with your chest up. Drive through the floor, spreading your feet apart, with your weight on the back half of your feet. Extend through the hips and knees.",
            "As the bar passes through the knees, lean back and drive the hips into the bar, pulling your shoulder blades together.",
            "Return the weight to the ground by bending at the hips and controlling the weight on the way down.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Lower Back",
        "secondary_muscles": [
            "Traps",
            "Glutes",
            "Hamstrings",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Rack Pulls / Block Pulls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rack_Pulls/0.jpg",
        "instructions": [
            "Set up in a power rack with the bar on the pins. The pins should be set to the desired point; just below the knees, just above, or in the mid thigh position. Position yourself against the bar in proper deadlifting position. Your feet should be under your hips, your grip shoulder width, back arched, and hips back to engage the hamstrings. Since the weight is typically heavy, you may use a mixed grip, a hook grip, or use straps to aid in holding the weight.",
            "With your head looking forward, extend through the hips and knees, pulling the weight up and back until lockout. Be sure to pull your shoulders back as you complete the movement.",
            "Return the weight to the pins and repeat.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Lower Back",
        "secondary_muscles": [
            "Traps",
            "Forearms",
            "Glutes",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Back Extensions (45-Degree)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hyperextensions_Back_Extensions/0.jpg",
        "instructions": [
            "Lie face down on a hyperextension bench, tucking your ankles securely under the footpads.",
            "Adjust the upper pad if possible so your upper thighs lie flat across the wide pad, leaving enough room for you to bend at the waist without any restriction.",
            "With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms.",
            "Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you feel a nice stretch on the hamstrings and you can no longer keep going without a rounding of the back. Tip: Never round the back as you perform this exercise. Also, some people can go farther than others. The key thing is that you go as far as your body allows you to without rounding the back.",
            "Slowly raise your torso back to the initial position as you inhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lower Back",
        "secondary_muscles": [
            "Glutes",
            "Hamstrings",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Lower Back Machine",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lower Back",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Barbell Good Mornings",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff_Leg_Barbell_Good_Morning/0.jpg",
        "instructions": [
            "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.",
            "Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.",
            "Step away from the rack and position your legs using a shoulder width medium stance. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position.",
            "Keeping your legs stationary, move your torso forward by bending at the hips while inhaling. Lower your torso until it is parallel with the floor.",
            "Begin to raise the bar as you exhale by elevating your torso back to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Lower Back",
        "secondary_muscles": [
            "Glutes",
            "Hamstrings",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Barbell Shrugs",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug/0.jpg",
        "instructions": [
            "Stand up straight with your feet at shoulder width as you hold a barbell with both hands in front of you using a pronated grip (palms facing the thighs). Tip: Your hands should be a little wider than shoulder width apart. You can use wrist wraps for this exercise for a better grip. This will be your starting position.",
            "Raise your shoulders up as far as you can go as you breathe out and hold the contraction for a second. Tip: Refrain from trying to lift the barbell by using your biceps.",
            "Slowly return to the starting position as you breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Traps",
        "secondary_muscles": [
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Shrugs",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shrug/0.jpg",
        "instructions": [
            "Stand erect with a dumbbell on each hand (palms facing your torso), arms extended on the sides.",
            "Lift the dumbbells by elevating the shoulders as high as possible while you exhale. Hold the contraction at the top for a second. Tip: The arms should remain extended at all times. Refrain from using the biceps to help lift the dumbbells. Only the shoulders should be moving up and down.",
            "Lower the dumbbells back to the original position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Traps",
        "secondary_muscles": [
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Shrug Machine (Plate Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Shrug/0.jpg",
        "instructions": [
            "Load the pins to an appropriate weight. Position yourself directly between the handles.",
            "Grasp the top handles with a comfortable grip, and then lower your hips as you take a breath. Look forward with your head and keep your chest up.",
            "Drive through the floor with your heels, extending your hips and knees as you rise to a standing position. Keep your arms straight throughout the movement, finishing with your shoulders back. This will be your starting position.",
            "Raise the weight by shrugging the shoulders towards your ears, moving straight up and down.",
            "Pause at the top of the motion, and then return the weight to the starting position.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Traps",
        "secondary_muscles": [
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Trap Bar Shrugs",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug/0.jpg",
        "instructions": [
            "Stand up straight with your feet at shoulder width as you hold a barbell with both hands in front of you using a pronated grip (palms facing the thighs). Tip: Your hands should be a little wider than shoulder width apart. You can use wrist wraps for this exercise for a better grip. This will be your starting position.",
            "Raise your shoulders up as far as you can go as you breathe out and hold the contraction for a second. Tip: Refrain from trying to lift the barbell by using your biceps.",
            "Slowly return to the starting position as you breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Traps",
        "secondary_muscles": [
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Upright Rows",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg",
        "instructions": [
            "Grasp a barbell with an overhand grip that is slightly less than shoulder width. The bar should be resting on the top of your thighs with your arms extended and a slight bend in your elbows. Your back should also be straight. This will be your starting position.",
            "Now exhale and use the sides of your shoulders to lift the bar, raising your elbows up and to the side. Keep the bar close to your body as you raise it. Continue to lift the bar until it nearly touches your chin. Tip: Your elbows should drive the motion, and should always be higher than your forearms. Remember to keep your torso stationary and pause for a second at the top of the movement.",
            "Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Traps",
        "secondary_muscles": [
            "Biceps",
            "Lateral Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cable Upright Rows (Shoulder Focus / Wide Grip)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg",
        "instructions": [
            "Grasp a barbell with an overhand grip that is slightly less than shoulder width. The bar should be resting on the top of your thighs with your arms extended and a slight bend in your elbows. Your back should also be straight. This will be your starting position.",
            "Now exhale and use the sides of your shoulders to lift the bar, raising your elbows up and to the side. Keep the bar close to your body as you raise it. Continue to lift the bar until it nearly touches your chin. Tip: Your elbows should drive the motion, and should always be higher than your forearms. Remember to keep your torso stationary and pause for a second at the top of the movement.",
            "Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Traps",
        "secondary_muscles": [
            "Biceps",
            "Lateral Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Face Pulls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg",
        "instructions": [
            "Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Mid Back",
        "secondary_muscles": [
            "Posterior Delt",
            "Traps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Deficit Deadlift",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Deficit_Deadlift/0.jpg",
        "instructions": [
            "Begin by having a platform or weight plates that you can stand on, usually 1-3 inches in height. Approach the bar so that it is centered over your feet. You feet should be about hip width apart. Bend at the hip to grip the bar at shoulder width, allowing your shoulder blades to protract. Typically, you would use an overhand grip or an over/under grip on heavier sets.",
            "With your feet, and your grip set, take a big breath and then lower your hips and bend the knees until your shins contact the bar. Look forward with your head, keep your chest up and your back arched, and begin driving through the heels to move the weight upward. After the bar passes the knees, aggressively pull the bar back, pulling your shoulder blades together as you drive your hips forward into the bar.",
            "Lower the bar by bending at the hips and guiding it to the floor.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Lower Back",
        "secondary_muscles": [
            "Traps",
            "Forearms",
            "Glutes",
            "Hamstrings",
            "Lats",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
]
