"""Biceps entries for the global exercise database."""

BICEPS_EXERCISES = [
    {
        "name": "Straight Bar Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Cable_Curls/0.jpg",
        "instructions": [
            "Stand between a couple of high pulleys and grab a handle in each arm. Position your upper arms in a way that they are parallel to the floor with the palms of your hands facing you. This will be your starting position.",
            "Curl the handles towards you until they are next to your ears. Make sure that as you do so you flex your biceps and exhale. The upper arms should remain stationary and only the forearms should move. Hold for a second in the contracted position as you squeeze the biceps.",
            "Slowly bring back the arms to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "EZ-Bar Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Curl/0.jpg",
        "instructions": [
            "Stand up straight while holding an EZ curl bar at the wide outer handle. The palms of your hands should be facing forward and slightly tilted inward due to the shape of the bar. Keep your elbows close to your torso. This will be your starting position.",
            "Now, while keeping your upper arms stationary, exhale and curl the weights forward while contracting the biceps. Focus on only moving your forearms.",
            "Continue to raise the weight until your biceps are fully contracted and the bar is at shoulder level. Hold the top contracted position for a moment and squeeze the biceps.",
            "Then inhale and slowly lower the bar back to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Strict Wall-Supported Barbell Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg",
        "instructions": [
            "Stand up with your torso upright while holding a barbell at a shoulder-width grip. The palm of your hands should be facing forward and the elbows should be close to the torso. This will be your starting position.",
            "While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move.",
            "Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.",
            "Slowly begin to bring the bar back to starting position as your breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Reverse Barbell Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Barbell_Curl/0.jpg",
        "instructions": [
            "Stand up with your torso upright while holding a barbell at shoulder width with the elbows close to the torso. The palm of your hands should be facing down (pronated grip). This will be your starting position.",
            "While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.",
            "Slowly begin to bring the bar back to starting position as your breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Brachialis",
        "secondary_muscles": [
            "Biceps",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Reverse EZ-Bar Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Barbell_Curl/0.jpg",
        "instructions": [
            "Stand up with your torso upright while holding a barbell at shoulder width with the elbows close to the torso. The palm of your hands should be facing down (pronated grip). This will be your starting position.",
            "While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.",
            "Slowly begin to bring the bar back to starting position as your breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Brachialis",
        "secondary_muscles": [
            "Biceps",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Standing Dumbbell Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Reverse_Curl/0.jpg",
        "instructions": [
            "To begin, stand straight with a dumbbell in each hand using a pronated grip (palms facing down). Your arms should be fully extended while your feet are shoulder width apart from each other. This is the starting position.",
            "While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the muscle.",
            "Slowly begin to bring the dumbbells back to starting position as your breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Sitting Dumbbell Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Dumbbell_Curl/0.jpg",
        "instructions": [
            "Sit on a flat bench with a dumbbell on each hand being held at arms length. The elbows should be close to the torso.",
            "Rotate the palms of the hands so that they are facing your torso. This will be your starting position.",
            "While holding the upper arm stationary, curl the weights and start twisting the wrists once the dumbbells pass your thighs so that the palms of your hands face forward at the end of the movement. Make sure that you contract the biceps as you breathe out and make sure that only the forearms move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps.",
            "Slowly begin to bring the dumbbells back to the starting position as your breathe in and as you rotate the wrists back to a neutral grip.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Incline Dumbbell Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg",
        "instructions": [
            "Sit back on an incline bench with a dumbbell in each hand held at arms length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.",
            "While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second.",
            "Slowly begin to bring the dumbbells back to starting position as your breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Hammer Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Hammer_Dumbbell_Curl/0.jpg",
        "instructions": [
            "Place the upper part of both arms on top of the preacher bench as you hold a dumbbell in each hand with the palms facing each other (neutral grip).",
            "As you breathe in, slowly lower the dumbbells until your upper arm is extended and the biceps is fully stretched.",
            "As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the dumbbells are at shoulder height.",
            "Squeeze the biceps hard for a second at the contracted position and repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Brachialis",
        "secondary_muscles": [
            "Biceps",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cross-Body Dumbbell Hammer Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cross_Body_Hammer_Curl/0.jpg",
        "instructions": [
            "Stand up straight with a dumbbell in each hand. Your hands should be down at your side with your palms facing in.",
            "While keeping your palms facing in and without twisting your arm, curl the dumbbell of the right arm up towards your left shoulder as you exhale. Touch the top of the dumbbell to your shoulder and hold the contraction for a second.",
            "Slowly lower the dumbbell along the same path as you inhale and then repeat the same movement for the left arm.",
            "Continue alternating in this fashion until the recommended amount of repetitions is performed for each arm.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Brachialis",
        "secondary_muscles": [
            "Biceps",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Concentration Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curls/0.jpg",
        "instructions": [
            "Sit down on a flat bench with one dumbbell in front of you between your legs. Your legs should be spread with your knees bent and feet on the floor.",
            "Use your right arm to pick the dumbbell up. Place the back of your right upper arm on the top of your inner right thigh. Rotate the palm of your hand until it is facing forward away from your thigh. Tip: Your arm should be extended and the dumbbell should be above the floor. This will be your starting position.",
            "While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Tip: At the top of the movement make sure that the little finger of your arm is higher than your thumb. This guarantees a good contraction. Hold the contracted position for a second as you squeeze the biceps.",
            "Slowly begin to bring the dumbbells back to starting position as your breathe in. Caution: Avoid swinging motions at any time.",
            "Repeat for the recommended amount of repetitions. Then repeat the movement with the left arm.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Bench Supported Dumbbell Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Dumbbell_Curl/0.jpg",
        "instructions": [
            "Sit on a flat bench with a dumbbell on each hand being held at arms length. The elbows should be close to the torso.",
            "Rotate the palms of the hands so that they are facing your torso. This will be your starting position.",
            "While holding the upper arm stationary, curl the weights and start twisting the wrists once the dumbbells pass your thighs so that the palms of your hands face forward at the end of the movement. Make sure that you contract the biceps as you breathe out and make sure that only the forearms move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps.",
            "Slowly begin to bring the dumbbells back to the starting position as your breathe in and as you rotate the wrists back to a neutral grip.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Spider Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Supine_Dumbbell_Curl/0.jpg",
        "instructions": [
            "Lie down on a flat bench face up while holding a dumbbell in each arm on top of your thighs.",
            "Bring the dumbbells to the sides with the arms extended and the palms of the hands facing your thighs (neutral grip).",
            "While keeping the arms close to your torso and elbows in, slowly lower your arms (as you keep them extended with a slight bend at the elbows) as far down towards the floor as you can go. Once you cannot go down any further, lock your upper arms in that position and that will be your starting position.",
            "As you breathe out, slowly begin to curl the weights up as you simultaneously rotate your wrists so that the palms of the hands face up. Continue curling the weight until your biceps are fully contracted and squeeze hard at the top position for a second. Tip: Only the forearms should move. Upper arms should remain stationary and elbows should stay in throughout the movement.",
            "Return back to the starting position very slowly.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Straight Bar Spider Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Spider_Curl/0.jpg",
        "instructions": [
            "Start out by setting the bar on the part of the preacher bench that you would normally sit on. Make sure to align the barbell properly so that it is balanced and will not fall off.",
            "Move to the front side of the preacher bench (the part where the arms usually lay) and position yourself to lay at a 45 degree slant with your torso and stomach pressed against the front side of the preacher bench.",
            "Make sure that your feet (especially the toes) are well positioned on the floor and place your upper arms on top of the pad located on the inside part of the preacher bench.",
            "Use your arms to grab the barbell with a supinated grip (palms facing up) at about shoulder width apart or slightly closer from each other.",
            "Slowly begin to lift the barbell upwards and exhale. Hold the contracted position for a second as you squeeze the biceps.",
            "Slowly begin to bring the barbell back to the starting position as your breathe in. .",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "EZ-Bar Spider Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Spider_Curl/0.jpg",
        "instructions": [
            "Start out by setting the bar on the part of the preacher bench that you would normally sit on. Make sure to align the barbell properly so that it is balanced and will not fall off.",
            "Move to the front side of the preacher bench (the part where the arms usually lay) and position yourself to lay at a 45 degree slant with your torso and stomach pressed against the front side of the preacher bench.",
            "Make sure that your feet (especially the toes) are well positioned on the floor and place your upper arms on top of the pad located on the inside part of the preacher bench.",
            "Use your arms to grab the barbell with a supinated grip (palms facing up) at about shoulder width apart or slightly closer from each other.",
            "Slowly begin to lift the barbell upwards and exhale. Hold the contracted position for a second as you squeeze the biceps.",
            "Slowly begin to bring the barbell back to the starting position as your breathe in. .",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Straight Preacher Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg",
        "instructions": [
            "To perform this movement you will need a preacher bench and an E-Z bar. Grab the E-Z curl bar at the close inner handle (either have someone hand you the bar which is preferable or grab the bar from the front bar rest provided by most preacher benches). The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar.",
            "With the upper arms positioned against the preacher bench pad and the chest against it, hold the E-Z Curl Bar at shoulder length. This will be your starting position.",
            "As you breathe in, slowly lower the bar until your upper arm is extended and the biceps is fully stretched.",
            "As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "EZ-Bar Preacher Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg",
        "instructions": [
            "To perform this movement you will need a preacher bench and an E-Z bar. Grab the E-Z curl bar at the close inner handle (either have someone hand you the bar which is preferable or grab the bar from the front bar rest provided by most preacher benches). The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar.",
            "With the upper arms positioned against the preacher bench pad and the chest against it, hold the E-Z Curl Bar at shoulder length. This will be your starting position.",
            "As you breathe in, slowly lower the bar until your upper arm is extended and the biceps is fully stretched.",
            "As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Preacher Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Hammer_Dumbbell_Curl/0.jpg",
        "instructions": [
            "Place the upper part of both arms on top of the preacher bench as you hold a dumbbell in each hand with the palms facing each other (neutral grip).",
            "As you breathe in, slowly lower the dumbbells until your upper arm is extended and the biceps is fully stretched.",
            "As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the dumbbells are at shoulder height.",
            "Squeeze the biceps hard for a second at the contracted position and repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Hammer Preacher Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Hammer_Dumbbell_Curl/0.jpg",
        "instructions": [
            "Place the upper part of both arms on top of the preacher bench as you hold a dumbbell in each hand with the palms facing each other (neutral grip).",
            "As you breathe in, slowly lower the dumbbells until your upper arm is extended and the biceps is fully stretched.",
            "As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the dumbbells are at shoulder height.",
            "Squeeze the biceps hard for a second at the contracted position and repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Brachialis",
        "secondary_muscles": [
            "Biceps",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Preacher Curls Machine (Plate Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Preacher_Curls/0.jpg",
        "instructions": [
            "Sit down on the Preacher Curl Machine and select the weight.",
            "Place the back of your upper arms (your triceps) on the preacher pad provided and grab the handles using an underhand grip (palms facing up). Tip: Make sure that when you place the arms on the pad you keep the elbows in. This will be your starting position.",
            "Now lift the handles as you exhale and you contract the biceps. At the top of the position make sure that you hold the contraction for a second. Tip: Only the forearms should move. The upper arms should remain stationary and on the pad at all times.",
            "Lower the handles slowly back to the starting position as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Preacher Curls Machine (Pin Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Preacher_Curls/0.jpg",
        "instructions": [
            "Sit down on the Preacher Curl Machine and select the weight.",
            "Place the back of your upper arms (your triceps) on the preacher pad provided and grab the handles using an underhand grip (palms facing up). Tip: Make sure that when you place the arms on the pad you keep the elbows in. This will be your starting position.",
            "Now lift the handles as you exhale and you contract the biceps. At the top of the position make sure that you hold the contraction for a second. Tip: Only the forearms should move. The upper arms should remain stationary and on the pad at all times.",
            "Lower the handles slowly back to the starting position as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Straight Bar Cable Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Cable_Curls/0.jpg",
        "instructions": [
            "Stand between a couple of high pulleys and grab a handle in each arm. Position your upper arms in a way that they are parallel to the floor with the palms of your hands facing you. This will be your starting position.",
            "Curl the handles towards you until they are next to your ears. Make sure that as you do so you flex your biceps and exhale. The upper arms should remain stationary and only the forearms should move. Hold for a second in the contracted position as you squeeze the biceps.",
            "Slowly bring back the arms to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "D-Handle Cable Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Cable_Curls/0.jpg",
        "instructions": [
            "Stand between a couple of high pulleys and grab a handle in each arm. Position your upper arms in a way that they are parallel to the floor with the palms of your hands facing you. This will be your starting position.",
            "Curl the handles towards you until they are next to your ears. Make sure that as you do so you flex your biceps and exhale. The upper arms should remain stationary and only the forearms should move. Hold for a second in the contracted position as you squeeze the biceps.",
            "Slowly bring back the arms to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Rope Cable Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Hammer_Curls_-_Rope_Attachment/0.jpg",
        "instructions": [
            "Attach a rope attachment to a low pulley and stand facing the machine about 12 inches away from it.",
            "Grasp the rope with a neutral (palms-in) grip and stand straight up keeping the natural arch of the back and your torso stationary.",
            "Put your elbows in by your side and keep them there stationary during the entire movement. Tip: Only the forearms should move; not your upper arms. This will be your starting position.",
            "Using your biceps, pull your arms up as you exhale until your biceps touch your forearms. Tip: Remember to keep the elbows in and your upper arms stationary.",
            "After a 1 second contraction where you squeeze your biceps, slowly start to bring the weight back to the original position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Brachialis",
        "secondary_muscles": [
            "Biceps",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Single Hand Cable Hammer Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Hammer_Curls_-_Rope_Attachment/0.jpg",
        "instructions": [
            "Attach a rope attachment to a low pulley and stand facing the machine about 12 inches away from it.",
            "Grasp the rope with a neutral (palms-in) grip and stand straight up keeping the natural arch of the back and your torso stationary.",
            "Put your elbows in by your side and keep them there stationary during the entire movement. Tip: Only the forearms should move; not your upper arms. This will be your starting position.",
            "Using your biceps, pull your arms up as you exhale until your biceps touch your forearms. Tip: Remember to keep the elbows in and your upper arms stationary.",
            "After a 1 second contraction where you squeeze your biceps, slowly start to bring the weight back to the original position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Brachialis",
        "secondary_muscles": [
            "Biceps",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Bayesian Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Reverse Cable Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Cable_Curl/0.jpg",
        "instructions": [
            "Stand up with your torso upright while holding a bar attachment that is attached to a low pulley using a pronated (palms down) and shoulder width grip. Make sure also that you keep the elbows close to the torso. This will be your starting position.",
            "While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.",
            "Slowly begin to bring the bar back to starting position as your breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Brachialis",
        "secondary_muscles": [
            "Biceps",
            "Forearms",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "High Pulley Cable Curls (Crucifix Curls)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Cable_Curls/0.jpg",
        "instructions": [
            "Stand between a couple of high pulleys and grab a handle in each arm. Position your upper arms in a way that they are parallel to the floor with the palms of your hands facing you. This will be your starting position.",
            "Curl the handles towards you until they are next to your ears. Make sure that as you do so you flex your biceps and exhale. The upper arms should remain stationary and only the forearms should move. Hold for a second in the contracted position as you squeeze the biceps.",
            "Slowly bring back the arms to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Incline Curls Machine",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Hammer_Curls/0.jpg",
        "instructions": [
            "Seat yourself on an incline bench with a dumbbell in each hand. You should pressed firmly against he back with your feet together. Allow the dumbbells to hang straight down at your side, holding them with a neutral grip. This will be your starting position.",
            "Initiate the movement by flexing at the elbow, attempting to keep the upper arm stationary.",
            "Continue to the top of the movement and pause, then slowly return to the start position.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": [
            "Brachialis",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
]
