"""Biceps entries for the global exercise database."""

BICEPS_EXERCISES = [
    {
        "name": "Straight Bar Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "EZ-Bar Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Strict Wall-Supported Barbell Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Reverse Barbell Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Brachialis",
        "secondary_muscles": ["Biceps", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Reverse EZ-Bar Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Brachialis",
        "secondary_muscles": ["Biceps", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Standing Dumbbell Curls",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Sitting Dumbbell Curls",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Dumbbell Curls",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Hammer Curls",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Brachialis",
        "secondary_muscles": ["Biceps", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cross-Body Dumbbell Hammer Curls",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Brachialis",
        "secondary_muscles": ["Biceps", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Concentration Curls",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Bench Supported Dumbbell Curls",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Spider Curls",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Straight Bar Spider Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "EZ-Bar Spider Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Straight Preacher Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "EZ-Bar Preacher Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Preacher Curls",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Hammer Preacher Curls",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Brachialis",
        "secondary_muscles": ["Biceps", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Preacher Curls Machine (Plate Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Preacher Curls Machine (Pin Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Straight Bar Cable Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "D-Handle Cable Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Rope Cable Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Brachialis",
        "secondary_muscles": ["Biceps", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single Hand Cable Hammer Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Brachialis",
        "secondary_muscles": ["Biceps", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Bayesian Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Reverse Cable Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Brachialis",
        "secondary_muscles": ["Biceps", "Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "High Pulley Cable Curls (Crucifix Curls)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Curls Machine",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis"],
        "tracking_fields": ["weight", "reps", "rir"],
    }
]