"""Cardio entries for the global exercise database."""

CARDIO_EXERCISES = [
    {
        "name": "Treadmill",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jogging_Treadmill/0.jpg",
        "instructions": [
            "To begin, step onto the treadmill and select the desired option from the menu. Most treadmills have a manual setting, or you can select a program to run. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. Elevation can be adjusted to change the intensity of the workout.",
            "Treadmills offer convenience, cardiovascular benefits, and usually have less impact than jogging outside. A 150 lb person will burn almost 250 calories jogging for 30 minutes, compared to more than 450 calories running. Maintain proper posture as you jog, and only hold onto the handles when necessary, such as when dismounting or checking your heart rate.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Calves",
            "Hamstrings",
            "Quads",
        ],
        "tracking_fields": [
            "distance",
            "time",
            "incline",
            "speed",
        ],
    },
    {
        "name": "Air Treadmill / Curved Treadmill",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jogging_Treadmill/0.jpg",
        "instructions": [
            "To begin, step onto the treadmill and select the desired option from the menu. Most treadmills have a manual setting, or you can select a program to run. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. Elevation can be adjusted to change the intensity of the workout.",
            "Treadmills offer convenience, cardiovascular benefits, and usually have less impact than jogging outside. A 150 lb person will burn almost 250 calories jogging for 30 minutes, compared to more than 450 calories running. Maintain proper posture as you jog, and only hold onto the handles when necessary, such as when dismounting or checking your heart rate.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Glutes",
            "Hamstrings",
            "Calves",
        ],
        "tracking_fields": [
            "distance",
            "time",
            "incline",
            "speed",
        ],
    },
    {
        "name": "Stationary Bike",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycling_Stationary/0.jpg",
        "instructions": [
            "To begin, seat yourself on the bike and adjust the seat to your height.",
            "Select the desired option from the menu. You may have to start pedaling to turn it on. You can use the manual setting, or you can select a program to use. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. The level of resistance can be changed throughout the workout. The handles can be used to monitor your heart rate to help you stay at an appropriate intensity.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Quads",
            "Calves",
        ],
        "tracking_fields": [
            "time",
            "distance",
            "difficulty",
        ],
    },
    {
        "name": "Air Bike (Assault / Echo Bike)",
        "type": "cardio",
        "instructions": [
            "Adjust the seat height so that your leg has a slight bend at the bottom of the pedal stroke.",
            "Sit on the bike, place your feet on the pedals, and grip the moving handles.",
            "Push and pull the handles with your arms while simultaneously pedaling with your legs.",
            "Keep your chest up and core engaged, maintaining a steady, coordinated rhythm."
        ],
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Anterior Delt",
            "Quads",
        ],
        "tracking_fields": [
            "time",
            "distance",
            "difficulty",
        ],
    },
    {
        "name": "Elliptical",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elliptical_Trainer/0.jpg",
        "instructions": [
            "To begin, step onto the elliptical and select the desired option from the menu. Most ellipticals have a manual setting, or you can select a program to run. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. Elevation can be adjusted to change the intensity of the workout.",
            "The handles can be used to monitor your heart rate to help you stay at an appropriate intensity.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Anterior Delt",
            "Glutes",
            "Lats",
            "Quads",
        ],
        "tracking_fields": [
            "time",
            "distance",
            "difficulty",
        ],
    },
    {
        "name": "Stair Master / Step Machine",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Step_Mill/0.jpg",
        "instructions": [
            "To begin, step onto the stepmill and select the desired option from the menu. You can choose a manual setting, or you can select a program to run. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. Use caution so that you don't trip as you climb the stairs. It is recommended that you maintain your grip on the handles so that you don't fall.",
            "Stepmills offer convenience, cardiovascular benefits, and usually have less impact than running outside while offering a similar rate of calories burned. They are typically much harder than other cardio equipment. A 150 lb person will typically burn over 300 calories in 30 minutes, compared to about 175 calories walking.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Glutes",
            "Quads",
            "Calves",
        ],
        "tracking_fields": [
            "time",
            "distance",
            "difficulty",
        ],
    },
    {
        "name": "Rowing Machine (Ergometer)",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rowing_Stationary/0.jpg",
        "instructions": [
            "To begin, seat yourself on the rower. Make sure that your heels are resting comfortably against the base of the foot pedals and that the straps are secured. Select the program that you wish to use, if applicable. Sit up straight and bend forward at the hips.",
            "There are three phases of movement when using a rower. The first phase is when you come forward on the rower. Your knees are bent and against your chest. Your upper body is leaning slightly forward while still maintaining good posture. Next, push against the foot pedals and extend your legs while bringing your hands to your upper abdominal area, squeezing your shoulders back as you do so. To avoid straining your back, use primarily your leg and hip muscles.",
            "The recovery phase simply involves straightening your arms, bending the knees, and bringing your body forward again as you transition back into the first phase.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Hamstrings",
            "Glutes",
            "Lats",
            "Quads",
        ],
        "tracking_fields": [
            "distance",
            "time",
        ],
    },
    {
        "name": "SkiErg",
        "type": "cardio",
        "instructions": [
            "Stand facing the SkiErg machine with your feet shoulder-width apart and grip a handle in each hand, arms extended overhead.",
            "Hinge slightly at the hips and brace your core. This is your starting position.",
            "Pull both handles down and back by driving through your lats and core, bending at the hips as you pull, similar to a double-pole skiing motion.",
            "Let the handles return back up overhead as you reset, controlling the recoil rather than letting it snap back.",
            "Repeat continuously for the target duration or distance, settling into a steady rhythm.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Abs",
            "Glutes",
            "Lats",
        ],
        "tracking_fields": [
            "distance",
            "time",
        ],
    },
    {
        "name": "VersaClimber",
        "type": "cardio",
        "instructions": [
            "Step onto the VersaClimber footplates and grip the handles, standing tall with a slight bend in your knees and elbows.",
            "Brace your core to keep your torso stable. This is your starting position.",
            "Drive one arm down while pulling the opposite foot up, alternating sides in a climbing motion, keeping your movements smooth and continuous.",
            "Maintain an upright posture throughout rather than leaning heavily on the handles.",
            "Continue the alternating climbing motion for the target duration, adjusting the resistance and pace as needed.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Anterior Delt",
            "Glutes",
            "Lats",
            "Quads",
        ],
        "tracking_fields": [
            "time",
            "distance",
            "difficulty",
        ],
    },
    {
        "name": "Walking",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Walking_Treadmill/0.jpg",
        "instructions": [
            "To begin, step onto the treadmill and select the desired option from the menu. Most treadmills have a manual setting, or you can select a program to run. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. Elevation can be adjusted to change the intensity of the workout.",
            "Treadmills offer convenience, cardiovascular benefits, and usually have less impact than walking outside. When walking, you should move at a moderate to fast pace, not a leisurely one. Being an activity of lower intensity, walking doesn't burn as many calories as some other activities, but still provides great benefit. A 150 lb person will burn about 175 calories walking 4 miles per hour for 30 minutes, compared to 450 calories running twice as fast. Maintain proper posture as you walk, and only hold onto the handles when necessary, such as when dismounting or checking your heart rate.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Calves",
            "Hamstrings",
        ],
        "tracking_fields": [
            "distance",
            "time",
        ],
    },
    {
        "name": "Running",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Running_Treadmill/0.jpg",
        "instructions": [
            "To begin, step onto the treadmill and select the desired option from the menu. Most treadmills have a manual setting, or you can select a program to run. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. Elevation can be adjusted to change the intensity of the workout.",
            "Treadmills offer convenience, cardiovascular benefits, and usually have less impact than running outside. A 150 lb person will burn over 450 calories running 8 miles per hour for 30 minutes. Maintain proper posture as you run, and only hold onto the handles when necessary, such as when dismounting or checking your heart rate.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Hamstrings",
            "Quads",
            "Calves",
        ],
        "tracking_fields": [
            "distance",
            "time",
        ],
    },
    {
        "name": "Jogging",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jogging_Treadmill/0.jpg",
        "instructions": [
            "To begin, step onto the treadmill and select the desired option from the menu. Most treadmills have a manual setting, or you can select a program to run. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. Elevation can be adjusted to change the intensity of the workout.",
            "Treadmills offer convenience, cardiovascular benefits, and usually have less impact than jogging outside. A 150 lb person will burn almost 250 calories jogging for 30 minutes, compared to more than 450 calories running. Maintain proper posture as you jog, and only hold onto the handles when necessary, such as when dismounting or checking your heart rate.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Hamstrings",
            "Quads",
            "Calves",
        ],
        "tracking_fields": [
            "distance",
            "time",
        ],
    },
    {
        "name": "Hiking",
        "type": "cardio",
        "instructions": [
            "Choose a trail suited to your fitness level and wear supportive footwear, carrying a light pack if desired.",
            "Start at an easy, sustainable pace to warm up, keeping your posture upright and your steps controlled on uneven ground.",
            "Settle into a steady rhythm, using your arms for balance and shortening your stride on steeper inclines.",
            "Stay hydrated and take breaks as needed, especially on longer or hillier routes.",
            "Continue for the target duration or distance, paying extra attention to footing on descents.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Abs",
            "Glutes",
            "Quads",
            "Calves",
        ],
        "tracking_fields": [
            "distance",
            "time",
        ],
    },
    {
        "name": "Cycling (Outdoor)",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycling/0.jpg",
        "instructions": [
            "To begin, seat yourself on the bike and adjust the seat to your height.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Glutes",
            "Quads",
            "Calves",
        ],
        "tracking_fields": [
            "distance",
            "time",
        ],
    },
    {
        "name": "Skiing (Cross-Country)",
        "type": "cardio",
        "instructions": [
            "Fit into cross-country skis and poles, and begin on flat, groomed terrain if you're new to the movement.",
            "Push off with one ski while gliding on the other, swinging the opposite arm and pole forward in a rhythmic, alternating pattern. This is your starting motion.",
            "Plant each pole slightly behind you and push through it to add propulsion as you glide.",
            "Keep your knees soft and your weight shifting smoothly from ski to ski as you find your rhythm.",
            "Continue the alternating glide for the target duration or distance, increasing pace or tackling hills as your technique improves.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Glutes",
            "Lats",
            "Quads",
        ],
        "tracking_fields": [
            "distance",
            "time",
        ],
    },
    {
        "name": "Swimming",
        "type": "cardio",
        "instructions": [
            "Enter the pool and choose a stroke suited to your ability, such as freestyle, breaststroke, or backstroke.",
            "Push off from the wall in a streamlined position with your arms extended and body flat near the surface. This is your starting position.",
            "Begin your stroke cycle, coordinating your arm pulls, kick, and breathing rhythm for your chosen stroke.",
            "Keep your body as horizontal as possible to minimize drag, and exhale steadily underwater between breaths.",
            "Continue swimming laps for the target duration or distance, resting at the wall between sets as needed.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Anterior Delt",
            "Abs",
            "Lats",
        ],
        "tracking_fields": [
            "distance",
            "time",
        ],
    },
    {
        "name": "Jump Rope / Skipping",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rope_Jumping/0.jpg",
        "instructions": [
            "Hold an end of the rope in each hand and position the rope behind you on the ground.",
            "Raise your arms up and turn the rope over your head, bringing it down in front of you. This is your starting position.",
            "When the rope reaches the ground, jump over it, finding a turning pace you can maintain comfortably.",
            "Keep your jumps small and land softly on the balls of your feet, using your wrists rather than your whole arms to turn the rope.",
            "Continue for the target duration, varying speed and footwork for variety.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Anterior Delt",
            "Calves",
        ],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "Battle Ropes",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Battling_Ropes/0.jpg",
        "instructions": [
            "For this exercise you will need a heavy rope anchored at its center 15-20 feet away. Standing in front of the rope, take an end in each hand with your arms extended at your side. This will be your starting position.",
            "Initiate the movement by rapidly raising one arm to shoulder level as quickly as you can.",
            "As you let that arm drop to the starting position, raise the opposite side.",
            "Continue alternating your left and right arms, whipping the ropes up and down as fast as you can.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Anterior Delt",
            "Abs",
            "Lats",
        ],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "Heavy Bag / Boxing",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Heavy_Bag_Thrust/0.jpg",
        "instructions": [
            "Utilize a heavy bag for this exercise. Assume an upright stance next to the bag, with your feet staggered, fairly wide apart. Place your hand on the bag at about chest height. This will be your starting position.",
            "Begin by twisting at the waist, pushing the bag forward as hard as possible. Perform this move quickly, pushing the bag away from your body.",
            "Receive the bag as it swings back by reversing these steps.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Anterior Delt",
            "Abs",
            "Calves",
        ],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "Sled Push / Prowler",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sled_Push/0.jpg",
        "instructions": [
            "Load your pushing sled with the desired weight.",
            "Take an athletic posture, leaning into the sled with your arms fully extended, grasping the handles. Push the sled as fast as possible, focusing on extending your hips and knees to strengthen your posterior chain.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Abs",
            "Glutes",
            "Quads",
            "Calves",
        ],
        "tracking_fields": [
            "weight",
            "distance",
            "time",
        ],
    },
    {
        "name": "Burpees",
        "type": "cardio",
        "instructions": [
            "Stand with your feet shoulder-width apart, arms at your sides. This is your starting position.",
            "Drop into a squat and place your hands on the floor in front of you.",
            "Kick your feet straight back into a push-up position, then perform a push-up if desired.",
            "Jump your feet back up to your hands, then explosively jump straight up, reaching your arms overhead. Exhale as you jump.",
            "Land softly with your knees slightly bent and immediately drop back into the next rep.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Chest",
            "Abs",
            "Quads",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "Mountain Climbers",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climbers/0.jpg",
        "instructions": [
            "Begin in a pushup position, with your weight supported by your hands and toes. Flexing the knee and hip, bring one leg until the knee is approximately under the hip. This will be your starting position.",
            "Explosively reverse the positions of your legs, extending the bent leg until the leg is straight and supported by the toe, and bringing the other foot up with the hip and knee flexed. Repeat in an alternating fashion for 20-30 seconds.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Abs",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "Jumping Jacks",
        "type": "cardio",
        "instructions": [
            "Stand upright with your feet together and your arms at your sides. This is your starting position.",
            "Jump your feet out wide while simultaneously raising your arms overhead, landing softly on the balls of your feet.",
            "Immediately reverse the motion, jumping your feet back together while lowering your arms back to your sides.",
            "Keep the movement continuous and rhythmic, using your calves and ankles to absorb each landing.",
            "Repeat for the target duration.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Anterior Delt",
            "Calves",
        ],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "High Knees",
        "type": "cardio",
        "instructions": [
            "Stand tall with your feet hip-width apart, arms bent at your sides as if jogging. This is your starting position.",
            "Drive one knee up toward your chest as high as you can while quickly pushing off the ground with the opposite foot.",
            "Immediately switch legs, driving the other knee up as the first foot returns to the ground, pumping your arms in rhythm.",
            "Keep your torso upright and land on the balls of your feet with each step.",
            "Continue alternating at a quick pace for the target duration.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Abs",
            "Calves",
        ],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "Box Jumps",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Box_Jump/0.jpg",
        "instructions": [
            "Begin with a box of an appropriate height 1-2 feet in front of you. Stand with your feet should width apart. This will be your starting position.",
            "Perform a short squat in preparation for jumping, swinging your arms behind you.",
            "Rebound out of this position, extending through the hips, knees, and ankles to jump as high as possible. Swing your arms forward and up.",
            "Land on the box with the knees bent, absorbing the impact through the legs. You can jump from the box back to the ground, or preferably step down one leg at a time.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Quads",
        "secondary_muscles": [
            "Glutes",
            "Hamstrings",
            "Calves",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Kettlebell Swings",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Swings/0.jpg",
        "instructions": [
            "Stand with your feet shoulder-width apart, a kettlebell on the floor a short distance in front of you. Hinge at the hips and grip the handle with both hands.",
            "Hike the kettlebell back between your legs like a football snap, keeping your back flat. This will be your starting position.",
            "Drive your hips forward explosively to swing the kettlebell up to chest height, keeping your arms relaxed and letting the hip drive do the work. Exhale as you swing up.",
            "Let the kettlebell swing back down between your legs as you hinge at the hips again, inhaling as it descends, and immediately flow into the next rep.",
            "Repeat for the recommended amount of repetitions, keeping your core braced and your lower back neutral throughout.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Glutes",
        "secondary_muscles": [
            "Hamstrings",
            "Abs",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Bear Crawls",
        "type": "cardio",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bear_Crawl_Sled_Drags/0.jpg",
        "instructions": [
            "Wearing either a harness or a loose weight belt, attach the chain to the back so that you will be facing away from the sled. Bend down so that your hands are on the ground. Your back should be flat and knees bent. This is your starting position.",
            "Begin by driving with legs, alternating left and right. Use your hands to maintain balance and to help pull. Try to keep your back flat as you move over a given distance.",
        ],
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": [
            "Abs",
            "Quads",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "time",
        ],
    },
]
