"""Cardio entries for the global exercise database."""

CARDIO_EXERCISES = [
    {
        "name": "Treadmill",
        "type": "cardio",
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Calves", "Hamstrings", "Quads"],
        "tracking_fields": ["distance", "time", "incline", "speed"],
    },
    {
        "name": "Air Treadmill / Curved Treadmill",
        "type": "cardio",
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Glutes", "Hamstrings", "Calves"],
        "tracking_fields": ["distance", "time", "incline", "speed"],
    },
    {
        "name": "Stationary Bike",
        "type": "cardio",
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Quads", "Calves"],
        "tracking_fields": ["time", "distance", "difficulty"],
    },
    {
        "name": "Air Bike (Assault / Echo Bike)",
        "type": "cardio",
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Anterior Delt", "Quads"],
        "tracking_fields": ["time", "distance", "difficulty"],
    },
    {
        "name": "Elliptical",
        "type": "cardio",
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Anterior Delt", "Glutes", "Lats", "Quads"],
        "tracking_fields": ["time", "distance", "difficulty"],
    },
    {
        "name": "Stair Master / Step Machine",
        "type": "cardio",
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Glutes", "Quads", "Calves"],
        "tracking_fields": ["time", "distance", "difficulty"],
    },
    {
        "name": "Rowing Machine (Ergometer)",
        "type": "cardio",
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Hamstrings", "Glutes", "Lats", "Quads"],
        "tracking_fields": ["distance", "time"],
    },
    {
        "name": "SkiErg",
        "type": "cardio",
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Abs", "Glutes", "Lats"],
        "tracking_fields": ["distance", "time"],
    },
    {
        "name": "VersaClimber",
        "type": "cardio",
        "equipment": "Machine",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Anterior Delt", "Glutes", "Lats", "Quads"],
        "tracking_fields": ["time", "distance", "difficulty"],
    },
    {
        "name": "Walking",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Calves", "Hamstrings"],
        "tracking_fields": ["distance", "time"],
    },
    {
        "name": "Running",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Hamstrings", "Quads", "Calves"],
        "tracking_fields": ["distance", "time"],
    },
    {
        "name": "Jogging",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Hamstrings", "Quads", "Calves"],
        "tracking_fields": ["distance", "time"],
    },
    {
        "name": "Hiking",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Abs", "Glutes", "Quads", "Calves"],
        "tracking_fields": ["distance", "time"],
    },
    {
        "name": "Cycling (Outdoor)",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Glutes", "Quads", "Calves"],
        "tracking_fields": ["distance", "time"],
    },
    {
        "name": "Skiing (Cross-Country)",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Glutes", "Lats", "Quads"],
        "tracking_fields": ["distance", "time"],
    },
    {
        "name": "Swimming",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Anterior Delt", "Abs", "Lats"],
        "tracking_fields": ["distance", "time"],
    },
    {
        "name": "Jump Rope / Skipping",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Anterior Delt", "Calves"],
        "tracking_fields": ["time"],
    },
    {
        "name": "Battle Ropes",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Anterior Delt", "Abs", "Lats"],
        "tracking_fields": ["time"],
    },
    {
        "name": "Heavy Bag / Boxing",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Anterior Delt", "Abs", "Calves"],
        "tracking_fields": ["time"],
    },
    {
        "name": "Sled Push / Prowler",
        "type": "cardio",
        "equipment": "Plate",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Abs", "Glutes", "Quads", "Calves"],
        "tracking_fields": ["weight", "distance", "time"],
    },
    {
        "name": "Burpees",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Chest", "Abs", "Quads", "Anterior Delt"],
        "tracking_fields": ["time"],
    },
    {
        "name": "Mountain Climbers",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Abs", "Anterior Delt"],
        "tracking_fields": ["time"],
    },
    {
        "name": "Jumping Jacks",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Anterior Delt", "Calves"],
        "tracking_fields": ["time"],
    },
    {
        "name": "High Knees",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Abs", "Calves"],
        "tracking_fields": ["time"],
    },
    {
        "name": "Box Jumps",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes", "Hamstrings", "Calves"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Kettlebell Swings",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Hamstrings", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Bear Crawls",
        "type": "cardio",
        "equipment": "None",
        "primary_muscle": "Cardio",
        "secondary_muscles": ["Abs", "Quads", "Anterior Delt"],
        "tracking_fields": ["time"],
    }
]