"""Chest entries for the global exercise database."""

CHEST_EXERCISES = [
    {
        "name": "Flat Barbell Bench Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg",
        "instructions": [
            "Lie back on a flat bench. Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
            "From the starting position, breathe in and begin coming down slowly until the bar touches your middle chest.",
            "After a brief pause, push the bar back to the starting position as you breathe out. Focus on pushing the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position at the top of the motion, hold for a second and then start coming down slowly again. Tip: Ideally, lowering the weight should take about twice as long as raising it.",
            "Repeat the movement for the prescribed amount of repetitions.",
            "When you are done, place the bar back in the rack.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Incline Barbell Bench Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg",
        "instructions": [
            "Lie back on an incline bench. Using a medium-width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
            "As you breathe in, come down slowly until you feel the bar on you upper chest.",
            "After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms in the contracted position, squeeze your chest, hold for a second and then start coming down slowly again. Tip: it should take at least twice as long to go down than to come up.",
            "Repeat the movement for the prescribed amount of repetitions.",
            "When you are done, place the bar back in the rack.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Decline Barbell Bench Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Barbell_Bench_Press/0.jpg",
        "instructions": [
            "Secure your legs at the end of the decline bench and slowly lay down on the bench.",
            "Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. The arms should be perpendicular to the floor. This will be your starting position. Tip: In order to protect your rotator cuff, it is best if you have a spotter help you lift the barbell off the rack.",
            "As you breathe in, come down slowly until you feel the bar on your lower chest.",
            "After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up).",
            "Repeat the movement for the prescribed amount of repetitions.",
            "When you are done, place the bar back in the rack.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Barbell Floor Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Floor_Press/0.jpg",
        "instructions": [
            "Adjust the j-hooks so they are at the appropriate height to rack the bar. Begin lying on the floor with your head near the end of a power rack. Keeping your shoulder blades pulled together; pull the bar off of the hooks.",
            "Lower the bar towards the bottom of your chest or upper stomach, squeezing the bar and attempting to pull it apart as you do so. Ensure that you tuck your elbows throughout the movement. Lower the bar until your upper arm contacts the ground and pause, preventing any slamming or bouncing of the weight.",
            "Press the bar back up as fast as you can, keeping the bar, your wrists, and elbows in line as you do so.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Barbell Guillotine Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Guillotine_Bench_Press/0.jpg",
        "instructions": [
            "Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over your neck with your arms locked. This will be your starting position.",
            "As you breathe in, bring the bar down slowly until it is about 1 inch from your neck.",
            "After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position, hold for a second and then start coming down slowly again. It should take at least twice as long to go down than to come up.",
            "Repeat the movement for the prescribed amount of repetitions.",
            "When you are done, place the bar back in the rack.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Flat Dumbbell Bench Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg",
        "instructions": [
            "Lie down on a flat bench with a dumbbell in each hand resting on top of your thighs. The palms of your hands will be facing each other.",
            "Then, using your thighs to help raise the dumbbells up, lift the dumbbells one at a time so that you can hold them in front of you at shoulder width.",
            "Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. The dumbbells should be just to the sides of your chest, with your upper arm and forearm creating a 90 degree angle. Be sure to maintain full control of the dumbbells at all times. This will be your starting position.",
            "Then, as you breathe out, use your chest to push the dumbbells up. Lock your arms at the top of the lift and squeeze your chest, hold for a second and then begin coming down slowly. Tip: Ideally, lowering the weight should take about twice as long as raising it.",
            "Repeat the movement for the prescribed amount of repetitions of your training program.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Incline Dumbbell Bench Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg",
        "instructions": [
            "Lie back on an incline bench with a dumbbell in each hand atop your thighs. The palms of your hands will be facing each other.",
            "Then, using your thighs to help push the dumbbells up, lift the dumbbells one at a time so that you can hold them at shoulder width.",
            "Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.",
            "Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest.",
            "Lock your arms at the top, hold for a second, and then start slowly lowering the weight. Tip Ideally, lowering the weights should take about twice as long as raising them.",
            "Repeat the movement for the prescribed amount of repetitions.",
            "When you are done, place the dumbbells back on your thighs and then on the floor. This is the safest manner to release the dumbbells.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Decline Dumbbell Bench Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Bench_Press/0.jpg",
        "instructions": [
            "Secure your legs at the end of the decline bench and lie down with a dumbbell on each hand on top of your thighs. The palms of your hand will be facing each other.",
            "Once you are laying down, move the dumbbells in front of you at shoulder width.",
            "Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.",
            "Bring down the weights slowly to your side as you breathe out. Keep full control of the dumbbells at all times. Tip: Throughout the motion, the forearms should always be perpendicular to the floor.",
            "As you breathe out, push the dumbbells up using your pectoral muscles. Lock your arms in the contracted position, squeeze your chest, hold for a second and then start coming down slowly. Tip: It should take at least twice as long to go down than to come up..",
            "Repeat the movement for the prescribed amount of repetitions of your training program.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Flat Dumbbell Hex / Squeeze Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Floor_Press/0.jpg",
        "instructions": [
            "Lay on the floor holding dumbbells in your hands. Your knees can be bent. Begin with the weights fully extended above you.",
            "Lower the weights until your upper arm comes in contact with the floor. You can tuck your elbows to emphasize triceps size and strength, or to focus on your chest angle your arms to the side.",
            "Pause at the bottom, and then bring the weight together at the top by extending through the elbows.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Incline Dumbbell Hex / Squeeze Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg",
        "instructions": [
            "Lie back on an incline bench with a dumbbell in each hand atop your thighs. The palms of your hands will be facing each other.",
            "Then, using your thighs to help push the dumbbells up, lift the dumbbells one at a time so that you can hold them at shoulder width.",
            "Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.",
            "Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest.",
            "Lock your arms at the top, hold for a second, and then start slowly lowering the weight. Tip Ideally, lowering the weights should take about twice as long as raising them.",
            "Repeat the movement for the prescribed amount of repetitions.",
            "When you are done, place the dumbbells back on your thighs and then on the floor. This is the safest manner to release the dumbbells.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Decline Dumbbell Hex / Squeeze Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Bench_Press/0.jpg",
        "instructions": [
            "Secure your legs at the end of the decline bench and lie down with a dumbbell on each hand on top of your thighs. The palms of your hand will be facing each other.",
            "Once you are laying down, move the dumbbells in front of you at shoulder width.",
            "Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.",
            "Bring down the weights slowly to your side as you breathe out. Keep full control of the dumbbells at all times. Tip: Throughout the motion, the forearms should always be perpendicular to the floor.",
            "As you breathe out, push the dumbbells up using your pectoral muscles. Lock your arms in the contracted position, squeeze your chest, hold for a second and then start coming down slowly. Tip: It should take at least twice as long to go down than to come up..",
            "Repeat the movement for the prescribed amount of repetitions of your training program.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Flat Dumbbell Fly",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Flat_Bench_Dumbbell_Flye/0.jpg",
        "instructions": [
            "Lie down on a flat bench with a dumbbell in one hand resting on top of your thigh. The palm of your hand with the dumbbell in it should be at a neutral grip.",
            "By using your thighs to help you get the dumbbell up, clean the dumbbell so that you can hold it in front of you with your lifting arm being fully extended. Remember to maintain a neutral grip with this exercise. Your non lifting hand should be to the side holding the flat bench for better support. This will be your starting position.",
            "Your arm with the weight should have a slight bend on your elbow in order to prevent stress at the biceps tendon. Begin by lowering your arm with the weight in it out in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, your lifting arm should remain stationary; the movement should only occur at the shoulder joint.",
            "Return your lifting arm back to the starting position as you squeeze your chest muscles and breathe out. Tip: Make sure to use the same arc of motion used to lower the weights.",
            "Hold for a second at the contracted position and repeat the movement for the prescribed amount of repetitions.",
            "Switch arms and repeat the exercise.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Incline Dumbbell Fly",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Flyes/0.jpg",
        "instructions": [
            "Hold a dumbbell on each hand and lie on an incline bench that is set to an incline angle of no more than 30 degrees.",
            "Extend your arms above you with a slight bend at the elbows.",
            "Now rotate the wrists so that the palms of your hands are facing you. Tip: The pinky fingers should be next to each other. This will be your starting position.",
            "As you breathe in, start to slowly lower the arms to the side while keeping the arms extended and while rotating the wrists until the palms of the hand are facing each other. Tip: At the end of the movement the arms will be by your side with the palms facing the ceiling.",
            "As you exhale start to bring the dumbbells back up to the starting position by reversing the motion and rotating the hands so that the pinky fingers are next to each other again. Tip: Keep in mind that the movement will only happen at the shoulder joint and at the wrist. There is no motion that happens at the elbow joint.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Decline Dumbbell Fly",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Flyes/0.jpg",
        "instructions": [
            "Secure your legs at the end of the decline bench and lie down with a dumbbell on each hand on top of your thighs. The palms of your hand will be facing each other.",
            "Once you are laying down, move the dumbbells in front of you at shoulder width. The palms of the hands should be facing each other and the arms should be perpendicular to the floor and fully extended. This will be your starting position.",
            "With a slight bend on your elbows in order to prevent stress at the biceps tendon, lower your arms out at both sides in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms should remain stationary; the movement should only occur at the shoulder joint.",
            "Return your arms back to the starting position as you squeeze your chest muscles and breathe out. Tip: Make sure to use the same arc of motion used to lower the weights.",
            "Hold for a second at the contracted position and repeat the movement for the prescribed amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Floor Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Floor_Press/0.jpg",
        "instructions": [
            "Lay on the floor holding dumbbells in your hands. Your knees can be bent. Begin with the weights fully extended above you.",
            "Lower the weights until your upper arm comes in contact with the floor. You can tuck your elbows to emphasize triceps size and strength, or to focus on your chest angle your arms to the side.",
            "Pause at the bottom, and then bring the weight together at the top by extending through the elbows.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Pullover (Chest-Focused)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent-Arm_Dumbbell_Pullover/0.jpg",
        "instructions": [
            "Place a dumbbell standing up on a flat bench.",
            "Ensuring that the dumbbell stays securely placed at the top of the bench, lie perpendicular to the bench (torso across it as in forming a cross) with only your shoulders lying on the surface. Hips should be below the bench and legs bent with feet firmly on the floor. The head will be off the bench as well.",
            "Grasp the dumbbell with both hands and hold it straight over your chest with a bend in your arms. Both palms should be pressing against the underside one of the sides of the dumbbell. This will be your starting position. Caution: Always ensure that the dumbbell used for this exercise is secure. Using a dumbbell with loose plates can result in the dumbbell falling apart and falling on your face.",
            "While keeping your arms locked in the bent arm position, lower the weight slowly in an arc behind your head while breathing in until you feel a stretch on the chest.",
            "At that point, bring the dumbbell back to the starting position using the arc through which the weight was lowered and exhale as you perform this movement.",
            "Hold the weight on the initial position for a second and repeat the motion for the prescribed number of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Flat Machine Chest Press (Plate-Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Chest_Press/0.jpg",
        "instructions": [
            "Load an appropriate weight onto the pins and adjust the seat for your height. The handles should be near the bottom or middle of the pectorals at the beginning of the motion.",
            "Your chest and head should be up and your shoulder blades retracted. This will be your starting position.",
            "Press the handles forward by extending through the elbow.",
            "After a brief pause at the top, return the weight just above the start position, keeping tension on the muscles by not returning the weight to the stops until the set is complete.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Flat Machine Chest Press (Pin-Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Chest_Press/0.jpg",
        "instructions": [
            "Load an appropriate weight onto the pins and adjust the seat for your height. The handles should be near the bottom or middle of the pectorals at the beginning of the motion.",
            "Your chest and head should be up and your shoulder blades retracted. This will be your starting position.",
            "Press the handles forward by extending through the elbow.",
            "After a brief pause at the top, return the weight just above the start position, keeping tension on the muscles by not returning the weight to the stops until the set is complete.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Incline Machine Chest Press (Plate-Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Incline_Chest_Press/0.jpg",
        "instructions": [
            "Load an appropriate weight onto the pins and adjust the seat for your height. The handles should be near the top of the pectorals at the beginning of the motion. Your chest and head should be up and your shoulder blades retracted. This will be your starting position.",
            "Press the handles forward by extending through the elbow.",
            "After a brief pause at the top, return the weight just above the start position, keeping tension on the muscles by not returning the weight to the stops until the set is complete.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Incline Machine Chest Press (Pin-Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Incline_Chest_Press/0.jpg",
        "instructions": [
            "Load an appropriate weight onto the pins and adjust the seat for your height. The handles should be near the top of the pectorals at the beginning of the motion. Your chest and head should be up and your shoulder blades retracted. This will be your starting position.",
            "Press the handles forward by extending through the elbow.",
            "After a brief pause at the top, return the weight just above the start position, keeping tension on the muscles by not returning the weight to the stops until the set is complete.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Decline Machine Chest Press (Plate-Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Decline_Chest_Press/0.jpg",
        "instructions": [
            "Load an appropriate weight onto the pins and adjust the seat for your height. The handles should be near the bottom of the pectorals at the beginning of the motion. Your chest and head should be up and your shoulder blades retracted. This will be your starting position.",
            "Press the handles forward by extending through the elbow.",
            "After a brief pause at the top, return the weight just above the start position, keeping tension on the muscles by not returning the weight to the stops until the set is complete.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Decline Machine Chest Press (Pin-Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Decline_Chest_Press/0.jpg",
        "instructions": [
            "Load an appropriate weight onto the pins and adjust the seat for your height. The handles should be near the bottom of the pectorals at the beginning of the motion. Your chest and head should be up and your shoulder blades retracted. This will be your starting position.",
            "Press the handles forward by extending through the elbow.",
            "After a brief pause at the top, return the weight just above the start position, keeping tension on the muscles by not returning the weight to the stops until the set is complete.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Smith Machine Flat Press",
        "type": "strength",
        "instructions": [
            "Place a flat bench underneath the Smith machine. Adjust the barbell to a height you can reach when lying down with your arms almost fully extended.",
            "Lie down and grasp the bar with a pronated grip slightly wider than shoulder-width.",
            "Unrack the bar and hold it straight over your chest. This is your starting position.",
            "Inhale and slowly lower the bar under control until it lightly touches your mid-chest.",
            "Exhale and press the bar back up to the starting position by extending your elbows.",
            "When the set is complete, lock the bar back into the rack."
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Smith Machine Incline Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Incline_Bench_Press/0.jpg",
        "instructions": [
            "Place an incline bench underneath the smith machine. Place the barbell at a height that you can reach when lying down and your arms are almost fully extended. Once the weight you need is selected, lie down on the incline bench and make sure your upper chest is aligned with the barbell. Using a pronated grip (palms facing forward) that is wider than shoulder width, unlock the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
            "As you breathe in, come down slowly until you feel the bar on your upper chest.",
            "After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.",
            "Repeat the movement for the prescribed amount of repetitions.",
            "When you are done, place the bar back in the rack.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Smith Machine Decline Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Smith_Press/0.jpg",
        "instructions": [
            "Place a decline bench underneath the Smith machine. Now place the barbell at a height that you can reach when lying down and your arms are almost fully extended. Using a pronated grip that is wider than shoulder width, unlock the bar from the rack and hold it straight over you with your arms extended. This will be your starting position.",
            "As you inhale, lower the bar under control by allowing the elbows to flex, lightly contacting the torso.",
            "After a brief pause, bring the bar back to the starting position by extending the elbows, exhaling as you do so.",
            "Repeat the movement for the prescribed amount of repetitions.",
            "When the set is complete, lock the bar back in the rack.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Standing / Seated Cable Chest Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Cable_Chest_Press/0.jpg",
        "instructions": [
            "Position dual pulleys to chest height and select an appropriate weight. Stand a foot or two in front of the cables, holding one in each hand. You can stagger your stance for better stability.",
            "Position the upper arm at a 90 degree angle with the shoulder blades together. This will be your starting position.",
            "Keeping the rest of the body stationary, extend through the elbows to press the handles forward, drawing them together in front of you.",
            "Pause at the top of the motion, and return to the starting position.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Low to High Cable Chest Fly",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg",
        "instructions": [
            "To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand.",
            "Step forward in front of an imaginary straight line between both pulleys while pulling your arms together in front of you. Your torso should have a small forward bend from the waist. This will be your starting position.",
            "With a slight bend on your elbows in order to prevent stress at the biceps tendon, extend your arms to the side (straight out at both sides) in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms and torso should remain stationary; the movement should only occur at the shoulder joint.",
            "Return your arms back to the starting position as you breathe out. Make sure to use the same arc of motion used to lower the weights.",
            "Hold for a second at the starting position and repeat the movement for the prescribed amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Middle Cable Chest Fly",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg",
        "instructions": [
            "To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand.",
            "Step forward in front of an imaginary straight line between both pulleys while pulling your arms together in front of you. Your torso should have a small forward bend from the waist. This will be your starting position.",
            "With a slight bend on your elbows in order to prevent stress at the biceps tendon, extend your arms to the side (straight out at both sides) in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms and torso should remain stationary; the movement should only occur at the shoulder joint.",
            "Return your arms back to the starting position as you breathe out. Make sure to use the same arc of motion used to lower the weights.",
            "Hold for a second at the starting position and repeat the movement for the prescribed amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "High to Low Cable Chest Fly",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg",
        "instructions": [
            "To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand.",
            "Step forward in front of an imaginary straight line between both pulleys while pulling your arms together in front of you. Your torso should have a small forward bend from the waist. This will be your starting position.",
            "With a slight bend on your elbows in order to prevent stress at the biceps tendon, extend your arms to the side (straight out at both sides) in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms and torso should remain stationary; the movement should only occur at the shoulder joint.",
            "Return your arms back to the starting position as you breathe out. Make sure to use the same arc of motion used to lower the weights.",
            "Hold for a second at the starting position and repeat the movement for the prescribed amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Single-Arm Cross-Body Cable Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single-Arm_Cable_Crossover/0.jpg",
        "instructions": [
            "Begin by moving the pulleys to the high position, select the resistance to be used, and take a handle in each hand.",
            "Step forward in front of both pulleys with your arms extended in front of you, bringing your hands together. Your head and chest should be up as you lean forward, while your feet should be staggered. This will be your starting position.",
            "Keeping your left arm in place, allow your right arm to extend out to the side, maintaining a slight bend at the elbow. The right arm should be perpendicular to the body at approximately shoulder level.",
            "Return your arm back to the starting position by pulling your hand back to the midline of the body.",
            "Hold for a second at the starting position and repeat the movement on the opposite side. Continue alternating back and forth for the prescribed number of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Single-Arm Cable Fly",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single-Arm_Cable_Crossover/0.jpg",
        "instructions": [
            "Begin by moving the pulleys to the high position, select the resistance to be used, and take a handle in each hand.",
            "Step forward in front of both pulleys with your arms extended in front of you, bringing your hands together. Your head and chest should be up as you lean forward, while your feet should be staggered. This will be your starting position.",
            "Keeping your left arm in place, allow your right arm to extend out to the side, maintaining a slight bend at the elbow. The right arm should be perpendicular to the body at approximately shoulder level.",
            "Return your arm back to the starting position by pulling your hand back to the midline of the body.",
            "Hold for a second at the starting position and repeat the movement on the opposite side. Continue alternating back and forth for the prescribed number of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Pec Deck Machine (Machine Fly)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butterfly/0.jpg",
        "instructions": [
            "Sit on the machine with your back flat against the pad and adjust the seat height so the handles sit level with your shoulders.",
            "Take hold of the handles with your upper arms parallel to the floor. This will be your starting position.",
            "Push the handles together slowly as you squeeze your chest in the middle. Breathe out during this part of the motion and hold the contraction for a second.",
            "Return to the starting position slowly as you inhale until your chest muscles are fully stretched.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Incline Chest Fly Machine",
        "type": "strength",
        "instructions": [
            "Sit on the incline fly machine and adjust the seat so the handles sit level with your upper chest, arms angled slightly upward.",
            "Grip the handles with a slight bend in your elbows and squeeze your shoulder blades together. This will be your starting position.",
            "Breathe out as you bring the handles together in a wide arc, focusing on squeezing the upper chest at the midpoint.",
            "Hold the contraction for a second, then breathe in as you slowly let the handles return to the starting position.",
            "Repeat for the recommended amount of repetitions, keeping the movement controlled rather than using momentum.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Chest Dips (Parallel Bars)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Parallel_Bar_Dip/0.jpg",
        "instructions": [
            "Stand between a set of parallel bars. Place a hand on each bar, and then take a small jump to help you get into the starting position with your arms locked out.",
            "Begin by flexing the elbow, lowering your body until your arms break 90 degrees. Avoid swinging, and maintain good posture throughout the descent.",
            "Reverse the motion by extending the elbow, pushing yourself back up into the starting position.",
            "Repeat for the desired number of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Weighted Dips (Chest Focus)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Parallel_Bar_Dip/0.jpg",
        "instructions": [
            "Stand between a set of parallel bars. Place a hand on each bar, and then take a small jump to help you get into the starting position with your arms locked out.",
            "Begin by flexing the elbow, lowering your body until your arms break 90 degrees. Avoid swinging, and maintain good posture throughout the descent.",
            "Reverse the motion by extending the elbow, pushing yourself back up into the starting position.",
            "Repeat for the desired number of repetitions.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Assisted Dips Machine",
        "type": "strength",
        "instructions": [
            "Select an assistance weight on the pin stack, kneel or step onto the platform, and grip the handles with your arms extended.",
            "Lean your torso slightly forward and bend your elbows to lower your body until your upper arms are roughly parallel to the floor. Inhale as you descend.",
            "Push back up through your palms until your arms are extended again, exhaling as you press. Keep your elbows tucked to bias the chest and triceps rather than flaring them out.",
            "Repeat for the recommended amount of repetitions, then step off carefully once the platform has stopped moving.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Gymnastic Ring Dips",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ring_Dips/0.jpg",
        "instructions": [
            "Grip a ring in each hand, and then take a small jump to help you get into the starting position with your arms locked out.",
            "Begin by flexing the elbow, lowering your body until your arms break 90 degrees. Avoid swinging, and maintain good posture throughout the descent.",
            "Reverse the motion by extending the elbow, pushing yourself back up into the starting position.",
            "Repeat for the desired number of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
            "Anterior Delt",
            "Abs",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Standard Push-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg",
        "instructions": [
            "Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length.",
            "Next, lower yourself downward until your chest almost touches the floor as you inhale.",
            "Now breathe out and press your upper body back up to the starting position while squeezing your chest.",
            "After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed.",
        ],
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
            "Abs",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Deficit Push-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push-Ups_With_Feet_Elevated/0.jpg",
        "instructions": [
            "Lie on the floor face down and place your hands about 36 inches apart from each other holding your torso up at arms length.",
            "Place your toes on top of a flat bench. This will allow your body to be elevated. Note: The higher the elevation of the flat bench, the higher the resistance of the exercise is.",
            "Lower yourself until your chest almost touches the floor as you inhale.",
            "Using your pectoral muscles, press your upper body back up to the starting position and squeeze your chest. Breathe out as you perform this step.",
            "After a second pause at the contracted position, repeat the movement for the prescribed amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Weighted Push-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg",
        "instructions": [
            "Have a partner place a weight plate or a weighted vest across your upper back, then get into a push-up position with your hands about shoulder-width apart and your body in a straight line from head to heels.",
            "Lower yourself down slowly until your chest almost touches the floor as you inhale, keeping your core braced so the added weight doesn't cause your hips to sag.",
            "Press back up to the starting position as you exhale, squeezing your chest at the top.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
            "Abs",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Incline Push-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Push-Up/0.jpg",
        "instructions": [
            "Stand facing bench or sturdy elevated platform. Place hands on edge of bench or platform, slightly wider than shoulder width.",
            "Position forefoot back from bench or platform with arms and body straight. Arms should be perpendicular to body. Keeping body straight, lower chest to edge of box or platform by bending arms.",
            "Push body up until arms are extended. Repeat.",
        ],
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Triceps",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Decline Push-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Push-Up/0.jpg",
        "instructions": [
            "Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length. Move your feet up to a box or bench. This will be your starting position.",
            "Next, lower yourself downward until your chest almost touches the floor as you inhale.",
            "Now breathe out and press your upper body back up to the starting position while squeezing your chest.",
            "After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed.",
        ],
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Gymnastic Ring Push-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push-Ups_-_Close_Triceps_Position/0.jpg",
        "instructions": [
            "Lie on the floor face down and place your hands closer than shoulder width for a close hand position. Make sure that you are holding your torso up at arms' length.",
            "Lower yourself until your chest almost touches the floor as you inhale.",
            "Using your triceps and some of your pectoral muscles, press your upper body back up to the starting position and squeeze your chest. Breathe out as you perform this step.",
            "After a second pause at the contracted position, repeat the movement for the prescribed amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
            "Abs",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Landmine Chest Press",
        "type": "strength",
        "instructions": [
            "Load one end of a barbell into a landmine attachment (or wedge it securely into a corner) and load the desired weight onto the free end.",
            "Stand facing the landmine, holding the weighted end of the collar with both hands at chest level. Lean slightly forward into the weight. This is your starting position.",
            "Exhale and press the barbell up and away from your chest until your arms are fully extended.",
            "Inhale and slowly lower the barbell back to your chest under control."
        ],
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Svend Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Svend_Press/0.jpg",
        "instructions": [
            "Begin in a standing position.",
            "Press two lightweight plates together with your hands. Hold the plates together close to your chest to create an isometric contraction in your chest muscles. Your fingers should be pointed forward. This is your starting position.",
            "Squeeze the plates between your palms and extend your arms directly out in front of you in a controlled motion.",
            "Pause at the top of the motion, and then slowly return to the starting position.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Paused Barbell Bench Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg",
        "instructions": [
            "Lie back on a flat bench. Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
            "From the starting position, breathe in and begin coming down slowly until the bar touches your middle chest.",
            "After a brief pause, push the bar back to the starting position as you breathe out. Focus on pushing the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position at the top of the motion, hold for a second and then start coming down slowly again. Tip: Ideally, lowering the weight should take about twice as long as raising it.",
            "Repeat the movement for the prescribed amount of repetitions.",
            "When you are done, place the bar back in the rack.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Spoto Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg",
        "instructions": [
            "Lie back on a flat bench. Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
            "From the starting position, breathe in and begin coming down slowly until the bar touches your middle chest.",
            "After a brief pause, push the bar back to the starting position as you breathe out. Focus on pushing the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position at the top of the motion, hold for a second and then start coming down slowly again. Tip: Ideally, lowering the weight should take about twice as long as raising it.",
            "Repeat the movement for the prescribed amount of repetitions.",
            "When you are done, place the bar back in the rack.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": [
            "Anterior Delt",
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
]
