"""Chest entries for the global exercise database."""

CHEST_EXERCISES = [
    {
        "name": "Flat Barbell Bench Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Barbell Bench Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Decline Barbell Bench Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Floor Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Guillotine Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Flat Dumbbell Bench Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Dumbbell Bench Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Decline Dumbbell Bench Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Flat Dumbbell Hex / Squeeze Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Dumbbell Hex / Squeeze Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Decline Dumbbell Hex / Squeeze Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Flat Dumbbell Fly",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Dumbbell Fly",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Decline Dumbbell Fly",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Floor Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Pullover (Chest-Focused)",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Flat Machine Chest Press (Plate-Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Flat Machine Chest Press (Pin-Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Machine Chest Press (Plate-Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Machine Chest Press (Pin-Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Decline Machine Chest Press (Plate-Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Decline Machine Chest Press (Pin-Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine Flat Press",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine Incline Press",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine Decline Press",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Standing / Seated Cable Chest Press",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Low to High Cable Chest Fly",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Middle Cable Chest Fly",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "High to Low Cable Chest Fly",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single-Arm Cross-Body Cable Press",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single-Arm Cable Fly",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Pec Deck Machine (Machine Fly)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Chest Fly Machine",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Chest Dips (Parallel Bars)",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps", "Anterior Delt"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Weighted Dips (Chest Focus)",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Assisted Dips Machine",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Gymnastic Ring Dips",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps", "Anterior Delt", "Abs"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Standard Push-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps", "Abs"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Deficit Push-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Weighted Push-Ups",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Push-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Triceps", "Anterior Delt"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Decline Push-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Gymnastic Ring Push-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps", "Abs"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Landmine Chest Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Svend Press",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Paused Barbell Bench Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Spoto Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Chest",
        "secondary_muscles": ["Anterior Delt", "Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
]
