"""Core entries for the global exercise database."""

CORE_EXERCISES = [
    {
        "name": "Crunches",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunches/0.jpg",
        "instructions": [
            "Lie flat on your back with your feet flat on the ground, or resting on a bench with your knees bent at a 90 degree angle. If you are resting your feet on a bench, place them three to four inches apart and point your toes inward so they touch.",
            "Now place your hands lightly on either side of your head keeping your elbows in. Tip: Don't lock your fingers behind your head.",
            "While pushing the small of your back down in the floor to better isolate your abdominal muscles, begin to roll your shoulders off the floor.",
            "Continue to push down as hard as you can with your lower back as you contract your abdominals and exhale. Your shoulders should come up off the floor only about four inches, and your lower back should remain on the floor. At the top of the movement, contract your abdominals hard and keep the contraction for a second. Tip: Focus on slow, controlled movement - don't cheat yourself by using momentum.",
            "After the one second contraction, begin to come down slowly again to the starting position as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Crunch Machine",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunches/0.jpg",
        "instructions": [
            "Lie flat on your back with your feet flat on the ground, or resting on a bench with your knees bent at a 90 degree angle. If you are resting your feet on a bench, place them three to four inches apart and point your toes inward so they touch.",
            "Now place your hands lightly on either side of your head keeping your elbows in. Tip: Don't lock your fingers behind your head.",
            "While pushing the small of your back down in the floor to better isolate your abdominal muscles, begin to roll your shoulders off the floor.",
            "Continue to push down as hard as you can with your lower back as you contract your abdominals and exhale. Your shoulders should come up off the floor only about four inches, and your lower back should remain on the floor. At the top of the movement, contract your abdominals hard and keep the contraction for a second. Tip: Focus on slow, controlled movement - don't cheat yourself by using momentum.",
            "After the one second contraction, begin to come down slowly again to the starting position as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cable Crunches",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg",
        "instructions": [
            "Kneel below a high pulley that contains a rope attachment.",
            "Grasp cable rope attachment and lower the rope until your hands are placed next to your face.",
            "Flex your hips slightly and allow the weight to hyperextend the lower back. This will be your starting position.",
            "With the hips stationary, flex the waist as you contract the abs so that the elbows travel towards the middle of the thighs. Exhale as you perform this portion of the movement and hold the contraction for a second.",
            "Slowly return to the starting position as you inhale. Tip: Make sure that you keep constant tension on the abs throughout the movement. Also, do not choose a weight so heavy that the lower back handles the brunt of the work.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Decline Crunches",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Crunch/0.jpg",
        "instructions": [
            "Secure your legs at the end of the decline bench and lie down.",
            "Now place your hands lightly on either side of your head keeping your elbows in. Tip: Don't lock your fingers behind your head.",
            "While pushing the small of your back down in the bench to better isolate your abdominal muscles, begin to roll your shoulders off it.",
            "Continue to push down as hard as you can with your lower back as you contract your abdominals and exhale. Your shoulders should come up off the bench only about four inches, and your lower back should remain on the bench. At the top of the movement, contract your abdominals hard and keep the contraction for a second. Tip: Focus on slow, controlled movement - don't cheat yourself by using momentum.",
            "After the one second contraction, begin to come down slowly again to the starting position as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Hanging Leg Raises",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg",
        "instructions": [
            "Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position.",
            "Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so.",
            "Go back slowly to the starting position as you breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Hanging Knee Raises",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg",
        "instructions": [
            "Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position.",
            "Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so.",
            "Go back slowly to the starting position as you breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Captain's Chair Leg Raises",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg",
        "instructions": [
            "Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position.",
            "Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so.",
            "Go back slowly to the starting position as you breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Lying Leg Raises",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flat_Bench_Lying_Leg_Raise/0.jpg",
        "instructions": [
            "Lie with your back flat on a bench and your legs extended in front of you off the end.",
            "Place your hands either under your glutes with your palms down or by the sides holding on to the bench. This will be your starting position.",
            "As you keep your legs extended, straight as possible with your knees slightly bent but locked raise your legs until they make a 90-degree angle with the floor. Exhale as you perform this portion of the movement and hold the contraction at the top for a second.",
            "Now, as you inhale, slowly lower your legs back down to the starting position.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Toes to Bar",
        "type": "strength",
        "instructions": [
            "Hang from a pull-up bar with an overhand, shoulder-width grip and your arms fully extended, legs straight down. This is your starting position.",
            "Brace your core and, using a slight swing if needed, drive your legs upward while keeping them as straight as possible.",
            "Continue raising your legs until your toes touch the bar, exhaling as you lift, keeping your shoulders active and avoiding excessive swinging.",
            "Lower your legs back down under control as you inhale, returning to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Plank",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg",
        "instructions": [
            "Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.",
            "Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "Weighted Plank",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg",
        "instructions": [
            "Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.",
            "Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "weight",
            "time",
        ],
    },
    {
        "name": "Side Plank",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push_Up_to_Side_Plank/0.jpg",
        "instructions": [
            "Get into pushup position on the toes with your hands just outside of shoulder width.",
            "Perform a pushup by allowing the elbows to flex. As you descend, keep your body straight.",
            "Do one pushup and as you come up, shift your weight on the left side of the body, twist to the side while bringing the right arm up towards the ceiling in a side plank.",
            "Lower the arm back to the floor for another pushup and then twist to the other side.",
            "Repeat the series, alternating each side, for 10 or more reps.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "Hollow Body Hold / Rock",
        "type": "strength",
        "instructions": [
            "Lie on your back with your arms extended overhead and your legs straight. Press your lower back firmly into the floor.",
            "Lift your shoulders and legs a few inches off the floor at the same time, forming a slight banana-shaped curve with your body. This is your starting position.",
            "Hold this hollow position, keeping your lower back pressed down and breathing steadily, for the target duration.",
            "For the rocking variation, gently rock forward and back along your spine while maintaining the hollow shape.",
            "Lower your arms, shoulders, and legs back to the floor once the set is complete.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "L-Sit Hold",
        "type": "strength",
        "instructions": [
            "Sit between two parallel bars or blocks with your hands planted at your sides, fingers pointing forward.",
            "Press down through your hands to lift your entire body off the ground, straightening your arms. This is your starting position.",
            "Raise your legs out in front of you until they're parallel to the floor, keeping your knees locked straight and your toes pointed.",
            "Hold this position, keeping your shoulders depressed away from your ears, for the target duration.",
            "Lower your legs and then your body back down with control once the set is complete.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "Dragon Flag",
        "type": "strength",
        "instructions": [
            "Lie on a flat bench and grip behind your head for support. Press your upper back firmly into the bench.",
            "Raise your legs and hips straight up off the bench until only your shoulders remain in contact with the surface, keeping your entire body in one rigid line. This is your starting position.",
            "Slowly lower your entire body as one straight, rigid unit toward the bench, inhaling as you descend, stopping just before your lower back would touch down.",
            "Reverse the motion to raise your body back up to the starting position, exhaling as you rise.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Ab Wheel Rollout",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Ab_Rollout/0.jpg",
        "instructions": [
            "For this exercise you will need to get into a pushup position, but instead of having your hands of the floor, you will be grabbing on to an Olympic barbell (loaded with 5-10 lbs on each side) instead. This will be your starting position.",
            "While keeping a slight arch on your back, lift your hips and roll the barbell towards your feet as you exhale. Tip: As you perform the movement, your glutes should be coming up, you should be keeping the abs tight and should maintain your back posture at all times. Also your arms should be staying perpendicular to the floor throughout the movement. If you don't, you will work out your shoulders and back more than the abs.",
            "After a second contraction at the top, start to roll the barbell back forward to the starting position slowly as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Sit-Ups / Weighted Sit-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Weighted_Sit-Ups_-_With_Bands/0.jpg",
        "instructions": [
            "Start out by strapping the bands around the base of the decline bench. Place the handles towards the inside of the decline bench so that when lying down, you can reach for both of them.",
            "Position your legs through the decline machine until they are secured. Now reach for the exercise bands with both hands. Use a pronated (palms forward) grip to grasp the handles. Position them near your collar bone and rotate your wrist to a neutral grip (palms facing the torso). Note: Your arms should remain stationary throughout the exercise. This is the starting position.",
            "Move your torso upward until your upper body is perpendicular to the floor while exhaling. Hold the contraction for a second and lower your upper body back down to the starting position while inhaling.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "V-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jackknife_Sit-Up/0.jpg",
        "instructions": [
            "Lie flat on the floor on your back with your arms extended straight behind your head and your legs extended as well. This will be your starting position.",
            "As you exhale, bend at the waist while simultaneously raising your legs and arms to meet in a V-shaped jackknife position.",
            "Keep your legs extended and lifted at around a 45-degree angle from the floor, arms extended and parallel to your legs, with your upper torso off the floor.",
            "While inhaling, lower your arms and legs back to the starting position under control.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Bicycle Crunches",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunches/0.jpg",
        "instructions": [
            "Lie flat on your back with your feet flat on the ground, or resting on a bench with your knees bent at a 90 degree angle. If you are resting your feet on a bench, place them three to four inches apart and point your toes inward so they touch.",
            "Now place your hands lightly on either side of your head keeping your elbows in. Tip: Don't lock your fingers behind your head.",
            "While pushing the small of your back down in the floor to better isolate your abdominal muscles, begin to roll your shoulders off the floor.",
            "Continue to push down as hard as you can with your lower back as you contract your abdominals and exhale. Your shoulders should come up off the floor only about four inches, and your lower back should remain on the floor. At the top of the movement, contract your abdominals hard and keep the contraction for a second. Tip: Focus on slow, controlled movement - don't cheat yourself by using momentum.",
            "After the one second contraction, begin to come down slowly again to the starting position as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dead Bug",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/0.jpg",
        "instructions": [
            "Begin lying on your back with your hands extended above you toward the ceiling.",
            "Bring your feet, knees, and hips up to 90 degrees.",
            "Exhale hard to bring your ribcage down and flatten your back onto the floor, rotating your pelvis up and squeezing your glutes. Hold this position throughout the movement. This will be your starting position.",
            "Initiate the exercise by extending one leg, straightening the knee and hip to bring the leg just above the ground.",
            "Maintain the position of your lumbar and pelvis as you perform the movement, as your back is going to want to arch.",
            "Stay tight and return the working leg to the starting position.",
            "Repeat on the opposite side, alternating until the set is complete.",
        ],
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cable Twist (High to Low / Woodchopper)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Russian_Twists/0.jpg",
        "instructions": [
            "Connect a standard handle attachment, and position the cable to a middle pulley position.",
            "Lie on a stability ball perpendicular to the cable and grab the handle with one hand. You should be approximately arm's length away from the pulley, with the tension of the weight on the cable.",
            "Grab the handle with both hands and fully extend your arms above your chest. You hands should be directly in-line with the pulley. If not, adjust the pulley up or down until they are.",
            "Keep your hips elevated and abs engaged. Rotate your torso away from the pulley for a full-quarter rotation. Your body should be flat from head to knees.",
            "Pause for a moment and in a slow and controlled manner reset to the starting position. You should still have side tension on the cable in the resting position.",
            "Repeat the same movement to failure.",
            "Then, reposition and repeat the same series of movements on the opposite side.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cable Twist (Low to High)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Russian_Twists/0.jpg",
        "instructions": [
            "Connect a standard handle attachment, and position the cable to a middle pulley position.",
            "Lie on a stability ball perpendicular to the cable and grab the handle with one hand. You should be approximately arm's length away from the pulley, with the tension of the weight on the cable.",
            "Grab the handle with both hands and fully extend your arms above your chest. You hands should be directly in-line with the pulley. If not, adjust the pulley up or down until they are.",
            "Keep your hips elevated and abs engaged. Rotate your torso away from the pulley for a full-quarter rotation. Your body should be flat from head to knees.",
            "Pause for a moment and in a slow and controlled manner reset to the starting position. You should still have side tension on the cable in the resting position.",
            "Repeat the same movement to failure.",
            "Then, reposition and repeat the same series of movements on the opposite side.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cable Pallof Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pallof_Press/0.jpg",
        "instructions": [
            "Connect a standard handle to a tower, and—if possible—position the cable to shoulder height. If not, a low pulley will suffice.",
            "With your side to the cable, grab the handle with both hands and step away from the tower. You should be approximately arm's length away from the pulley, with the tension of the weight on the cable.",
            "With your feet positioned hip-width apart and knees slightly bent, hold the cable to the middle of your chest. This will be your starting position.",
            "Press the cable away from your chest, fully extending both arms. You core should be tight and engaged.",
            "Hold the repetition for several seconds before returning to the starting position.",
            "At the conclusion of the set, repeat facing the other direction.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Russian Twists / Weighted",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg",
        "instructions": [
            "Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees.",
            "Elevate your upper body so that it creates an imaginary V-shape with your thighs. Your arms should be fully extended in front of you perpendicular to your torso and with the hands clasped. This is the starting position.",
            "Twist your torso to the right side until your arms are parallel with the floor while breathing out.",
            "Hold the contraction for a second and move back to the starting position while breathing out. Now move to the opposite side performing the same techniques you applied to the right side.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Side Bends",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Side_Bend/0.jpg",
        "instructions": [
            "Stand up straight while holding a dumbbell on the left hand (palms facing the torso) as you have the right hand holding your waist. Your feet should be placed at shoulder width. This will be your starting position.",
            "While keeping your back straight and your head up, bend only at the waist to the right as far as possible. Breathe in as you bend to the side. Then hold for a second and come back up to the starting position as you exhale. Tip: Keep the rest of the body stationary.",
            "Now repeat the movement but bending to the left instead. Hold for a second and come back to the starting position.",
            "Repeat for the recommended amount of repetitions and then change hands.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
            "Quads",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Landmine 180s",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Landmine_180s/0.jpg",
        "instructions": [
            "Position a bar into a landmine or securely anchor it in a corner. Load the bar to an appropriate weight.",
            "Raise the bar from the floor, taking it to shoulder height with both hands with your arms extended in front of you. Adopt a wide stance. This will be your starting position.",
            "Perform the movement by rotating the trunk and hips as you swing the weight all the way down to one side. Keep your arms extended throughout the exercise.",
            "Reverse the motion to swing the weight all the way to the opposite side.",
            "Continue alternating the movement until the set is complete.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Abs",
        "secondary_muscles": [
            "Lower Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Farmers Walk / Suitcase Carry",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Farmers_Walk/0.jpg",
        "instructions": [
            "There are various implements that can be used for the farmers walk. These can also be performed with heavy dumbbells or short bars if these implements aren't available. Begin by standing between the implements.",
            "After gripping the handles, lift them up by driving through your heels, keeping your back straight and your head up.",
            "Walk taking short, quick steps, and don't forget to breathe. Move for a given distance, typically 50-100 feet, as fast as possible.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [
            "Traps",
            "Abs",
            "Quads",
        ],
        "tracking_fields": [
            "weight",
            "distance",
        ],
    },
]
