"""Core entries for the global exercise database."""

CORE_EXERCISES = [
    {
        "name": "Crunches",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Crunch Machine",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Crunches",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Decline Crunches",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Hanging Leg Raises",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Hanging Knee Raises",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Captain's Chair Leg Raises",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Lying Leg Raises",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Toes to Bar",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Plank",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["time"],
    },
    {
        "name": "Weighted Plank",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["weight", "time"],
    },
    {
        "name": "Side Plank",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["time"],
    },
    {
        "name": "Hollow Body Hold / Rock",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": ["time"],
    },
    {
        "name": "L-Sit Hold",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": ["time"],
    },
    {
        "name": "Dragon Flag",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Ab Wheel Rollout",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Sit-Ups / Weighted Sit-Ups",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "V-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Bicycle Crunches",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Dead Bug",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Abs",
        "secondary_muscles": [],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Cable Twist (High to Low / Woodchopper)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Twist (Low to High)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Pallof Press",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Russian Twists / Weighted",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Side Bends",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back", "Quads"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Landmine 180s",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Abs",
        "secondary_muscles": ["Lower Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Farmers Walk / Suitcase Carry",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": ["Traps", "Abs", "Quads"],
        "tracking_fields": ["weight", "distance"],
    }
]