"""Forearm entries for the global exercise database."""

FOREARM_EXERCISES = [
    {
        "name": "Dumbbell Forearm Curls (Wrist Curls)",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Forearm Extensions (Reverse Wrist Curls)",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Pronation / Supination",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Forearm Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Forearm Extensions",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "EZ-Bar Forearm Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "EZ-Bar Forearm Extensions",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Behind Body Barbell Forearm Curls",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Straight Bar Cable Forearm Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Straight Bar Cable Forearm Extensions",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "D-Handle Cable Forearm Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "D-Handle Cable Forearm Extensions",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Behind Smith Machine Forearm Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Wrist Roller",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": ["Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Plate Pinches",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "time"],
    },
    {
        "name": "Dead Hangs",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Forearms",
        "secondary_muscles": ["Lats", "Anterior Delt"],
        "tracking_fields": ["time"],
    },
    {
        "name": "Zottman Curls",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": ["Biceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Sledgehammer / Leverage Bar Levering",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Towel Pull-Ups / Towel Hangs",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Forearms",
        "secondary_muscles": ["Lats", "Biceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Hex Dumbbell Holds",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "time"],
    },
    {
        "name": "Hand Grippers (Captains of Crush)",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Thick Bar / Fat Gripz Holds",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": ["Traps"],
        "tracking_fields": ["weight", "time"],
    }
]