"""Forearm entries for the global exercise database."""

FOREARM_EXERCISES = [
    {
        "name": "Dumbbell Forearm Curls (Wrist Curls)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Dumbbell_Palms-Up_Wrist_Curl/0.jpg",
        "instructions": [
            "Start out by placing two dumbbells on the floor in front of a flat bench.",
            "Sit down on the edge of the flat bench with your legs at about shoulder width apart. Make sure to keep your feet on the floor.",
            "Use your arms to grab both of the dumbbells and bring them up so that your forearms are resting against your thighs with the palms of the hands facing up. Your wrists should be hanging over the edge of your thighs.",
            "Start out by curling your wrist upwards and exhaling.",
            "Slowly lower your wrists back down to the starting position while inhaling. Make sure to inhale during this part of the exercise. Tip: Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.",
            "Repeat for the recommended amount of repetitions.",
            "When finished, simply lower the dumbbells to the floor.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Forearm Extensions (Reverse Wrist Curls)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Dumbbell_Palms-Down_Wrist_Curl/0.jpg",
        "instructions": [
            "Start out by placing two dumbbells on the floor in front of a flat bench.",
            "Sit down on the edge of the flat bench with your legs at about shoulder width apart. Make sure to keep your feet on the floor.",
            "Use your arms to grab both of the dumbbells and bring them up so that your forearms are resting against your thighs with the palms of the hands facing down. Your wrists should be hanging over the edge of your thighs.",
            "Start out by curling your wrist upwards and exhaling.",
            "Slowly lower your wrists back down to the starting position while inhaling. Make sure to inhale during this part of the exercise. Tip: Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.",
            "Repeat for the recommended amount of repetitions.",
            "When finished, simply lower the dumbbells to the floor.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Pronation / Supination",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lying_Supination/0.jpg",
        "instructions": [
            "Lie sideways on a flat bench with one arm holding a dumbbell and the other hand on top of the bench folded so that you can rest your head on it.",
            "Bend the elbows of the arm holding the dumbbell so that it creates a 90-degree angle between the upper arm and the forearm.",
            "Now raise the upper arm so that the forearm is parallel to the floor and perpendicular to your torso (Tip: So the forearm will be directly in front of you). The upper arm will be stationary by your torso and should be parallel to the floor (aligned with your torso at all times). This will be your starting position.",
            "As you breathe out, externally rotate your forearm so that the dumbbell is lifted up in a semicircle motion as you maintain the 90 degree angle bend between the upper arms and the forearm. You will continue this external rotation until the forearm is perpendicular to the floor and the torso pointing towards the ceiling. At this point you will hold the contraction for a second.",
            "As you breathe in, slowly go back to the starting position.",
            "Repeat for the recommended amount of repetitions and then switch to the other arm.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Barbell Forearm Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg",
        "instructions": [
            "Stand up with your torso upright while holding a barbell at a shoulder-width grip. The palm of your hands should be facing forward and the elbows should be close to the torso. This will be your starting position.",
            "While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move.",
            "Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.",
            "Slowly begin to bring the bar back to starting position as your breathe in.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Barbell Forearm Extensions",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Palms-Down_Wrist_Curl_Over_A_Bench/0.jpg",
        "instructions": [
            "Start out by placing a barbell on one side of a flat bench.",
            "Kneel down on both of your knees so that your body is facing the flat bench.",
            "Use your arms to grab the barbell with a pronated grip (palms down) and bring them up so that your forearms are resting against the flat bench. Your wrists should be hanging over the edge.",
            "Start out by curling your wrist upwards and exhaling.",
            "Slowly lower your wrists back down to the starting position while inhaling.",
            "Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "EZ-Bar Forearm Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Palm-Up_Barbell_Wrist_Curl/0.jpg",
        "instructions": [
            "Hold a barbell with both hands and your palms facing up; hands spaced about shoulder width.",
            "Place your feet flat on the floor, at a distance that is slightly wider than shoulder width apart.",
            "Lean forward and place your forearms on top of your upper thighs with your palms up. Tip: Make sure that the front of the wrists lay on top of your knees. This will be your starting position.",
            "Lower the bar as far as possible while inhaling and keeping a tight grip.",
            "Now curl bar up as high as possible while flexing the forearms and exhaling. Hold the contraction at the top for a second and Tip: Only the wrist should move.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "EZ-Bar Forearm Extensions",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Palms-Down_Barbell_Wrist_Curl/0.jpg",
        "instructions": [
            "Hold a barbell with both hands and your palms facing down; hands spaced about shoulder width.",
            "Place your feet flat on the floor, at a distance that is slightly wider than shoulder width apart.",
            "Lean forward and place your forearms on top of your upper thighs with your palms down. Tip: Make sure that the back of the wrists lay on top of your knees. This will be your starting position.",
            "Lower the bar as far as possible while inhaling and keeping a tight grip.",
            "Now curl bar up as high as possible while flexing the forearms and exhaling. Hold the contraction at the top for a second and Tip: Only the wrist should move.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Behind Body Barbell Forearm Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl/0.jpg",
        "instructions": [
            "Start by standing straight and holding a barbell behind your glutes at arm's length while using a pronated grip (palms will be facing back away from the glutes) and having your hands shoulder width apart from each other.",
            "You should be looking straight forward while your feet are shoulder width apart from each other. This is the starting position.",
            "While exhaling, slowly elevate the barbell up by curling your wrist in a semi-circular motion towards the ceiling. Note: Your wrist should be the only body part moving for this exercise.",
            "Hold the contraction for a second and lower the barbell back down to the starting position while inhaling.",
            "Repeat for the recommended amount of repetitions.",
            "When finished, lower the barbell down to the squat rack or the floor by bending the knees. Tip: It is easiest to either pick it up from a squat rack or have a partner hand it to you.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Straight Bar Cable Forearm Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Wrist_Curl/0.jpg",
        "instructions": [
            "Start out by placing a flat bench in front of a low pulley cable that has a straight bar attachment.",
            "Use your arms to grab the cable bar with a narrow to shoulder width supinated grip (palms up) and bring them up so that your forearms are resting against the top of your thighs. Your wrists should be hanging just beyond your knees.",
            "Start out by curling your wrist upwards and exhaling. Keep the contraction for a second.",
            "Slowly lower your wrists back down to the starting position while inhaling.",
            "Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Straight Bar Cable Forearm Extensions",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Wrist_Curl/0.jpg",
        "instructions": [
            "Start out by placing a flat bench in front of a low pulley cable that has a straight bar attachment.",
            "Use your arms to grab the cable bar with a narrow to shoulder width supinated grip (palms up) and bring them up so that your forearms are resting against the top of your thighs. Your wrists should be hanging just beyond your knees.",
            "Start out by curling your wrist upwards and exhaling. Keep the contraction for a second.",
            "Slowly lower your wrists back down to the starting position while inhaling.",
            "Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "D-Handle Cable Forearm Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Wrist_Curl/0.jpg",
        "instructions": [
            "Start out by placing a flat bench in front of a low pulley cable that has a straight bar attachment.",
            "Use your arms to grab the cable bar with a narrow to shoulder width supinated grip (palms up) and bring them up so that your forearms are resting against the top of your thighs. Your wrists should be hanging just beyond your knees.",
            "Start out by curling your wrist upwards and exhaling. Keep the contraction for a second.",
            "Slowly lower your wrists back down to the starting position while inhaling.",
            "Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "D-Handle Cable Forearm Extensions",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Wrist_Curl/0.jpg",
        "instructions": [
            "Start out by placing a flat bench in front of a low pulley cable that has a straight bar attachment.",
            "Use your arms to grab the cable bar with a narrow to shoulder width supinated grip (palms up) and bring them up so that your forearms are resting against the top of your thighs. Your wrists should be hanging just beyond your knees.",
            "Start out by curling your wrist upwards and exhaling. Keep the contraction for a second.",
            "Slowly lower your wrists back down to the starting position while inhaling.",
            "Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Behind Smith Machine Forearm Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl/0.jpg",
        "instructions": [
            "Start by standing straight and holding a barbell behind your glutes at arm's length while using a pronated grip (palms will be facing back away from the glutes) and having your hands shoulder width apart from each other.",
            "You should be looking straight forward while your feet are shoulder width apart from each other. This is the starting position.",
            "While exhaling, slowly elevate the barbell up by curling your wrist in a semi-circular motion towards the ceiling. Note: Your wrist should be the only body part moving for this exercise.",
            "Hold the contraction for a second and lower the barbell back down to the starting position while inhaling.",
            "Repeat for the recommended amount of repetitions.",
            "When finished, lower the barbell down to the squat rack or the floor by bending the knees. Tip: It is easiest to either pick it up from a squat rack or have a partner hand it to you.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Wrist Roller",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wrist_Roller/0.jpg",
        "instructions": [
            "To begin, stand straight up grabbing a wrist roller using a pronated grip (palms facing down). Your feet should be shoulder width apart.",
            "Slowly lift both arms until they are fully extended and parallel to the floor in front of you. Note: Make sure the rope is not wrapped around the roller. Your entire body should be stationary except for the forearms. This is the starting position.",
            "Rotate one wrist at a time in an upward motion to bring the weight up to the bar by rolling the rope around the roller.",
            "Once the weight has reached the bar, slowly begin to lower the weight back down by rotating the wrist in a downward motion until the weight reaches the starting position.",
            "Repeat for the prescribed amount of repetitions in your program.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Forearms",
        "secondary_muscles": [
            "Anterior Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Plate Pinches",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plate_Pinch/0.jpg",
        "instructions": [
            "Grab two wide-rimmed plates and put them together with the smooth sides facing outward",
            "Use your fingers to grip the outside part of the plate and your thumb for the other side thus holding both plates together. This is the starting position.",
            "Squeeze the plate with your fingers and thumb. Hold this position for as long as you can.",
            "Repeat for the recommended amount of sets prescribed in your program.",
            "Switch arms and repeat the movements.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "time",
        ],
    },
    {
        "name": "Dead Hangs",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Forearms",
        "secondary_muscles": [
            "Lats",
            "Anterior Delt",
        ],
        "tracking_fields": [
            "time",
        ],
    },
    {
        "name": "Zottman Curls",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Zottman_Curl/0.jpg",
        "instructions": [
            "Stand up with your torso upright and a dumbbell in each hand being held at arms length. The elbows should be close to the torso.",
            "Make sure the palms of the hands are facing each other. This will be your starting position.",
            "While holding the upper arm stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Your wrist should rotate so that you have a supinated (palms up) grip. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level.",
            "Hold the contracted position for a second as you squeeze the biceps.",
            "Now during the contracted position, rotate your wrist until you now have a pronated (palms facing down) grip with the thumb at a higher position than the pinky.",
            "Slowly begin to bring the dumbbells back down using the pronated grip.",
            "As the dumbbells close your thighs, start rotating the wrist so that you go back to a neutral (palms facing your body) grip.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [
            "Biceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Sledgehammer / Leverage Bar Levering",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Towel Pull-Ups / Towel Hangs",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Forearms",
        "secondary_muscles": [
            "Lats",
            "Biceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Hex Dumbbell Holds",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "time",
        ],
    },
    {
        "name": "Hand Grippers (Captains of Crush)",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Forearms",
        "secondary_muscles": [],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Thick Bar / Fat Gripz Holds",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Forearms",
        "secondary_muscles": [
            "Traps",
        ],
        "tracking_fields": [
            "weight",
            "time",
        ],
    },
]
