"""Leg entries for the global exercise database."""

LEG_EXERCISES = [
    {
        "name": "Barbell Squat",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Lower Back", "Hamstrings", "Adductor", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Front Squat",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Zercher Squat",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Goblet Squat",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine Squat",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Bodyweight Squats",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Calves", "Glutes"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Hack Squat",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Pendulum Squat",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Squat Machine (V-Squat / Leverage Squat)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Belt Squat",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Sissy Squats",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Leg Press (Plate Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Leg Press (Pin Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Vertical Leg Press",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Bulgarian Split Squats",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Glutes", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Bulgarian Split Squats",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine Bulgarian Split Squats",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Bodyweight Bulgarian Split Squats",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Dumbbell Lunges",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Glutes", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Reverse Lunges (Barbell or Dumbbell)",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Hamstrings", "Quads"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Body Weight Lunges",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Dumbbell Walking Lunges",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Body Weight Walking Lunges",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Weight Bag Walking Lunges",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Weight Bag Lunges",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glutes", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cossack Squats / Lateral Lunges",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Hamstrings", "Adductor", "Glutes"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Barbell RDLs (Romanian Deadlifts)",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Lower Back", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell RDLs",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Lower Back", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single Leg Dumbbell RDLs",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Calves", "Glutes", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine RDLs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Lower Back", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Straight Leg Deadlifts (Barbell)",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Lower Back", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Straight Leg RDLs",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Lower Back", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single Leg Dumbbell Straight Leg RDLs",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine Straight Leg RDLs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Lower Back", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine Good Mornings",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Lower Back", "Glutes"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Pull-Throughs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Lower Back", "Hamstrings"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Lying Leg Curls (Plate Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Calves"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Lying Leg Curls (Pin Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Calves"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Seated Leg Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Calves"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single Leg Curls (Plate Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Standing Cable Leg Curls",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Nordic Hamstring Curls",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Lower Back", "Glutes"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Leg Extensions (Plate Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Leg Extensions (Pin Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Quads",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Hip Thrusts",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Hamstrings", "Quads"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine Hip Thrusts",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Hamstrings"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Hip Thrust Machine",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Hamstrings"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Glute Bridges (Barbell or Bodyweight)",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Hamstrings"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Roman Chair Glute Extensions",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Lower Back", "Hamstrings"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Roman Chair Hamstring Extensions (Glute-Ham Raise)",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Lower Back", "Calves", "Glutes"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Reverse Hyperextensions",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Lower Back", "Hamstrings"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Leg Kick Back Machine",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Hamstrings"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Leg Kick Back",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Hamstrings"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Deficit Glute Step-Ups (Eccentric Step-Downs)",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Quads"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Adductor Machine (Inner Thigh)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Adductor",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Abductor Machine (Outer Glute)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Glutes",
        "secondary_muscles": ["Abductor"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Seated Calves Machine",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Calves",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Leg Press Calf Raises",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Calves",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine Calf Raises",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Calves",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Straight Leg Calves Machine (Standing)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Calves",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Calf Raises",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Calves",
        "secondary_muscles": ["Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Calf Raises (Bilateral)",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Calves",
        "secondary_muscles": ["Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single-Leg Standing Calf Raises",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Calves",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Donkey Calf Raises Machine",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Calves",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Tibialis Raises",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Calves",
        "secondary_muscles": [],
        "tracking_fields": ["reps", "rir"],
    }
]