"""Shoulder entries for the global exercise database."""

SHOULDER_EXERCISES = [
    {
        "name": "Standing Barbell Overhead Press (OHP)",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Triceps", "Abs", "Lateral Delt", "Traps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Seated Barbell Overhead Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Triceps", "Lateral Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Barbell Push Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Glutes", "Triceps", "Traps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Seated Dumbbell Shoulder Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Triceps", "Lateral Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Arnold Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Triceps", "Lateral Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Standing Dumbbell Shoulder Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Triceps", "Abs", "Lateral Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Lateral Raise",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": ["Anterior Delt", "Traps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Seated Dumbbell Lateral Raise",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": ["Traps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Standing Dumbbell Lateral Raise",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": ["Traps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Lateral Raise (Single Arm)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": ["Traps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Machine Lateral Raise",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": ["Traps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Front Raise",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Chest", "Lateral Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Front Raise",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Chest"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Plate Front Raise",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Forearms", "Chest"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Reverse Pec Deck Fly",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": ["Traps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Rear Delt Fly (Bent-Over)",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": ["Traps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Chest-Supported Dumbbell Rear Delt Fly",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": ["Traps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Rear Delt Fly (Cross-Body)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": ["Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Face Pulls (Shoulder Focus)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": ["Traps", "Mid Back"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine Overhead Press",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Triceps", "Lateral Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Machine Shoulder Press (Plate-Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Triceps", "Lateral Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Machine Shoulder Press (Pin-Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Triceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Pike Push-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Chest", "Triceps"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Handstand Push-Ups (Wall Supported)",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Triceps", "Abs", "Lateral Delt"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Single-Arm Landmine Shoulder Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Chest", "Triceps", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Kettlebell Z-Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Triceps", "Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },  
    {                   
        "name": "Upright Rows (Shoulder Focus / Wide Grip)",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": ["Anterior Delt", "Traps", "Biceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Upright Rows (Shoulder Focus / Wide Grip)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": ["Anterior Delt", "Traps", "Biceps"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable External Rotation",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": ["Lateral Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Internal Rotation",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": ["Chest"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
]