"""Shoulder entries for the global exercise database."""

SHOULDER_EXERCISES = [
    {
        "name": "Standing Barbell Overhead Press (OHP)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Military_Press/0.jpg",
        "instructions": [
            "Start by placing a barbell that is about chest high on a squat rack. Once you have selected the weights, grab the barbell using a pronated (palms facing forward) grip. Make sure to grip the bar wider than shoulder width apart from each other.",
            "Slightly bend the knees and place the barbell on your collar bone. Lift the barbell up keeping it lying on your chest. Take a step back and position your feet shoulder width apart from each other.",
            "Once you pick up the barbell with the correct grip length, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position.",
            "Lower the bar down to the collarbone slowly as you inhale.",
            "Lift the bar back up to the starting position as you exhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Triceps",
            "Abs",
            "Lateral Delt",
            "Traps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Seated Barbell Overhead Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Barbell_Military_Press/0.jpg",
        "instructions": [
            "Sit on a Military Press Bench with a bar behind your head and either have a spotter give you the bar (better on the rotator cuff this way) or pick it up yourself carefully with a pronated grip (palms facing forward). Tip: Your grip should be wider than shoulder width and it should create a 90-degree angle between the forearm and the upper arm as the barbell goes down.",
            "Once you pick up the barbell with the correct grip length, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position.",
            "Lower the bar down to the collarbone slowly as you inhale.",
            "Lift the bar back up to the starting position as you exhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Triceps",
            "Lateral Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Barbell Push Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push_Press/0.jpg",
        "instructions": [
            "Stand with your feet shoulder-width apart and the bar racked across the front of your shoulders, elbows up, gripping it just outside shoulder width.",
            "Dip down a few inches by bending your knees and hips slightly, keeping your torso upright. This will be your starting position.",
            "Drive explosively through your legs and extend your hips as you press the bar overhead, using the leg drive to help launch the weight past the sticking point. Exhale as you press.",
            "Lock the bar out fully overhead, then lower it back down to your shoulders under control as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Glutes",
            "Triceps",
            "Traps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Seated Dumbbell Shoulder Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg",
        "instructions": [
            "While holding a dumbbell in each hand, sit on a military press bench or utility bench that has back support. Place the dumbbells upright on top of your thighs.",
            "Now raise the dumbbells to shoulder height one at a time using your thighs to help propel them up into position.",
            "Make sure to rotate your wrists so that the palms of your hands are facing forward. This is your starting position.",
            "Now, exhale and push the dumbbells upward until they touch at the top.",
            "Then, after a brief pause at the top contracted position, slowly lower the weights back down to the starting position while inhaling.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Triceps",
            "Lateral Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Arnold Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg",
        "instructions": [
            "Sit on an exercise bench with back support and hold two dumbbells in front of you at about upper chest level with your palms facing your body and your elbows bent. Tip: Your arms should be next to your torso. The starting position should look like the contracted portion of a dumbbell curl.",
            "Now to perform the movement, raise the dumbbells as you rotate the palms of your hands until they are facing forward.",
            "Continue lifting the dumbbells until your arms are extended above you in straight arm position. Breathe out as you perform this portion of the movement.",
            "After a second pause at the top, begin to lower the dumbbells to the original position by rotating the palms of your hands towards you. Tip: The left arm will be rotated in a counter clockwise manner while the right one will be rotated clockwise. Breathe in as you perform this portion of the movement.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Triceps",
            "Lateral Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Standing Dumbbell Shoulder Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg",
        "instructions": [
            "While holding a dumbbell in each hand, sit on a military press bench or utility bench that has back support. Place the dumbbells upright on top of your thighs.",
            "Now raise the dumbbells to shoulder height one at a time using your thighs to help propel them up into position.",
            "Make sure to rotate your wrists so that the palms of your hands are facing forward. This is your starting position.",
            "Now, exhale and push the dumbbells upward until they touch at the top.",
            "Then, after a brief pause at the top contracted position, slowly lower the weights back down to the starting position while inhaling.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Triceps",
            "Abs",
            "Lateral Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Lateral Raise",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg",
        "instructions": [
            "Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position.",
            "While maintaining the torso in a stationary position (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.",
            "Lower the dumbbells back down slowly to the starting position as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": [
            "Anterior Delt",
            "Traps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Seated Dumbbell Lateral Raise",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Side_Lateral_Raise/0.jpg",
        "instructions": [
            "Pick a couple of dumbbells and sit at the end of a flat bench with your feet firmly on the floor. Hold the dumbbells with your palms facing in and your arms straight down at your sides at arms' length. This will be your starting position.",
            "While maintaining the torso stationary (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.",
            "Lower the dumbbells back down slowly to the starting position as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": [
            "Traps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Standing Dumbbell Lateral Raise",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg",
        "instructions": [
            "Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position.",
            "While maintaining the torso in a stationary position (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.",
            "Lower the dumbbells back down slowly to the starting position as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": [
            "Traps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cable Lateral Raise (Single Arm)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Incline_Lateral_Raise/0.jpg",
        "instructions": [
            "Lie down sideways on an incline bench press with a dumbbell in the hand. Make sure the shoulder is pressing against the incline bench and the arm is lying across your body with the palm around your navel.",
            "Hold a dumbbell in your uppermost arm while keeping it extended in front of you parallel to the floor. This is your starting position.",
            "While keeping the dumbbell parallel to the floor at all times, perform a lateral raise. Your arm should travel straight up until it is pointing at the ceiling. Tip: Exhale as you perform this movement. Hold the dumbbell in the position and feel the contraction in the shoulders for a second.",
            "While inhaling lower the weight across your body back into the starting position.",
            "Repeat the movement for the prescribed amount of repetitions.",
            "Switch arms and repeat the movement.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": [
            "Traps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Machine Lateral Raise",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg",
        "instructions": [
            "Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position.",
            "While maintaining the torso in a stationary position (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.",
            "Lower the dumbbells back down slowly to the starting position as you inhale.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": [
            "Traps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Front Raise",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Dumbbell_Raise/0.jpg",
        "instructions": [
            "Pick a couple of dumbbells and stand with a straight torso and the dumbbells on front of your thighs at arms length with the palms of the hand facing your thighs. This will be your starting position.",
            "While maintaining the torso stationary (no swinging), lift the left dumbbell to the front with a slight bend on the elbow and the palms of the hands always facing down. Continue to go up until you arm is slightly above parallel to the floor. Exhale as you execute this portion of the movement and pause for a second at the top. Inhale after the second pause.",
            "Now lower the dumbbell back down slowly to the starting position as you simultaneously lift the right dumbbell.",
            "Continue alternating in this fashion until all of the recommended amount of repetitions have been performed for each arm.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Chest",
            "Lateral Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cable Front Raise",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Cable_Raise/0.jpg",
        "instructions": [
            "Select the weight on a low pulley machine and grasp the single hand cable attachment that is attached to the low pulley with your left hand.",
            "Face away from the pulley and put your arm straight down with the hand cable attachment in front of your thighs at arms' length with the palms of the hand facing your thighs. This will be your starting position.",
            "While maintaining the torso stationary (no swinging), lift the left arm to the front with a slight bend on the elbow and the palms of the hand always faces down. Continue to go up until you arm is slightly above parallel to the floor. Exhale as you execute this portion of the movement and pause for a second at the top.",
            "Now as you inhale lower the arm back down slowly to the starting position.",
            "Once all of the recommended amount of repetitions have been performed for this arm, switch arms and perform the exercise with the right one.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Chest",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Plate Front Raise",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Plate_Raise/0.jpg",
        "instructions": [
            "While standing straight, hold a barbell plate in both hands at the 3 and 9 o'clock positions. Your palms should be facing each other and your arms should be extended and locked with a slight bend at the elbows and the plate should be down near your waist in front of you as far as you can go. Tip: The arms will remain in this position throughout the exercise. This will be your starting position.",
            "Slowly raise the plate as you exhale until it is a little above shoulder level. Hold the contraction for a second. Tip: make sure that you do not swing the weight or bend at the elbows. Your torso should remain stationary throughout the movement as well.",
            "As you inhale, slowly lower the plate back down to the starting position.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Plate",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Forearms",
            "Chest",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Reverse Pec Deck Fly",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Machine_Flyes/0.jpg",
        "instructions": [
            "Adjust the handles so that they are fully to the rear. Make an appropriate weight selection and adjust the seat height so the handles are at shoulder level. Grasp the handles with your hands facing inwards. This will be your starting position.",
            "In a semicircular motion, pull your hands out to your side and back, contracting your rear delts.",
            "Keep your arms slightly bent throughout the movement, with all of the motion occurring at the shoulder joint.",
            "Pause at the rear of the movement, and slowly return the weight to the starting position.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": [
            "Traps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Dumbbell Rear Delt Fly (Bent-Over)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench/0.jpg",
        "instructions": [
            "Stand up straight while holding a dumbbell in each hand and with an incline bench in front of you.",
            "While keeping your back straight and maintaining the natural arch of your back, lean forward until your forehead touches the bench in front of you. Let the arms hang in front of you perpendicular to the ground. The palms of your hands should be facing each other and your torso should be parallel to the floor. This will be your starting position.",
            "Keeping your torso forward and stationary, and the arms straight with a slight bend at the elbows, lift the dumbbells straight to the side until both arms are parallel to the floor. Exhale as you lift the weights. Caution: avoid swinging the torso or bringing the arms back as opposed to the side.",
            "After a one second contraction at the top, slowly lower the dumbbells back to the starting position.",
            "Repeat the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": [
            "Traps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Chest-Supported Dumbbell Rear Delt Fly",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench/0.jpg",
        "instructions": [
            "Stand up straight while holding a dumbbell in each hand and with an incline bench in front of you.",
            "While keeping your back straight and maintaining the natural arch of your back, lean forward until your forehead touches the bench in front of you. Let the arms hang in front of you perpendicular to the ground. The palms of your hands should be facing each other and your torso should be parallel to the floor. This will be your starting position.",
            "Keeping your torso forward and stationary, and the arms straight with a slight bend at the elbows, lift the dumbbells straight to the side until both arms are parallel to the floor. Exhale as you lift the weights. Caution: avoid swinging the torso or bringing the arms back as opposed to the side.",
            "After a one second contraction at the top, slowly lower the dumbbells back to the starting position.",
            "Repeat the recommended amount of repetitions.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": [
            "Traps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cable Rear Delt Fly (Cross-Body)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rear_Delt_Fly/0.jpg",
        "instructions": [
            "Adjust the pulleys to the appropriate height and adjust the weight. The pulleys should be above your head.",
            "Grab the left pulley with your right hand and the right pulley with your left hand, crossing them in front of you. This will be your starting position.",
            "Initiate the movement by moving your arms back and outward, keeping your arms straight as you execute the movement.",
            "Pause at the end of the motion before returning the handles to the start position.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": [
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Face Pulls (Shoulder Focus)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg",
        "instructions": [
            "Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": [
            "Traps",
            "Mid Back",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Smith Machine Overhead Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Overhead_Shoulder_Press/0.jpg",
        "instructions": [
            "To begin, place a flat bench (or preferably one with back support) underneath a smith machine. Position the barbell at a height so that when seated on the flat bench, the arms must be almost fully extended to reach the barbell.",
            "Once you have the correct height, sit slightly in behind the barbell so that there is an imaginary straight line from the tip of your nose to the barbell. Your feet should be stationary. Grab the barbell with the palms facing forward, unlock it and lift it up so that your arms are fully extended. This is the starting position.",
            "Slowly begin to lower the barbell until it is level with your chin while inhaling.",
            "Then lift the barbell back to the starting position using your shoulders while exhaling.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Triceps",
            "Lateral Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Machine Shoulder Press (Plate-Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Shoulder_Press/0.jpg",
        "instructions": [
            "Load an appropriate weight onto the pins and adjust the seat for your height. The handles should be near the top of the shoulders at the beginning of the motion. Your chest and head should be up and handles held with a pronated grip. This will be your starting position.",
            "Press the handles upward by extending through the elbow.",
            "After a brief pause at the top, return the weight to just above the start position, keeping tension on the muscles by not returning the weight to the stops until the set is complete.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Triceps",
            "Lateral Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Machine Shoulder Press (Pin-Loaded)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Shoulder_Press/0.jpg",
        "instructions": [
            "Load an appropriate weight onto the pins and adjust the seat for your height. The handles should be near the top of the shoulders at the beginning of the motion. Your chest and head should be up and handles held with a pronated grip. This will be your starting position.",
            "Press the handles upward by extending through the elbow.",
            "After a brief pause at the top, return the weight to just above the start position, keeping tension on the muscles by not returning the weight to the stops until the set is complete.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Triceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Pike Push-Ups",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Handstand_Push-Ups/0.jpg",
        "instructions": [
            "With your back to the wall bend at the waist and place both hands on the floor at shoulder width.",
            "Kick yourself up against the wall with your arms straight. Your body should be upside down with the arms and legs fully extended. Keep your whole body as straight as possible. Tip: If doing this for the first time, have a spotter help you. Also, make sure that you keep facing the wall with your head, rather than looking down.",
            "Slowly lower yourself to the ground as you inhale until your head almost touches the floor. Tip: It is of utmost importance that you come down slow in order to avoid head injury.",
            "Push yourself back up slowly as you exhale until your elbows are nearly locked.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Chest",
            "Triceps",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Handstand Push-Ups (Wall Supported)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Handstand_Push-Ups/0.jpg",
        "instructions": [
            "With your back to the wall bend at the waist and place both hands on the floor at shoulder width.",
            "Kick yourself up against the wall with your arms straight. Your body should be upside down with the arms and legs fully extended. Keep your whole body as straight as possible. Tip: If doing this for the first time, have a spotter help you. Also, make sure that you keep facing the wall with your head, rather than looking down.",
            "Slowly lower yourself to the ground as you inhale until your head almost touches the floor. Tip: It is of utmost importance that you come down slow in order to avoid head injury.",
            "Push yourself back up slowly as you exhale until your elbows are nearly locked.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "None",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Triceps",
            "Abs",
            "Lateral Delt",
        ],
        "tracking_fields": [
            "reps",
            "rir",
        ],
    },
    {
        "name": "Single-Arm Landmine Shoulder Press",
        "type": "strength",
        "instructions": [
            "Load one end of a barbell into a landmine attachment, or wedge it securely into a corner, and stand facing it, holding the free end at shoulder height in one hand with your palm facing inward.",
            "Brace your core and stagger your stance slightly for stability. This is your starting position.",
            "Press the bar up and slightly forward along its natural arc until your arm is fully extended, exhaling as you press.",
            "Pause briefly at the top, then lower the bar back to shoulder height under control as you inhale.",
            "Complete all reps on one side before switching arms.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Chest",
            "Triceps",
            "Abs",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Kettlebell Z-Press",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Seated_Press/0.jpg",
        "instructions": [
            "Sit on the floor and spread your legs out comfortably.",
            "Clean one kettlebell to your shoulder.",
            "Press the kettlebell up and out until it is locked out overhead. Return to the starting position.",
        ],
        "equipment": "Dumbbell",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Triceps",
            "Abs",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Upright Rows (Shoulder Focus / Wide Grip)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg",
        "instructions": [
            "Grasp a barbell with an overhand grip that is slightly less than shoulder width. The bar should be resting on the top of your thighs with your arms extended and a slight bend in your elbows. Your back should also be straight. This will be your starting position.",
            "Now exhale and use the sides of your shoulders to lift the bar, raising your elbows up and to the side. Keep the bar close to your body as you raise it. Continue to lift the bar until it nearly touches your chin. Tip: Your elbows should drive the motion, and should always be higher than your forearms. Remember to keep your torso stationary and pause for a second at the top of the movement.",
            "Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Barbell",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": [
            "Anterior Delt",
            "Traps",
            "Biceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cable Upright Rows (Shoulder Focus / Wide Grip)",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg",
        "instructions": [
            "Grasp a barbell with an overhand grip that is slightly less than shoulder width. The bar should be resting on the top of your thighs with your arms extended and a slight bend in your elbows. Your back should also be straight. This will be your starting position.",
            "Now exhale and use the sides of your shoulders to lift the bar, raising your elbows up and to the side. Keep the bar close to your body as you raise it. Continue to lift the bar until it nearly touches your chin. Tip: Your elbows should drive the motion, and should always be higher than your forearms. Remember to keep your torso stationary and pause for a second at the top of the movement.",
            "Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.",
            "Repeat for the recommended amount of repetitions.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Lateral Delt",
        "secondary_muscles": [
            "Anterior Delt",
            "Traps",
            "Biceps",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cable External Rotation",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/External_Rotation_with_Cable/0.jpg",
        "instructions": [
            "Adjust the cable to the same height as your elbow. Stand with your left side to the band a couple of feet away.",
            "Grasp the handle with your right hand, and keep your elbow pressed firmly to your side. We recommend you hold a pad or foam roll in place with your elbow to keep it firmly in position.",
            "With your upper arm in position, your elbow should be flexed to 90 degrees with your hand reaching across the front of your torso. This will be your starting position.",
            "Execute the movement by rotating your arm in a backhand motion, keeping your elbow in place.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Posterior Delt",
        "secondary_muscles": [
            "Lateral Delt",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
    {
        "name": "Cable Internal Rotation",
        "type": "strength",
        "photo_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Internal_Rotation/0.jpg",
        "instructions": [
            "Sit next to a low pulley sideways (with legs stretched in front of you or crossed) and grasp the single hand cable attachment with the arm nearest to the cable. Tip: If you can adjust the pulley's height, you can use a flat bench to sit on instead.",
            "Position the elbow against your side with the elbow bent at 90° and the arm pointing towards the pulley. This will be your starting position.",
            "Pull the single hand cable attachment toward your body by internally rotating your shoulder until your forearm is across your abs. You will be creating an imaginary semi-circle. Tip: The forearm should be perpendicular to your torso at all times.",
            "Slowly go back to the initial position.",
            "Repeat for the recommended amount of repetitions and then repeat the movement with the next arm.",
        ],
        "equipment": "Machine",
        "primary_muscle": "Anterior Delt",
        "secondary_muscles": [
            "Chest",
        ],
        "tracking_fields": [
            "weight",
            "reps",
            "rir",
        ],
    },
]
