"""Triceps entries for the global exercise database."""

TRICEPS_EXERCISES = [
    {
        "name": "Rope Triceps Extensions",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single Arm Triceps Extensions",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Supinated Triceps Extensions",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Forearms"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single Arm Supinated Triceps Extensions",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Straight Bar Triceps Push-Downs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Abs", "Chest", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "V-Bar Triceps Push-Downs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "D-Handle Triceps Push-Downs (Single Arm)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cross-Body Cable Triceps Extensions (Katana Extensions)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Cable Triceps Kick Backs",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Posterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Overhead Triceps Extensions",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Abs"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single Hand Overhead Triceps Extensions",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Over Head Triceps Extensions Machine",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Over Head Dumbbell Triceps Extensions",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Single Hand Over Head Dumbbell Triceps Extensions",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "French Press (Standing or Seated)",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Straight Bar Skull Crushers",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "EZ-Bar Skull Crushers",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Skull Crushers",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Straight Bar Skull Crushers",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline EZ-Bar Skull Crushers",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Incline Dumbbell Skull Crushers",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Decline Straight Bar Skull Crushers",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Decline EZ-Bar Skull Crushers",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Decline Dumbbell Skull Crushers",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": [],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Close-Grip Barbell Bench Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Close-Grip Smith Machine Press",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "JM Press (Barbell)",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Smith Machine JM Press",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Board Press (Barbell)",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Pin Press / Rack Press",
        "type": "strength",
        "equipment": "Barbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Tate Press",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dips Machine (Plate Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dips Machine (Pin Loaded)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dips (Triceps Focus)",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest", "Anterior Delt"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Weighted Dips (Triceps Focus)",
        "type": "strength",
        "equipment": "Plate",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Assisted Dips (Triceps Focus)",
        "type": "strength",
        "equipment": "Machine",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Chest", "Anterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Dumbbell Triceps Kick Backs",
        "type": "strength",
        "equipment": "Dumbbell",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Posterior Delt"],
        "tracking_fields": ["weight", "reps", "rir"],
    },
    {
        "name": "Diamond Push-Ups",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Abs", "Chest", "Anterior Delt"],
        "tracking_fields": ["reps", "rir"],
    },
    {
        "name": "Bodyweight Triceps Extensions (Tiger-Bend Push-Ups)",
        "type": "strength",
        "equipment": "None",
        "primary_muscle": "Triceps",
        "secondary_muscles": ["Abs"],
        "tracking_fields": ["reps", "rir"],
    }
]