"""Beef & Pork entries for the global food database."""

BEEF_AND_PORK = [
    {
        "name": "Fillet Mignon / Tenderloin (Beef, Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 210,
        "protein_g": 27.6,
        "carbs_g": 0.0,
        "fats_g": 10.2,
        "saturated_fats_g": 3.8,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 395.0,
        "sodium_mg": 63.0,
        "iron_mg": 2.4,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 5.2,
        "magnesium_mg": 26.0,
        "calcium_mg": 8.0,
        "cholesterol_mg": 83.0,
    },
    {
        "name": "Fillet Mignon / Tenderloin (Beef, Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 143,
        "protein_g": 21.6,
        "carbs_g": 0.0,
        "fats_g": 5.6,
        "saturated_fats_g": 2.1,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 331.0,
        "sodium_mg": 53.0,
        "iron_mg": 1.7,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 4.0,
        "magnesium_mg": 23.0,
        "calcium_mg": 6.0,
        "cholesterol_mg": 63.0,
    },
    {
        "name": "Ground Beef (80% Lean / 20% Fat, Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 271,
        "protein_g": 24.8,
        "carbs_g": 0.0,
        "fats_g": 18.2,
        "saturated_fats_g": 6.8,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 318.0,
        "sodium_mg": 82.0,
        "iron_mg": 2.6,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 5.8,
        "magnesium_mg": 23.0,
        "calcium_mg": 23.0,
        "cholesterol_mg": 90.0,
    },
    {
        "name": "Ground Beef (80% Lean / 20% Fat, Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 254,
        "protein_g": 17.2,
        "carbs_g": 0.0,
        "fats_g": 20.0,
        "saturated_fats_g": 7.6,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 276.0,
        "sodium_mg": 66.0,
        "iron_mg": 1.9,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 4.3,
        "magnesium_mg": 18.0,
        "calcium_mg": 18.0,
        "cholesterol_mg": 71.0,
    },
    {
        "name": "Ground Beef (90% Lean / 10% Fat, Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 214,
        "protein_g": 26.6,
        "carbs_g": 0.0,
        "fats_g": 11.2,
        "saturated_fats_g": 4.5,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 354.0,
        "sodium_mg": 83.0,
        "iron_mg": 2.8,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 6.4,
        "magnesium_mg": 24.0,
        "calcium_mg": 13.0,
        "cholesterol_mg": 84.0,
    },
    {
        "name": "Ground Beef (90% Lean / 10% Fat, Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 176,
        "protein_g": 20.0,
        "carbs_g": 0.0,
        "fats_g": 10.0,
        "saturated_fats_g": 4.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 305.0,
        "sodium_mg": 65.0,
        "iron_mg": 2.1,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 4.8,
        "magnesium_mg": 20.0,
        "calcium_mg": 12.0,
        "cholesterol_mg": 65.0,
    },
    {
        "name": "Pork Chop (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 231,
        "protein_g": 27.3,
        "carbs_g": 0.0,
        "fats_g": 12.7,
        "saturated_fats_g": 4.4,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 419.0,
        "sodium_mg": 66.0,
        "iron_mg": 0.9,
        "vitamin_d_mcg": 0.7,
        "zinc_mg": 2.3,
        "magnesium_mg": 26.0,
        "calcium_mg": 17.0,
        "cholesterol_mg": 85.0,
    },
    {
        "name": "Pork Chop (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 197,
        "protein_g": 19.3,
        "carbs_g": 0.0,
        "fats_g": 12.8,
        "saturated_fats_g": 4.5,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 352.0,
        "sodium_mg": 58.0,
        "iron_mg": 0.7,
        "vitamin_d_mcg": 0.6,
        "zinc_mg": 1.7,
        "magnesium_mg": 22.0,
        "calcium_mg": 14.0,
        "cholesterol_mg": 62.0,
    },
    {
        "name": "Ribeye Steak (Beef, Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 274,
        "protein_g": 24.8,
        "carbs_g": 0.0,
        "fats_g": 18.6,
        "saturated_fats_g": 7.9,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 322.0,
        "sodium_mg": 62.0,
        "iron_mg": 2.2,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 5.9,
        "magnesium_mg": 22.0,
        "calcium_mg": 10.0,
        "cholesterol_mg": 86.0,
    },
    {
        "name": "Ribeye Steak (Beef, Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 291,
        "protein_g": 19.4,
        "carbs_g": 0.0,
        "fats_g": 23.4,
        "saturated_fats_g": 9.8,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 274.0,
        "sodium_mg": 53.0,
        "iron_mg": 1.8,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 4.6,
        "magnesium_mg": 19.0,
        "calcium_mg": 8.0,
        "cholesterol_mg": 65.0,
    },
    {
        "name": "Beef Liver (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 135,
        "protein_g": 20.4,
        "carbs_g": 3.9,
        "fats_g": 3.6,
        "saturated_fats_g": 1.2,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 313.0,
        "sodium_mg": 69.0,
        "iron_mg": 4.9,
        "vitamin_d_mcg": 1.2,
        "zinc_mg": 4.0,
        "magnesium_mg": 18.0,
        "calcium_mg": 5.0,
        "cholesterol_mg": 275.0,
    },
    {
        "name": "Beef Liver (Cooked / Pan-Fried)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 slice", "equivalent_g": 68.0},
        ],
        "calories": 175,
        "protein_g": 26.5,
        "carbs_g": 5.1,
        "fats_g": 4.7,
        "saturated_fats_g": 1.5,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 352.0,
        "sodium_mg": 77.0,
        "iron_mg": 6.2,
        "vitamin_d_mcg": 1.2,
        "zinc_mg": 5.3,
        "magnesium_mg": 21.0,
        "calcium_mg": 6.0,
        "cholesterol_mg": 381.0,
    },
]
