"""Beverages (Coffee, Tea & Sodas) entries for the global food database."""

BEVERAGES = [
    {
        "name": "Cappuccino (Whole Milk, Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "Standard Cup", "equivalent_g": 240.0},
            {"description": "Large Cup", "equivalent_g": 350.0},
        ],
        "calories": 31,
        "protein_g": 1.6,
        "carbs_g": 2.5,
        "fats_g": 1.7,
        "saturated_fats_g": 1.0,
        "fiber_g": 0.0,
        "sugar_g": 2.5,
        "potassium_mg": 85.0,
        "sodium_mg": 24.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.6,
        "zinc_mg": 0.2,
        "magnesium_mg": 6.0,
        "calcium_mg": 60.0,
        "cholesterol_mg": 5.0,
    },
    {
        "name": "Coconut Water (Pure, Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 100.0},
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 19,
        "protein_g": 0.7,
        "carbs_g": 3.7,
        "fats_g": 0.2,
        "saturated_fats_g": 0.2,
        "fiber_g": 1.1,
        "sugar_g": 2.6,
        "potassium_mg": 250.0,
        "sodium_mg": 105.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 25.0,
        "calcium_mg": 24.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Flat White (Whole Milk, Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [{"description": "Standard Cup", "equivalent_g": 180.0}],
        "calories": 48,
        "protein_g": 2.5,
        "carbs_g": 3.8,
        "fats_g": 2.6,
        "saturated_fats_g": 1.5,
        "fiber_g": 0.0,
        "sugar_g": 3.8,
        "potassium_mg": 130.0,
        "sodium_mg": 38.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.9,
        "zinc_mg": 0.3,
        "magnesium_mg": 9.0,
        "calcium_mg": 93.0,
        "cholesterol_mg": 8.0,
    },
    {
        "name": "Iced Latte (Whole Milk, Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "Standard Cup", "equivalent_g": 350.0},
            {"description": "Large Cup", "equivalent_g": 470.0},
        ],
        "calories": 35,
        "protein_g": 1.9,
        "carbs_g": 2.8,
        "fats_g": 1.9,
        "saturated_fats_g": 1.1,
        "fiber_g": 0.0,
        "sugar_g": 2.8,
        "potassium_mg": 95.0,
        "sodium_mg": 28.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.7,
        "zinc_mg": 0.2,
        "magnesium_mg": 7.0,
        "calcium_mg": 68.0,
        "cholesterol_mg": 6.0,
    },
    {
        "name": "Latte (Whole Milk, Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "Standard Cup", "equivalent_g": 240.0},
            {"description": "Large Cup", "equivalent_g": 350.0},
        ],
        "calories": 42,
        "protein_g": 2.2,
        "carbs_g": 3.4,
        "fats_g": 2.3,
        "saturated_fats_g": 1.3,
        "fiber_g": 0.0,
        "sugar_g": 3.4,
        "potassium_mg": 115.0,
        "sodium_mg": 33.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.8,
        "zinc_mg": 0.3,
        "magnesium_mg": 8.0,
        "calcium_mg": 82.0,
        "cholesterol_mg": 7.0,
    },
]
