"""Bread entries for the global food database."""

BREAD = [
    {
        "name": "Integral / Whole Wheat Bread",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 slice", "equivalent_g": 28.0},
        ],
        "calories": 252,
        "protein_g": 12.5,
        "carbs_g": 42.7,
        "fats_g": 3.5,
        "saturated_fats_g": 0.7,
        "fiber_g": 6.0,
        "sugar_g": 4.3,
        "potassium_mg": 254.0,
        "sodium_mg": 400.0,
        "iron_mg": 2.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.8,
        "magnesium_mg": 76.0,
        "calcium_mg": 161.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "White Bread (Commercially Prepared)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 slice", "equivalent_g": 25.0},
        ],
        "calories": 266,
        "protein_g": 8.8,
        "carbs_g": 50.6,
        "fats_g": 3.3,
        "saturated_fats_g": 0.7,
        "fiber_g": 2.7,
        "sugar_g": 5.7,
        "potassium_mg": 131.0,
        "sodium_mg": 495.0,
        "iron_mg": 3.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.8,
        "magnesium_mg": 25.0,
        "calcium_mg": 260.0,
        "cholesterol_mg": 0.0,
    },
]
