"""Condiments, Sauces & Oils entries for the global food database."""

CONDIMENTS_SAUCES_AND_OILS = [
    {
        "name": "Capers (Canned / Brined, Drained)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 138.0},
        ],
        "calories": 23,
        "protein_g": 2.4,
        "carbs_g": 4.9,
        "fats_g": 0.9,
        "saturated_fats_g": 0.2,
        "fiber_g": 3.2,
        "sugar_g": 0.4,
        "potassium_mg": 40.0,
        "sodium_mg": 2964.0,
        "iron_mg": 1.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 33.0,
        "calcium_mg": 40.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Heinz Ketchup (50% Less Sugar & Salt, EU Formulation)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 240.0},
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 57,
        "protein_g": 1.4,
        "carbs_g": 12.0,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.0,
        "sugar_g": 11.0,
        "potassium_mg": 350.0,
        "sodium_mg": 450.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 15.0,
        "calcium_mg": 16.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Heinz Ketchup (Classic, EU Formulation)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 240.0},
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 102,
        "protein_g": 1.2,
        "carbs_g": 23.2,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.9,
        "sugar_g": 22.8,
        "potassium_mg": 300.0,
        "sodium_mg": 900.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 15.0,
        "calcium_mg": 16.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Mustard (Yellow / Generic)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 240.0},
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 60,
        "protein_g": 3.8,
        "carbs_g": 5.8,
        "fats_g": 2.8,
        "saturated_fats_g": 0.2,
        "fiber_g": 2.9,
        "sugar_g": 0.9,
        "potassium_mg": 135.0,
        "sodium_mg": 1100.0,
        "iron_mg": 1.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.6,
        "magnesium_mg": 49.0,
        "calcium_mg": 58.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Olive Oil (Extra Virgin)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "100ml", "equivalent_g": 92.0},
            {"description": "1 tablespoon", "equivalent_g": 14.0},
            {"description": "1 teaspoon", "equivalent_g": 4.5},
        ],
        "calories": 884,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fats_g": 100.0,
        "saturated_fats_g": 13.8,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 1.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 1.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Peanut Butter (Natural, Creamy)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 258.0},
            {"description": "1 tablespoon", "equivalent_g": 16.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 588,
        "protein_g": 25.1,
        "carbs_g": 20.0,
        "fats_g": 50.4,
        "saturated_fats_g": 10.3,
        "fiber_g": 6.0,
        "sugar_g": 9.2,
        "potassium_mg": 649.0,
        "sodium_mg": 17.0,
        "iron_mg": 1.9,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 2.9,
        "magnesium_mg": 154.0,
        "calcium_mg": 43.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Soy Sauce",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 250.0},
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 53,
        "protein_g": 8.0,
        "carbs_g": 4.9,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.8,
        "sugar_g": 0.4,
        "potassium_mg": 212.0,
        "sodium_mg": 5493.0,
        "iron_mg": 2.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.4,
        "magnesium_mg": 40.0,
        "calcium_mg": 20.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Sriracha Sauce",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 240.0},
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 80,
        "protein_g": 1.8,
        "carbs_g": 16.0,
        "fats_g": 0.5,
        "saturated_fats_g": 0.1,
        "fiber_g": 1.2,
        "sugar_g": 10.0,
        "potassium_mg": 260.0,
        "sodium_mg": 1900.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 16.0,
        "calcium_mg": 14.0,
        "cholesterol_mg": 0.0,
    },
]
