"""Condiments, Sauces & Oils entries for the global food database."""

CONDIMENTS_SAUCES_AND_OILS = [
    {
        "name": "Capers (Canned / Brined, Drained)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 138.0},
        ],
        "calories": 23,
        "protein_g": 2.4,
        "carbs_g": 4.9,
        "fats_g": 0.9,
        "saturated_fats_g": 0.2,
        "fiber_g": 3.2,
        "sugar_g": 0.4,
        "potassium_mg": 40.0,
        "sodium_mg": 2964.0,
        "iron_mg": 1.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 33.0,
        "calcium_mg": 40.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Heinz Ketchup (50% Less Sugar & Salt, EU Formulation)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 240.0},
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 57,
        "protein_g": 1.4,
        "carbs_g": 12.0,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.0,
        "sugar_g": 11.0,
        "potassium_mg": 350.0,
        "sodium_mg": 450.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 15.0,
        "calcium_mg": 16.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Heinz Ketchup (Classic, EU Formulation)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 240.0},
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 102,
        "protein_g": 1.2,
        "carbs_g": 23.2,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.9,
        "sugar_g": 22.8,
        "potassium_mg": 300.0,
        "sodium_mg": 900.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 15.0,
        "calcium_mg": 16.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Mustard (Yellow / Generic)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 240.0},
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 60,
        "protein_g": 3.8,
        "carbs_g": 5.8,
        "fats_g": 2.8,
        "saturated_fats_g": 0.2,
        "fiber_g": 2.9,
        "sugar_g": 0.9,
        "potassium_mg": 135.0,
        "sodium_mg": 1100.0,
        "iron_mg": 1.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.6,
        "magnesium_mg": 49.0,
        "calcium_mg": 58.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Olive Oil (Extra Virgin)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "100ml", "equivalent_g": 92.0},
            {"description": "1 tablespoon", "equivalent_g": 14.0},
            {"description": "1 teaspoon", "equivalent_g": 4.5},
        ],
        "calories": 884,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fats_g": 100.0,
        "saturated_fats_g": 13.8,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 1.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 1.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Peanut Butter (Natural, Creamy)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 258.0},
            {"description": "1 tablespoon", "equivalent_g": 16.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 588,
        "protein_g": 25.1,
        "carbs_g": 20.0,
        "fats_g": 50.4,
        "saturated_fats_g": 10.3,
        "fiber_g": 6.0,
        "sugar_g": 9.2,
        "potassium_mg": 649.0,
        "sodium_mg": 17.0,
        "iron_mg": 1.9,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 2.9,
        "magnesium_mg": 154.0,
        "calcium_mg": 43.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Soy Sauce",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 250.0},
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 53,
        "protein_g": 8.0,
        "carbs_g": 4.9,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.8,
        "sugar_g": 0.4,
        "potassium_mg": 212.0,
        "sodium_mg": 5493.0,
        "iron_mg": 2.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.4,
        "magnesium_mg": 40.0,
        "calcium_mg": 20.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Sriracha Sauce",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 240.0},
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 80,
        "protein_g": 1.8,
        "carbs_g": 16.0,
        "fats_g": 0.5,
        "saturated_fats_g": 0.1,
        "fiber_g": 1.2,
        "sugar_g": 10.0,
        "potassium_mg": 260.0,
        "sodium_mg": 1900.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 16.0,
        "calcium_mg": 14.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Avocado Oil",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 14.0},
            {"description": "1 teaspoon", "equivalent_g": 4.5},
        ],
        "calories": 884,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fats_g": 100.0,
        "saturated_fats_g": 11.6,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 0.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 0.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Coconut Oil",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 14.0},
            {"description": "1 teaspoon", "equivalent_g": 4.5},
        ],
        "calories": 862,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fats_g": 100.0,
        "saturated_fats_g": 86.5,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 0.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 0.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Canola Oil / Rapeseed Oil",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 14.0},
            {"description": "1 teaspoon", "equivalent_g": 4.5},
        ],
        "calories": 884,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fats_g": 100.0,
        "saturated_fats_g": 7.3,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 0.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 0.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Sunflower Oil",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 14.0},
            {"description": "1 teaspoon", "equivalent_g": 4.5},
        ],
        "calories": 884,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fats_g": 100.0,
        "saturated_fats_g": 13.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 0.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 0.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Sesame Oil (Toasted)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 14.0},
            {"description": "1 teaspoon", "equivalent_g": 4.5},
        ],
        "calories": 884,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fats_g": 100.0,
        "saturated_fats_g": 14.2,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 0.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 0.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Vegetable Oil (Generic Blend)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 14.0},
            {"description": "1 teaspoon", "equivalent_g": 4.5},
        ],
        "calories": 884,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fats_g": 100.0,
        "saturated_fats_g": 14.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 0.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 0.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Mayonnaise (Full Fat)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 14.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 680,
        "protein_g": 1.0,
        "carbs_g": 0.6,
        "fats_g": 75.0,
        "saturated_fats_g": 12.0,
        "fiber_g": 0.0,
        "sugar_g": 0.6,
        "potassium_mg": 20.0,
        "sodium_mg": 635.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 2.0,
        "calcium_mg": 8.0,
        "cholesterol_mg": 42.0,
    },
    {
        "name": "Mayonnaise (Light / Low Fat)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 270,
        "protein_g": 0.8,
        "carbs_g": 11.0,
        "fats_g": 25.0,
        "saturated_fats_g": 4.0,
        "fiber_g": 0.0,
        "sugar_g": 4.0,
        "potassium_mg": 30.0,
        "sodium_mg": 700.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 2.0,
        "calcium_mg": 10.0,
        "cholesterol_mg": 25.0,
    },
    {
        "name": "BBQ Sauce (Classic)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 17.0},
        ],
        "calories": 160,
        "protein_g": 0.8,
        "carbs_g": 38.0,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.6,
        "sugar_g": 33.0,
        "potassium_mg": 220.0,
        "sodium_mg": 1020.0,
        "iron_mg": 0.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 13.0,
        "calcium_mg": 25.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Oyster Sauce",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 18.0},
            {"description": "1 teaspoon", "equivalent_g": 6.0},
        ],
        "calories": 51,
        "protein_g": 1.2,
        "carbs_g": 10.9,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.3,
        "sugar_g": 8.0,
        "potassium_mg": 55.0,
        "sodium_mg": 2730.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 8.0,
        "calcium_mg": 12.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Hoisin Sauce",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 16.0},
            {"description": "1 teaspoon", "equivalent_g": 5.3},
        ],
        "calories": 220,
        "protein_g": 1.5,
        "carbs_g": 50.0,
        "fats_g": 1.5,
        "saturated_fats_g": 0.2,
        "fiber_g": 1.2,
        "sugar_g": 35.0,
        "potassium_mg": 120.0,
        "sodium_mg": 1500.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 15.0,
        "calcium_mg": 20.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Teriyaki Sauce",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 18.0},
        ],
        "calories": 89,
        "protein_g": 6.0,
        "carbs_g": 15.6,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.1,
        "sugar_g": 14.0,
        "potassium_mg": 210.0,
        "sodium_mg": 3830.0,
        "iron_mg": 1.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.4,
        "magnesium_mg": 35.0,
        "calcium_mg": 18.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Fish Sauce",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 18.0},
            {"description": "1 teaspoon", "equivalent_g": 6.0},
        ],
        "calories": 35,
        "protein_g": 5.0,
        "carbs_g": 3.6,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 3.6,
        "potassium_mg": 288.0,
        "sodium_mg": 7850.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 175.0,
        "calcium_mg": 43.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Sweet Chili Sauce",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 18.0},
        ],
        "calories": 185,
        "protein_g": 0.4,
        "carbs_g": 45.0,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.5,
        "sugar_g": 40.0,
        "potassium_mg": 90.0,
        "sodium_mg": 1200.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 8.0,
        "calcium_mg": 10.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Worcestershire Sauce",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 17.0},
            {"description": "1 teaspoon", "equivalent_g": 5.7},
        ],
        "calories": 78,
        "protein_g": 0.8,
        "carbs_g": 18.0,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 10.0,
        "potassium_mg": 170.0,
        "sodium_mg": 980.0,
        "iron_mg": 5.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 13.0,
        "calcium_mg": 108.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Apple Cider Vinegar",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 15.0},
        ],
        "calories": 21,
        "protein_g": 0.0,
        "carbs_g": 0.9,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 0.4,
        "potassium_mg": 73.0,
        "sodium_mg": 5.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 5.0,
        "calcium_mg": 7.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Balsamic Vinegar",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 16.0},
        ],
        "calories": 88,
        "protein_g": 0.5,
        "carbs_g": 17.0,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 15.0,
        "potassium_mg": 112.0,
        "sodium_mg": 23.0,
        "iron_mg": 0.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 12.0,
        "calcium_mg": 27.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "White Vinegar (Distilled)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 15.0},
        ],
        "calories": 18,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 2.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 1.0,
        "calcium_mg": 6.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Rice Vinegar (Unseasoned)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 15.0},
        ],
        "calories": 18,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 5.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 1.0,
        "calcium_mg": 2.0,
        "cholesterol_mg": 0.0,
    },
]
