"""Dairy & Milk Alternatives entries for the global food database."""

DAIRY = [
    {
        "name": "Almond Milk (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 15,
        "protein_g": 0.5,
        "carbs_g": 0.3,
        "fats_g": 1.2,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.2,
        "sugar_g": 0.0,
        "potassium_mg": 67.0,
        "sodium_mg": 73.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 1.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 6.0,
        "calcium_mg": 184.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Coconut Milk (Unsweetened Beverage)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 20,
        "protein_g": 0.2,
        "carbs_g": 0.6,
        "fats_g": 2.1,
        "saturated_fats_g": 1.9,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 19.0,
        "sodium_mg": 16.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 1.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 4.0,
        "calcium_mg": 188.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Greek Yogurt (0% Fat, Plain)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 245.0},
        ],
        "calories": 59,
        "protein_g": 10.3,
        "carbs_g": 3.6,
        "fats_g": 0.4,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.0,
        "sugar_g": 3.2,
        "potassium_mg": 141.0,
        "sodium_mg": 36.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 11.0,
        "calcium_mg": 110.0,
        "cholesterol_mg": 5.0,
    },
    {
        "name": "Greek Yogurt (10% Fat, Plain)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 245.0},
        ],
        "calories": 130,
        "protein_g": 9.0,
        "carbs_g": 4.0,
        "fats_g": 10.0,
        "saturated_fats_g": 6.5,
        "fiber_g": 0.0,
        "sugar_g": 3.5,
        "potassium_mg": 130.0,
        "sodium_mg": 32.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 0.6,
        "magnesium_mg": 10.0,
        "calcium_mg": 100.0,
        "cholesterol_mg": 35.0,
    },
    {
        "name": "Greek Yogurt (2% Fat, Plain)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 245.0},
        ],
        "calories": 73,
        "protein_g": 9.9,
        "carbs_g": 3.9,
        "fats_g": 1.9,
        "saturated_fats_g": 1.1,
        "fiber_g": 0.0,
        "sugar_g": 3.6,
        "potassium_mg": 135.0,
        "sodium_mg": 34.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.6,
        "magnesium_mg": 11.0,
        "calcium_mg": 105.0,
        "cholesterol_mg": 10.0,
    },
    {
        "name": "Milk (1.5% Fat, Low-Fat)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 244.0},
        ],
        "calories": 47,
        "protein_g": 3.3,
        "carbs_g": 5.0,
        "fats_g": 1.5,
        "saturated_fats_g": 0.9,
        "fiber_g": 0.0,
        "sugar_g": 5.0,
        "potassium_mg": 150.0,
        "sodium_mg": 44.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 1.1,
        "zinc_mg": 0.4,
        "magnesium_mg": 11.0,
        "calcium_mg": 120.0,
        "cholesterol_mg": 5.0,
    },
    {
        "name": "Milk (3.5% Fat, Whole)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 244.0},
        ],
        "calories": 61,
        "protein_g": 3.2,
        "carbs_g": 4.8,
        "fats_g": 3.3,
        "saturated_fats_g": 1.9,
        "fiber_g": 0.0,
        "sugar_g": 4.8,
        "potassium_mg": 132.0,
        "sodium_mg": 43.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 1.2,
        "zinc_mg": 0.4,
        "magnesium_mg": 10.0,
        "calcium_mg": 113.0,
        "cholesterol_mg": 10.0,
    },
    {
        "name": "Parmigiano Reggiano (Cheese)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 100.0},
        ],
        "calories": 392,
        "protein_g": 35.8,
        "carbs_g": 3.2,
        "fats_g": 25.8,
        "saturated_fats_g": 16.4,
        "fiber_g": 0.0,
        "sugar_g": 0.8,
        "potassium_mg": 92.0,
        "sodium_mg": 1529.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 0.5,
        "zinc_mg": 2.8,
        "magnesium_mg": 44.0,
        "calcium_mg": 1109.0,
        "cholesterol_mg": 68.0,
    },
    {
        "name": "Soy Milk (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 33,
        "protein_g": 2.8,
        "carbs_g": 1.8,
        "fats_g": 1.5,
        "saturated_fats_g": 0.2,
        "fiber_g": 0.4,
        "sugar_g": 0.4,
        "potassium_mg": 118.0,
        "sodium_mg": 51.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 1.1,
        "zinc_mg": 0.2,
        "magnesium_mg": 15.0,
        "calcium_mg": 123.0,
        "cholesterol_mg": 0.0,
    },
]
