"""Dairy & Milk Alternatives entries for the global food database."""

DAIRY = [
    {
        "name": "Almond Milk (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 15,
        "protein_g": 0.5,
        "carbs_g": 0.3,
        "fats_g": 1.2,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.2,
        "sugar_g": 0.0,
        "potassium_mg": 67.0,
        "sodium_mg": 73.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 1.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 6.0,
        "calcium_mg": 184.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Coconut Milk (Unsweetened Beverage)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 20,
        "protein_g": 0.2,
        "carbs_g": 0.6,
        "fats_g": 2.1,
        "saturated_fats_g": 1.9,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 19.0,
        "sodium_mg": 16.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 1.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 4.0,
        "calcium_mg": 188.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Greek Yogurt (0% Fat, Plain)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 245.0},
        ],
        "calories": 59,
        "protein_g": 10.3,
        "carbs_g": 3.6,
        "fats_g": 0.4,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.0,
        "sugar_g": 3.2,
        "potassium_mg": 141.0,
        "sodium_mg": 36.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 11.0,
        "calcium_mg": 110.0,
        "cholesterol_mg": 5.0,
    },
    {
        "name": "Greek Yogurt (10% Fat, Plain)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 245.0},
        ],
        "calories": 130,
        "protein_g": 9.0,
        "carbs_g": 4.0,
        "fats_g": 10.0,
        "saturated_fats_g": 6.5,
        "fiber_g": 0.0,
        "sugar_g": 3.5,
        "potassium_mg": 130.0,
        "sodium_mg": 32.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 0.6,
        "magnesium_mg": 10.0,
        "calcium_mg": 100.0,
        "cholesterol_mg": 35.0,
    },
    {
        "name": "Greek Yogurt (2% Fat, Plain)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 245.0},
        ],
        "calories": 73,
        "protein_g": 9.9,
        "carbs_g": 3.9,
        "fats_g": 1.9,
        "saturated_fats_g": 1.1,
        "fiber_g": 0.0,
        "sugar_g": 3.6,
        "potassium_mg": 135.0,
        "sodium_mg": 34.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.6,
        "magnesium_mg": 11.0,
        "calcium_mg": 105.0,
        "cholesterol_mg": 10.0,
    },
    {
        "name": "Milk (1.5% Fat, Low-Fat)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 244.0},
        ],
        "calories": 47,
        "protein_g": 3.3,
        "carbs_g": 5.0,
        "fats_g": 1.5,
        "saturated_fats_g": 0.9,
        "fiber_g": 0.0,
        "sugar_g": 5.0,
        "potassium_mg": 150.0,
        "sodium_mg": 44.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 1.1,
        "zinc_mg": 0.4,
        "magnesium_mg": 11.0,
        "calcium_mg": 120.0,
        "cholesterol_mg": 5.0,
    },
    {
        "name": "Milk (3.5% Fat, Whole)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 244.0},
        ],
        "calories": 61,
        "protein_g": 3.2,
        "carbs_g": 4.8,
        "fats_g": 3.3,
        "saturated_fats_g": 1.9,
        "fiber_g": 0.0,
        "sugar_g": 4.8,
        "potassium_mg": 132.0,
        "sodium_mg": 43.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 1.2,
        "zinc_mg": 0.4,
        "magnesium_mg": 10.0,
        "calcium_mg": 113.0,
        "cholesterol_mg": 10.0,
    },
    {
        "name": "Parmigiano Reggiano (Cheese)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 100.0},
        ],
        "calories": 392,
        "protein_g": 35.8,
        "carbs_g": 3.2,
        "fats_g": 25.8,
        "saturated_fats_g": 16.4,
        "fiber_g": 0.0,
        "sugar_g": 0.8,
        "potassium_mg": 92.0,
        "sodium_mg": 1529.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 0.5,
        "zinc_mg": 2.8,
        "magnesium_mg": 44.0,
        "calcium_mg": 1109.0,
        "cholesterol_mg": 68.0,
    },
    {
        "name": "Soy Milk (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 33,
        "protein_g": 2.8,
        "carbs_g": 1.8,
        "fats_g": 1.5,
        "saturated_fats_g": 0.2,
        "fiber_g": 0.4,
        "sugar_g": 0.4,
        "potassium_mg": 118.0,
        "sodium_mg": 51.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 1.1,
        "zinc_mg": 0.2,
        "magnesium_mg": 15.0,
        "calcium_mg": 123.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Butter (Salted)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 14.0},
            {"description": "1 pat / cube", "equivalent_g": 5.0},
        ],
        "calories": 717,
        "protein_g": 0.8,
        "carbs_g": 0.1,
        "fats_g": 81.1,
        "saturated_fats_g": 51.4,
        "fiber_g": 0.0,
        "sugar_g": 0.1,
        "potassium_mg": 24.0,
        "sodium_mg": 643.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 1.5,
        "zinc_mg": 0.1,
        "magnesium_mg": 2.0,
        "calcium_mg": 24.0,
        "cholesterol_mg": 215.0,
    },
    {
        "name": "Butter (Unsalted)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 14.0},
            {"description": "1 pat / cube", "equivalent_g": 5.0},
        ],
        "calories": 717,
        "protein_g": 0.8,
        "carbs_g": 0.1,
        "fats_g": 81.1,
        "saturated_fats_g": 51.4,
        "fiber_g": 0.0,
        "sugar_g": 0.1,
        "potassium_mg": 24.0,
        "sodium_mg": 11.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 1.5,
        "zinc_mg": 0.1,
        "magnesium_mg": 2.0,
        "calcium_mg": 24.0,
        "cholesterol_mg": 215.0,
    },
    {
        "name": "Ghee (Clarified Butter)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 14.0},
        ],
        "calories": 900,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fats_g": 100.0,
        "saturated_fats_g": 62.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 0.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 0.0,
        "cholesterol_mg": 256.0,
    },
    {
        "name": "Milk (0% Fat, Skim)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 245.0},
        ],
        "calories": 35,
        "protein_g": 3.4,
        "carbs_g": 5.0,
        "fats_g": 0.1,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.0,
        "sugar_g": 5.0,
        "potassium_mg": 156.0,
        "sodium_mg": 42.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 1.2,
        "zinc_mg": 0.4,
        "magnesium_mg": 11.0,
        "calcium_mg": 122.0,
        "cholesterol_mg": 2.0,
    },
    {
        "name": "Oat Milk (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 42,
        "protein_g": 0.8,
        "carbs_g": 6.8,
        "fats_g": 1.5,         "saturated_fats_g": 0.2,
        "fiber_g": 0.8,
        "sugar_g": 3.0,
        "potassium_mg": 162.0,
        "sodium_mg": 48.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.8,
        "zinc_mg": 0.1,
        "magnesium_mg": 4.0,
        "calcium_mg": 145.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Cashew Milk (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 10,
        "protein_g": 0.4,
        "carbs_g": 0.4,
        "fats_g": 0.8,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 16.0,
        "sodium_mg": 66.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 1.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 5.0,
        "calcium_mg": 187.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Macadamia Milk (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 21,
        "protein_g": 0.4,
        "carbs_g": 0.4,
        "fats_g": 2.1,
        "saturated_fats_g": 0.4,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 0.0,
        "sodium_mg": 43.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 1.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 187.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Pea Milk (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "100g", "equivalent_g": 103.0},
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 29,
        "protein_g": 3.3,
        "carbs_g": 0.0,
        "fats_g": 1.8,
        "saturated_fats_g": 0.2,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 187.0,
        "sodium_mg": 45.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 1.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 187.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Heavy Cream / Whipping Cream (36% Fat)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 cup", "equivalent_g": 238.0},
        ],
        "calories": 340,
        "protein_g": 2.8,
        "carbs_g": 2.8,
        "fats_g": 36.1,
        "saturated_fats_g": 23.0,
        "fiber_g": 0.0,
        "sugar_g": 2.8,
        "potassium_mg": 75.0,
        "sodium_mg": 38.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.8,
        "zinc_mg": 0.3,
        "magnesium_mg": 7.0,
        "calcium_mg": 65.0,
        "cholesterol_mg": 137.0,
    },
    {
        "name": "Telemea Cheese (Cow's Milk)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 slice", "equivalent_g": 30.0},
        ],
        "calories": 273,
        "protein_g": 14.5,
        "carbs_g": 1.0,
        "fats_g": 23.0,
        "saturated_fats_g": 15.0,
        "fiber_g": 0.0,
        "sugar_g": 1.0,
        "potassium_mg": 90.0,
        "sodium_mg": 1500.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.5,
        "zinc_mg": 2.5,
        "magnesium_mg": 20.0,
        "calcium_mg": 400.0,
        "cholesterol_mg": 70.0,
    },
    {
        "name": "Kefir (3.5% Fat)",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 240.0},
        ],
        "calories": 62,
        "protein_g": 3.3,
        "carbs_g": 4.5,
        "fats_g": 3.5,
        "saturated_fats_g": 2.2,
        "fiber_g": 0.0,
        "sugar_g": 4.5,
        "potassium_mg": 150.0,
        "sodium_mg": 40.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 1.0,
        "zinc_mg": 0.4,
        "magnesium_mg": 12.0,
        "calcium_mg": 120.0,
        "cholesterol_mg": 13.0,
    },
    {
        "name": "Feta Cheese",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup (crumbled)", "equivalent_g": 150.0},
            {"description": "1 slice", "equivalent_g": 38.0},
        ],
        "calories": 264,
        "protein_g": 14.2,
        "carbs_g": 4.1,
        "fats_g": 21.3,
        "saturated_fats_g": 15.0,
        "fiber_g": 0.0,
        "sugar_g": 4.1,
        "potassium_mg": 62.0,
        "sodium_mg": 1116.0,
        "iron_mg": 0.7,
        "vitamin_d_mcg": 0.4,
        "zinc_mg": 2.9,
        "magnesium_mg": 19.0,
        "calcium_mg": 493.0,
        "cholesterol_mg": 89.0,
    },
    {
        "name": "Mozzarella Cheese (Whole Milk / Full Fat)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup (shredded)", "equivalent_g": 112.0},
            {"description": "1 slice", "equivalent_g": 28.0},
        ],
        "calories": 300,
        "protein_g": 22.2,
        "carbs_g": 2.2,
        "fats_g": 22.4,
        "saturated_fats_g": 13.2,
        "fiber_g": 0.0,
        "sugar_g": 1.0,
        "potassium_mg": 76.0,
        "sodium_mg": 627.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.4,
        "zinc_mg": 2.9,
        "magnesium_mg": 20.0,
        "calcium_mg": 505.0,
        "cholesterol_mg": 79.0,
    },
    {
        "name": "Mozzarella Cheese (Part-Skim / Light)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup (shredded)", "equivalent_g": 112.0},
            {"description": "1 slice", "equivalent_g": 28.0},
        ],
        "calories": 254,
        "protein_g": 24.3,
        "carbs_g": 2.8,
        "fats_g": 15.9,
        "saturated_fats_g": 10.1,
        "fiber_g": 0.0,
        "sugar_g": 1.2,
        "potassium_mg": 84.0,
        "sodium_mg": 619.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.3,
        "zinc_mg": 2.8,
        "magnesium_mg": 23.0,
        "calcium_mg": 782.0,
        "cholesterol_mg": 54.0,
    },
    {
        "name": "Gouda Cheese",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 slice", "equivalent_g": 28.0},
        ],
        "calories": 356,
        "protein_g": 24.9,
        "carbs_g": 2.2,
        "fats_g": 27.4,
        "saturated_fats_g": 17.6,
        "fiber_g": 0.0,
        "sugar_g": 2.2,
        "potassium_mg": 121.0,
        "sodium_mg": 819.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.5,
        "zinc_mg": 3.9,
        "magnesium_mg": 29.0,
        "calcium_mg": 700.0,
        "cholesterol_mg": 114.0,
    },
    {
        "name": "Cheddar Cheese",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup (shredded)", "equivalent_g": 113.0},
            {"description": "1 slice", "equivalent_g": 28.0},
        ],
        "calories": 403,
        "protein_g": 22.9,
        "carbs_g": 3.1,
        "fats_g": 33.8,
        "saturated_fats_g": 19.4,
        "fiber_g": 0.0,
        "sugar_g": 0.5,
        "potassium_mg": 76.0,
        "sodium_mg": 653.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.6,
        "zinc_mg": 3.1,
        "magnesium_mg": 28.0,
        "calcium_mg": 710.0,
        "cholesterol_mg": 99.0,
    },
    {
        "name": "Cottage Cheese (2% Low Fat)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 226.0},
        ],
        "calories": 81,
        "protein_g": 10.4,
        "carbs_g": 4.8,
        "fats_g": 2.3,
        "saturated_fats_g": 0.9,
        "fiber_g": 0.0,
        "sugar_g": 4.1,
        "potassium_mg": 125.0,
        "sodium_mg": 308.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.4,
        "magnesium_mg": 8.0,
        "calcium_mg": 111.0,
        "cholesterol_mg": 12.0,
    },
]
