"""Eggs entries for the global food database."""

EGGS = [
    {
        "name": "Egg Whites (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 243.0},
            {"description": "1 large", "equivalent_g": 33.0},
        ],
        "calories": 52,
        "protein_g": 10.9,
        "carbs_g": 0.7,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 0.7,
        "potassium_mg": 163.0,
        "sodium_mg": 166.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 11.0,
        "calcium_mg": 7.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Egg Yolks (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 yolk", "equivalent_g": 17.0},
        ],
        "calories": 322,
        "protein_g": 15.9,
        "carbs_g": 3.6,
        "fats_g": 26.5,
        "saturated_fats_g": 9.6,
        "fiber_g": 0.0,
        "sugar_g": 0.6,
        "potassium_mg": 109.0,
        "sodium_mg": 48.0,
        "iron_mg": 2.7,
        "vitamin_d_mcg": 5.4,
        "zinc_mg": 2.3,
        "magnesium_mg": 5.0,
        "calcium_mg": 129.0,
        "cholesterol_mg": 1085.0,
    },
    {
        "name": "Whole Eggs (Boiled / Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 large", "equivalent_g": 50.0},
            {"description": "1 medium", "equivalent_g": 44.0},
            {"description": "1 small", "equivalent_g": 38.0},
        ],
        "calories": 155,
        "protein_g": 12.6,
        "carbs_g": 1.1,
        "fats_g": 10.6,
        "saturated_fats_g": 3.3,
        "fiber_g": 0.0,
        "sugar_g": 1.1,
        "potassium_mg": 126.0,
        "sodium_mg": 124.0,
        "iron_mg": 1.2,
        "vitamin_d_mcg": 2.2,
        "zinc_mg": 1.0,
        "magnesium_mg": 10.0,
        "calcium_mg": 50.0,
        "cholesterol_mg": 373.0,
    },
    {
        "name": "Whole Eggs (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 large", "equivalent_g": 50.0},
            {"description": "1 medium", "equivalent_g": 44.0},
            {"description": "1 small", "equivalent_g": 38.0},
        ],
        "calories": 143,
        "protein_g": 12.6,
        "carbs_g": 0.7,
        "fats_g": 9.5,
        "saturated_fats_g": 3.1,
        "fiber_g": 0.0,
        "sugar_g": 0.4,
        "potassium_mg": 138.0,
        "sodium_mg": 142.0,
        "iron_mg": 1.8,
        "vitamin_d_mcg": 2.0,
        "zinc_mg": 1.3,
        "magnesium_mg": 12.0,
        "calcium_mg": 56.0,
        "cholesterol_mg": 372.0,
    },
]
