"""Fish & Seafood entries for the global food database."""

FISH_AND_SEAFOOD = [
    {
        "name": "Bream (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 120.0},
        ],
        "calories": 135,
        "protein_g": 25.3,
        "carbs_g": 0.0,
        "fats_g": 3.0,
        "saturated_fats_g": 0.7,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 504.0,
        "sodium_mg": 87.0,
        "iron_mg": 0.5,
        "vitamin_d_mcg": 8.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 36.0,
        "calcium_mg": 33.0,
        "cholesterol_mg": 65.0,
    },
    {
        "name": "Bream (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 140.0},
        ],
        "calories": 105,
        "protein_g": 19.7,
        "carbs_g": 0.0,
        "fats_g": 2.3,
        "saturated_fats_g": 0.5,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 393.0,
        "sodium_mg": 68.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 6.2,
        "zinc_mg": 0.4,
        "magnesium_mg": 28.0,
        "calcium_mg": 26.0,
        "cholesterol_mg": 51.0,
    },
    {
        "name": "Canned Tuna (In Water, Drained)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 90,
        "protein_g": 19.4,
        "carbs_g": 0.0,
        "fats_g": 0.8,
        "saturated_fats_g": 0.2,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 175.0,
        "sodium_mg": 247.0,
        "iron_mg": 1.6,
        "vitamin_d_mcg": 1.4,
        "zinc_mg": 0.7,
        "magnesium_mg": 27.0,
        "calcium_mg": 11.0,
        "cholesterol_mg": 36.0,
    },
    {
        "name": "Cod (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 135.0},
        ],
        "calories": 105,
        "protein_g": 22.8,
        "carbs_g": 0.0,
        "fats_g": 0.9,
        "saturated_fats_g": 0.2,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 502.0,
        "sodium_mg": 78.0,
        "iron_mg": 0.5,
        "vitamin_d_mcg": 1.1,
        "zinc_mg": 0.5,
        "magnesium_mg": 38.0,
        "calcium_mg": 15.0,
        "cholesterol_mg": 55.0,
    },
    {
        "name": "Cod (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 150.0},
        ],
        "calories": 82,
        "protein_g": 17.8,
        "carbs_g": 0.0,
        "fats_g": 0.7,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 413.0,
        "sodium_mg": 54.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.9,
        "zinc_mg": 0.4,
        "magnesium_mg": 32.0,
        "calcium_mg": 16.0,
        "cholesterol_mg": 43.0,
    },
    {
        "name": "Haddock (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 135.0},
        ],
        "calories": 112,
        "protein_g": 24.2,
        "carbs_g": 0.0,
        "fats_g": 0.9,
        "saturated_fats_g": 0.2,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 349.0,
        "sodium_mg": 87.0,
        "iron_mg": 1.3,
        "vitamin_d_mcg": 0.8,
        "zinc_mg": 0.4,
        "magnesium_mg": 26.0,
        "calcium_mg": 42.0,
        "cholesterol_mg": 74.0,
    },
    {
        "name": "Haddock (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 150.0},
        ],
        "calories": 87,
        "protein_g": 18.9,
        "carbs_g": 0.0,
        "fats_g": 0.7,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 351.0,
        "sodium_mg": 68.0,
        "iron_mg": 1.0,
        "vitamin_d_mcg": 0.6,
        "zinc_mg": 0.4,
        "magnesium_mg": 21.0,
        "calcium_mg": 14.0,
        "cholesterol_mg": 57.0,
    },
    {
        "name": "Perch (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 110.0},
        ],
        "calories": 117,
        "protein_g": 24.9,
        "carbs_g": 0.0,
        "fats_g": 1.2,
        "saturated_fats_g": 0.2,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 345.0,
        "sodium_mg": 79.0,
        "iron_mg": 1.2,
        "vitamin_d_mcg": 3.3,
        "zinc_mg": 1.4,
        "magnesium_mg": 38.0,
        "calcium_mg": 103.0,
        "cholesterol_mg": 115.0,
    },
    {
        "name": "Perch (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 130.0},
        ],
        "calories": 91,
        "protein_g": 19.4,
        "carbs_g": 0.0,
        "fats_g": 0.9,
        "saturated_fats_g": 0.2,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 269.0,
        "sodium_mg": 62.0,
        "iron_mg": 0.9,
        "vitamin_d_mcg": 2.6,
        "zinc_mg": 1.1,
        "magnesium_mg": 30.0,
        "calcium_mg": 80.0,
        "cholesterol_mg": 90.0,
    },
    {
        "name": "Salmon (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 155.0},
        ],
        "calories": 206,
        "protein_g": 22.1,
        "carbs_g": 0.0,
        "fats_g": 12.3,
        "saturated_fats_g": 2.5,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 384.0,
        "sodium_mg": 61.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 13.1,
        "zinc_mg": 0.5,
        "magnesium_mg": 30.0,
        "calcium_mg": 15.0,
        "cholesterol_mg": 63.0,
    },
    {
        "name": "Salmon (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 170.0},
        ],
        "calories": 208,
        "protein_g": 20.4,
        "carbs_g": 0.0,
        "fats_g": 13.4,
        "saturated_fats_g": 3.1,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 363.0,
        "sodium_mg": 59.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 13.1,
        "zinc_mg": 0.4,
        "magnesium_mg": 27.0,
        "calcium_mg": 9.0,
        "cholesterol_mg": 55.0,
    },
    {
        "name": "Smoked Salmon",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 113.0},
        ],
        "calories": 117,
        "protein_g": 18.3,
        "carbs_g": 0.0,
        "fats_g": 4.3,
        "saturated_fats_g": 0.9,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 175.0,
        "sodium_mg": 672.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 17.1,
        "zinc_mg": 0.3,
        "magnesium_mg": 18.0,
        "calcium_mg": 11.0,
        "cholesterol_mg": 23.0,
    },
    {
        "name": "Trout (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 140.0},
        ],
        "calories": 190,
        "protein_g": 26.6,
        "carbs_g": 0.0,
        "fats_g": 8.5,
        "saturated_fats_g": 1.8,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 463.0,
        "sodium_mg": 67.0,
        "iron_mg": 1.9,
        "vitamin_d_mcg": 5.0,
        "zinc_mg": 0.8,
        "magnesium_mg": 28.0,
        "calcium_mg": 55.0,
        "cholesterol_mg": 74.0,
    },
    {
        "name": "Trout (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 160.0},
        ],
        "calories": 148,
        "protein_g": 20.8,
        "carbs_g": 0.0,
        "fats_g": 6.6,
        "saturated_fats_g": 1.4,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 361.0,
        "sodium_mg": 52.0,
        "iron_mg": 1.5,
        "vitamin_d_mcg": 3.9,
        "zinc_mg": 0.6,
        "magnesium_mg": 22.0,
        "calcium_mg": 43.0,
        "cholesterol_mg": 58.0,
    },
    {
        "name": "Tuna (Cooked, Fresh)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 150.0},
        ],
        "calories": 130,
        "protein_g": 28.0,
        "carbs_g": 0.0,
        "fats_g": 0.6,
        "saturated_fats_g": 0.2,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 323.0,
        "sodium_mg": 50.0,
        "iron_mg": 1.0,
        "vitamin_d_mcg": 7.3,
        "zinc_mg": 0.5,
        "magnesium_mg": 35.0,
        "calcium_mg": 10.0,
        "cholesterol_mg": 50.0,
    },
    {
        "name": "Tuna (Raw, Fresh)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fillet", "equivalent_g": 170.0},
        ],
        "calories": 109,
        "protein_g": 24.4,
        "carbs_g": 0.0,
        "fats_g": 0.5,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 252.0,
        "sodium_mg": 39.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 5.7,
        "zinc_mg": 0.4,
        "magnesium_mg": 27.0,
        "calcium_mg": 8.0,
        "cholesterol_mg": 39.0,
    },
]
