"""Citrus entries for the global food database."""

FRUITS_CITRUS = [
    {
        "name": "Grapefruit (Raw, Pink/Red)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 230.0},
            {"description": "1 fruit", "equivalent_g": 246.0},
            {"description": "1 slice", "equivalent_g": 20.0},
        ],
        "calories": 42,
        "protein_g": 0.8,
        "carbs_g": 10.7,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.6,
        "sugar_g": 6.9,
        "potassium_mg": 135.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 9.0,
        "calcium_mg": 22.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Lemon (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 212.0},
            {"description": "1 fruit", "equivalent_g": 58.0},
            {"description": "1 slice", "equivalent_g": 5.0},
        ],
        "calories": 29,
        "protein_g": 1.1,
        "carbs_g": 9.3,
        "fats_g": 0.3,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.8,
        "sugar_g": 2.5,
        "potassium_mg": 138.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 8.0,
        "calcium_mg": 26.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Lime (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 200.0},
            {"description": "1 fruit", "equivalent_g": 67.0},
            {"description": "1 slice", "equivalent_g": 5.0},
        ],
        "calories": 30,
        "protein_g": 0.7,
        "carbs_g": 10.5,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.8,
        "sugar_g": 1.7,
        "potassium_mg": 102.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 6.0,
        "calcium_mg": 33.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Mandarin / Tangerine (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 195.0},
            {"description": "1 fruit", "equivalent_g": 88.0},
            {"description": "1 slice", "equivalent_g": 10.0},
        ],
        "calories": 53,
        "protein_g": 0.8,
        "carbs_g": 13.3,
        "fats_g": 0.3,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.8,
        "sugar_g": 10.6,
        "potassium_mg": 166.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 12.0,
        "calcium_mg": 37.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Orange (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 180.0},
            {"description": "1 fruit", "equivalent_g": 131.0},
            {"description": "1 slice", "equivalent_g": 15.0},
        ],
        "calories": 47,
        "protein_g": 0.9,
        "carbs_g": 11.8,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.4,
        "sugar_g": 9.4,
        "potassium_mg": 181.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 10.0,
        "calcium_mg": 40.0,
        "cholesterol_mg": 0.0,
    },
]
