"""Berries & Melons entries for the global food database."""

FRUITS_BERRIES_AND_MELONS = [
    {
        "name": "Blackberries (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 144.0},
            {"description": "1 berry", "equivalent_g": 5.0},
        ],
        "calories": 43,
        "protein_g": 1.4,
        "carbs_g": 9.6,
        "fats_g": 0.5,
        "saturated_fats_g": 0.0,
        "fiber_g": 5.3,
        "sugar_g": 4.9,
        "potassium_mg": 162.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 20.0,
        "calcium_mg": 29.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Blueberries (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 148.0},
            {"description": "1 berry", "equivalent_g": 2.0},
        ],
        "calories": 57,
        "protein_g": 0.7,
        "carbs_g": 14.5,
        "fats_g": 0.3,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.4,
        "sugar_g": 10.0,
        "potassium_mg": 77.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 6.0,
        "calcium_mg": 6.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Cantaloupe Melon (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 160.0},
            {"description": "1 slice", "equivalent_g": 69.0},
        ],
        "calories": 34,
        "protein_g": 0.8,
        "carbs_g": 8.2,
        "fats_g": 0.2,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.9,
        "sugar_g": 7.9,
        "potassium_mg": 267.0,
        "sodium_mg": 16.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 12.0,
        "calcium_mg": 9.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Cherries (Raw, Sweet)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 154.0},
            {"description": "1 berry", "equivalent_g": 8.0},
        ],
        "calories": 63,
        "protein_g": 1.1,
        "carbs_g": 16.0,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.1,
        "sugar_g": 12.8,
        "potassium_mg": 222.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 11.0,
        "calcium_mg": 13.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Cranberries (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 100.0},
            {"description": "1 berry", "equivalent_g": 1.0},
        ],
        "calories": 46,
        "protein_g": 0.4,
        "carbs_g": 12.2,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 4.6,
        "sugar_g": 4.0,
        "potassium_mg": 85.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 6.0,
        "calcium_mg": 8.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Grapes (Raw, Red or Green)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 151.0},
            {"description": "1 berry", "equivalent_g": 5.0},
        ],
        "calories": 69,
        "protein_g": 0.7,
        "carbs_g": 18.1,
        "fats_g": 0.2,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.9,
        "sugar_g": 15.5,
        "potassium_mg": 191.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 7.0,
        "calcium_mg": 10.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Honeydew Melon (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 170.0},
            {"description": "1 slice", "equivalent_g": 160.0},
        ],
        "calories": 36,
        "protein_g": 0.5,
        "carbs_g": 9.1,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.8,
        "sugar_g": 8.1,
        "potassium_mg": 228.0,
        "sodium_mg": 18.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 10.0,
        "calcium_mg": 6.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Raspberries (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 123.0},
            {"description": "1 berry", "equivalent_g": 2.0},
        ],
        "calories": 52,
        "protein_g": 1.2,
        "carbs_g": 11.9,
        "fats_g": 0.7,
        "saturated_fats_g": 0.0,
        "fiber_g": 6.5,
        "sugar_g": 4.4,
        "potassium_mg": 151.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.4,
        "magnesium_mg": 22.0,
        "calcium_mg": 25.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Strawberries (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 152.0},
            {"description": "1 berry", "equivalent_g": 12.0},
        ],
        "calories": 32,
        "protein_g": 0.7,
        "carbs_g": 7.7,
        "fats_g": 0.3,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.0,
        "sugar_g": 4.9,
        "potassium_mg": 153.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 13.0,
        "calcium_mg": 16.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Watermelon (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 152.0},
            {"description": "1 slice", "equivalent_g": 286.0},
        ],
        "calories": 30,
        "protein_g": 0.6,
        "carbs_g": 7.6,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.4,
        "sugar_g": 6.2,
        "potassium_mg": 112.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 10.0,
        "calcium_mg": 7.0,
        "cholesterol_mg": 0.0,
    },
]
