"""Tree & Tropical Fruits entries for the global food database."""

FRUITS_TREE_AND_TROPICAL = [
    {
        "name": "Apple (Raw, with skin)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fruit", "equivalent_g": 182.0},
            {"description": "1 slice", "equivalent_g": 15.0},
        ],
        "calories": 52,
        "protein_g": 0.3,
        "carbs_g": 13.8,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.4,
        "sugar_g": 10.4,
        "potassium_mg": 107.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 5.0,
        "calcium_mg": 6.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Apricot (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 165.0},
            {"description": "1 fruit", "equivalent_g": 35.0},
            {"description": "1 slice", "equivalent_g": 17.0},
        ],
        "calories": 48,
        "protein_g": 1.4,
        "carbs_g": 11.1,
        "fats_g": 0.4,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.0,
        "sugar_g": 9.2,
        "potassium_mg": 259.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 10.0,
        "calcium_mg": 13.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Avocado (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fruit", "equivalent_g": 201.0},
            {"description": "1 slice", "equivalent_g": 15.0},
        ],
        "calories": 160,
        "protein_g": 2.0,
        "carbs_g": 8.5,
        "fats_g": 14.7,
        "saturated_fats_g": 2.1,
        "fiber_g": 6.7,
        "sugar_g": 0.7,
        "potassium_mg": 485.0,
        "sodium_mg": 7.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.6,
        "magnesium_mg": 29.0,
        "calcium_mg": 12.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Banana (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 large", "equivalent_g": 136.0},
            {"description": "1 medium", "equivalent_g": 118.0},
            {"description": "1 small", "equivalent_g": 101.0},
        ],
        "calories": 89,
        "protein_g": 1.1,
        "carbs_g": 22.8,
        "fats_g": 0.3,
        "saturated_fats_g": 0.1,
        "fiber_g": 2.6,
        "sugar_g": 12.2,
        "potassium_mg": 358.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 27.0,
        "calcium_mg": 5.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Coconut Flakes (Unsweetened, Dried)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 93.0},
        ],
        "calories": 660,
        "protein_g": 6.9,
        "carbs_g": 23.7,
        "fats_g": 64.5,
        "saturated_fats_g": 57.2,
        "fiber_g": 16.3,
        "sugar_g": 7.4,
        "potassium_mg": 543.0,
        "sodium_mg": 37.0,
        "iron_mg": 3.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 2.0,
        "magnesium_mg": 90.0,
        "calcium_mg": 26.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Fig (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 149.0},
            {"description": "1 fruit", "equivalent_g": 50.0},
        ],
        "calories": 74,
        "protein_g": 0.8,
        "carbs_g": 19.2,
        "fats_g": 0.3,
        "saturated_fats_g": 0.1,
        "fiber_g": 2.9,
        "sugar_g": 16.3,
        "potassium_mg": 232.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 17.0,
        "calcium_mg": 35.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Kiwi (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 180.0},
            {"description": "1 fruit", "equivalent_g": 69.0},
            {"description": "1 slice", "equivalent_g": 10.0},
        ],
        "calories": 61,
        "protein_g": 1.1,
        "carbs_g": 14.7,
        "fats_g": 0.5,
        "saturated_fats_g": 0.0,
        "fiber_g": 3.0,
        "sugar_g": 9.0,
        "potassium_mg": 312.0,
        "sodium_mg": 3.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 17.0,
        "calcium_mg": 34.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Mango (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 165.0},
            {"description": "1 fruit", "equivalent_g": 336.0},
            {"description": "1 slice", "equivalent_g": 20.0},
        ],
        "calories": 60,
        "protein_g": 0.8,
        "carbs_g": 15.0,
        "fats_g": 0.4,
        "saturated_fats_g": 0.1,
        "fiber_g": 1.6,
        "sugar_g": 13.7,
        "potassium_mg": 168.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 10.0,
        "calcium_mg": 11.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Nectarine (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 143.0},
            {"description": "1 fruit", "equivalent_g": 136.0},
            {"description": "1 slice", "equivalent_g": 10.0},
        ],
        "calories": 44,
        "protein_g": 1.1,
        "carbs_g": 10.5,
        "fats_g": 0.3,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.7,
        "sugar_g": 7.9,
        "potassium_mg": 201.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 9.0,
        "calcium_mg": 6.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Papaya (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 145.0},
            {"description": "1 fruit", "equivalent_g": 304.0},
            {"description": "1 slice", "equivalent_g": 100.0},
        ],
        "calories": 43,
        "protein_g": 0.5,
        "carbs_g": 10.8,
        "fats_g": 0.3,
        "saturated_fats_g": 0.1,
        "fiber_g": 1.7,
        "sugar_g": 7.8,
        "potassium_mg": 182.0,
        "sodium_mg": 8.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 21.0,
        "calcium_mg": 20.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Peach (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 fruit", "equivalent_g": 150.0},
            {"description": "1 slice", "equivalent_g": 15.0},
        ],
        "calories": 39,
        "protein_g": 0.9,
        "carbs_g": 9.5,
        "fats_g": 0.3,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.5,
        "sugar_g": 8.4,
        "potassium_mg": 190.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 9.0,
        "calcium_mg": 6.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Pineapple (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 165.0},
            {"description": "1 fruit", "equivalent_g": 905.0},
            {"description": "1 slice", "equivalent_g": 84.0},
        ],
        "calories": 50,
        "protein_g": 0.5,
        "carbs_g": 13.1,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.4,
        "sugar_g": 9.8,
        "potassium_mg": 109.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 12.0,
        "calcium_mg": 13.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Plum (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 165.0},
            {"description": "1 fruit", "equivalent_g": 66.0},
            {"description": "1 slice", "equivalent_g": 8.0},
        ],
        "calories": 46,
        "protein_g": 0.7,
        "carbs_g": 11.4,
        "fats_g": 0.3,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.4,
        "sugar_g": 9.9,
        "potassium_mg": 157.0,
        "sodium_mg": 0.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 7.0,
        "calcium_mg": 6.0,
        "cholesterol_mg": 0.0,
    },
]
