"""Grains, Pasta & Cereals entries for the global food database."""

GRAINS_PASTA_AND_CEREALS = [
    {
        "name": "Cornflakes (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 28.0},
        ],
        "calories": 357,
        "protein_g": 8.0,
        "carbs_g": 84.0,
        "fats_g": 0.4,
        "saturated_fats_g": 0.1,
        "fiber_g": 3.3,
        "sugar_g": 1.5,
        "potassium_mg": 168.0,
        "sodium_mg": 729.0,
        "iron_mg": 28.0,
        "vitamin_d_mcg": 4.0,
        "zinc_mg": 1.5,
        "magnesium_mg": 39.0,
        "calcium_mg": 14.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Fusilli Pasta (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 140.0},
        ],
        "calories": 158,
        "protein_g": 5.8,
        "carbs_g": 31.0,
        "fats_g": 0.9,
        "saturated_fats_g": 0.2,
        "fiber_g": 1.8,
        "sugar_g": 0.4,
        "potassium_mg": 44.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 18.0,
        "calcium_mg": 7.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Fusilli Pasta (Dry, Enriched)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 107.0},
        ],
        "calories": 371,
        "protein_g": 13.0,
        "carbs_g": 74.0,
        "fats_g": 1.5,
        "saturated_fats_g": 0.3,
        "fiber_g": 3.2,
        "sugar_g": 2.7,
        "potassium_mg": 223.0,
        "sodium_mg": 6.0,
        "iron_mg": 1.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.4,
        "magnesium_mg": 53.0,
        "calcium_mg": 21.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Glass Noodles (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 110,
        "protein_g": 0.1,
        "carbs_g": 27.0,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.2,
        "sugar_g": 0.0,
        "potassium_mg": 3.0,
        "sodium_mg": 3.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 2.0,
        "calcium_mg": 6.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Glass Noodles (Dry, Cellophane)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 351,
        "protein_g": 0.2,
        "carbs_g": 86.0,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.5,
        "sugar_g": 0.0,
        "potassium_mg": 10.0,
        "sodium_mg": 10.0,
        "iron_mg": 0.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 5.0,
        "calcium_mg": 20.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Oats (Cooked with Water)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 234.0},
        ],
        "calories": 71,
        "protein_g": 2.5,
        "carbs_g": 12.0,
        "fats_g": 1.5,
        "saturated_fats_g": 0.3,
        "fiber_g": 1.7,
        "sugar_g": 0.0,
        "potassium_mg": 61.0,
        "sodium_mg": 49.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.6,
        "magnesium_mg": 26.0,
        "calcium_mg": 9.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Oats (Dry, Rolled)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 81.0},
        ],
        "calories": 389,
        "protein_g": 16.9,
        "carbs_g": 66.3,
        "fats_g": 6.9,
        "saturated_fats_g": 1.2,
        "fiber_g": 10.6,
        "sugar_g": 0.0,
        "potassium_mg": 362.0,
        "sodium_mg": 2.0,
        "iron_mg": 4.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 3.6,
        "magnesium_mg": 138.0,
        "calcium_mg": 52.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Penne Pasta (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 140.0},
        ],
        "calories": 158,
        "protein_g": 5.8,
        "carbs_g": 31.0,
        "fats_g": 0.9,
        "saturated_fats_g": 0.2,
        "fiber_g": 1.8,
        "sugar_g": 0.4,
        "potassium_mg": 44.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 18.0,
        "calcium_mg": 7.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Penne Pasta (Dry, Enriched)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 107.0},
        ],
        "calories": 371,
        "protein_g": 13.0,
        "carbs_g": 74.0,
        "fats_g": 1.5,
        "saturated_fats_g": 0.3,
        "fiber_g": 3.2,
        "sugar_g": 2.7,
        "potassium_mg": 223.0,
        "sodium_mg": 6.0,
        "iron_mg": 1.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.4,
        "magnesium_mg": 53.0,
        "calcium_mg": 21.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Rice Cakes (Plain, Lightly Salted)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cake", "equivalent_g": 9.0},
        ],
        "calories": 387,
        "protein_g": 8.2,
        "carbs_g": 81.5,
        "fats_g": 2.8,
        "saturated_fats_g": 0.6,
        "fiber_g": 3.3,
        "sugar_g": 0.9,
        "potassium_mg": 326.0,
        "sodium_mg": 260.0,
        "iron_mg": 1.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 2.2,
        "magnesium_mg": 118.0,
        "calcium_mg": 11.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Rice Noodles (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 109,
        "protein_g": 0.9,
        "carbs_g": 24.0,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.4,
        "sugar_g": 0.0,
        "potassium_mg": 4.0,
        "sodium_mg": 5.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 3.0,
        "calcium_mg": 4.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Rice Noodles (Dry)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 364,
        "protein_g": 3.4,
        "carbs_g": 82.0,
        "fats_g": 0.6,
        "saturated_fats_g": 0.1,
        "fiber_g": 1.6,
        "sugar_g": 0.0,
        "potassium_mg": 25.0,
        "sodium_mg": 18.0,
        "iron_mg": 0.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 11.0,
        "calcium_mg": 15.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Spaghetti (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 158,
        "protein_g": 5.8,
        "carbs_g": 31.0,
        "fats_g": 0.9,
        "saturated_fats_g": 0.2,
        "fiber_g": 1.8,
        "sugar_g": 0.4,
        "potassium_mg": 44.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 18.0,
        "calcium_mg": 7.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Spaghetti (Dry, Enriched)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 371,
        "protein_g": 13.0,
        "carbs_g": 74.0,
        "fats_g": 1.5,
        "saturated_fats_g": 0.3,
        "fiber_g": 3.2,
        "sugar_g": 2.7,
        "potassium_mg": 223.0,
        "sodium_mg": 6.0,
        "iron_mg": 1.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.4,
        "magnesium_mg": 53.0,
        "calcium_mg": 21.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Wheat Noodles (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 130,
        "protein_g": 4.0,
        "carbs_g": 27.0,
        "fats_g": 0.5,
        "saturated_fats_g": 0.1,
        "fiber_g": 1.2,
        "sugar_g": 0.8,
        "potassium_mg": 50.0,
        "sodium_mg": 150.0,
        "iron_mg": 0.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.4,
        "magnesium_mg": 15.0,
        "calcium_mg": 8.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Wheat Noodles (Dry, Soba/Udon type)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 336,
        "protein_g": 12.0,
        "carbs_g": 72.0,
        "fats_g": 1.2,
        "saturated_fats_g": 0.2,
        "fiber_g": 3.0,
        "sugar_g": 2.0,
        "potassium_mg": 180.0,
        "sodium_mg": 500.0,
        "iron_mg": 1.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.0,
        "magnesium_mg": 40.0,
        "calcium_mg": 20.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "White Rice (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 158.0},
        ],
        "calories": 130,
        "protein_g": 2.7,
        "carbs_g": 28.2,
        "fats_g": 0.3,
        "saturated_fats_g": 0.1,
        "fiber_g": 0.4,
        "sugar_g": 0.1,
        "potassium_mg": 35.0,
        "sodium_mg": 1.0,
        "iron_mg": 1.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.4,
        "magnesium_mg": 12.0,
        "calcium_mg": 10.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "White Rice (Dry, Enriched Long Grain)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 185.0},
        ],
        "calories": 365,
        "protein_g": 7.1,
        "carbs_g": 80.0,
        "fats_g": 0.7,
        "saturated_fats_g": 0.2,
        "fiber_g": 1.3,
        "sugar_g": 0.1,
        "potassium_mg": 115.0,
        "sodium_mg": 5.0,
        "iron_mg": 4.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.1,
        "magnesium_mg": 25.0,
        "calcium_mg": 28.0,
        "cholesterol_mg": 0.0,
    },
]
