"""Legumes & Plant Proteins entries for the global food database."""

LEGUMES_AND_PLANT_PROTEINS = [
    {
        "name": "Black Beans (Cooked / Boiled)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 172.0},
        ],
        "calories": 132,
        "protein_g": 8.9,
        "carbs_g": 23.7,
        "fats_g": 0.5,
        "saturated_fats_g": 0.1,
        "fiber_g": 8.7,
        "sugar_g": 0.3,
        "potassium_mg": 355.0,
        "sodium_mg": 1.0,
        "iron_mg": 2.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.1,
        "magnesium_mg": 70.0,
        "calcium_mg": 27.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Chickpeas / Garbanzo Beans (Cooked / Boiled)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 164.0},
        ],
        "calories": 164,
        "protein_g": 8.9,
        "carbs_g": 27.4,
        "fats_g": 2.6,
        "saturated_fats_g": 0.3,
        "fiber_g": 7.6,
        "sugar_g": 4.8,
        "potassium_mg": 291.0,
        "sodium_mg": 7.0,
        "iron_mg": 2.9,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.5,
        "magnesium_mg": 48.0,
        "calcium_mg": 49.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Edamame (Cooked/Steamed)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 155.0},
        ],
        "calories": 121,
        "protein_g": 11.9,
        "carbs_g": 8.9,
        "fats_g": 5.2,
        "saturated_fats_g": 0.6,
        "fiber_g": 5.2,
        "sugar_g": 2.2,
        "potassium_mg": 436.0,
        "sodium_mg": 6.0,
        "iron_mg": 2.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.4,
        "magnesium_mg": 64.0,
        "calcium_mg": 63.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Green Peas (Cooked / Boiled)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 160.0},
        ],
        "calories": 84,
        "protein_g": 5.4,
        "carbs_g": 15.6,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 5.5,
        "sugar_g": 5.9,
        "potassium_mg": 271.0,
        "sodium_mg": 3.0,
        "iron_mg": 1.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.2,
        "magnesium_mg": 39.0,
        "calcium_mg": 27.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Lentils (Cooked / Boiled)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 198.0},
        ],
        "calories": 116,
        "protein_g": 9.0,
        "carbs_g": 20.1,
        "fats_g": 0.4,
        "saturated_fats_g": 0.1,
        "fiber_g": 7.9,
        "sugar_g": 1.8,
        "potassium_mg": 369.0,
        "sodium_mg": 2.0,
        "iron_mg": 3.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.3,
        "magnesium_mg": 36.0,
        "calcium_mg": 19.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Soybeans (Cooked / Boiled)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 172.0},
        ],
        "calories": 172,
        "protein_g": 16.6,
        "carbs_g": 9.9,
        "fats_g": 9.0,
        "saturated_fats_g": 1.3,
        "fiber_g": 6.0,
        "sugar_g": 3.0,
        "potassium_mg": 515.0,
        "sodium_mg": 1.0,
        "iron_mg": 5.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.2,
        "magnesium_mg": 86.0,
        "calcium_mg": 102.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Tofu (Firm, Calcium Set)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 144,
        "protein_g": 15.8,
        "carbs_g": 2.8,
        "fats_g": 8.7,
        "saturated_fats_g": 1.3,
        "fiber_g": 2.3,
        "sugar_g": 0.0,
        "potassium_mg": 121.0,
        "sodium_mg": 7.0,
        "iron_mg": 5.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.6,
        "magnesium_mg": 58.0,
        "calcium_mg": 683.0,
        "cholesterol_mg": 0.0,
    },
]
