"""Nuts & Seeds entries for the global food database."""

NUTS_AND_SEEDS = [
    {
        "name": "Almonds (Raw, Unsalted)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 143.0},
            {"description": "1 nut", "equivalent_g": 1.2},
        ],
        "calories": 579,
        "protein_g": 21.1,
        "carbs_g": 21.6,
        "fats_g": 49.9,
        "saturated_fats_g": 3.8,
        "fiber_g": 12.5,
        "sugar_g": 4.4,
        "potassium_mg": 733.0,
        "sodium_mg": 1.0,
        "iron_mg": 3.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 3.1,
        "magnesium_mg": 268.0,
        "calcium_mg": 269.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Brazil Nuts (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 133.0},
            {"description": "1 nut", "equivalent_g": 5.0},
        ],
        "calories": 659,
        "protein_g": 14.3,
        "carbs_g": 11.7,
        "fats_g": 67.1,
        "saturated_fats_g": 16.1,
        "fiber_g": 7.5,
        "sugar_g": 2.3,
        "potassium_mg": 659.0,
        "sodium_mg": 3.0,
        "iron_mg": 2.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 4.1,
        "magnesium_mg": 376.0,
        "calcium_mg": 160.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Cashews (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 130.0},
            {"description": "1 nut", "equivalent_g": 1.5},
        ],
        "calories": 553,
        "protein_g": 18.2,
        "carbs_g": 30.2,
        "fats_g": 43.8,
        "saturated_fats_g": 7.8,
        "fiber_g": 3.3,
        "sugar_g": 5.9,
        "potassium_mg": 660.0,
        "sodium_mg": 12.0,
        "iron_mg": 6.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 5.8,
        "magnesium_mg": 292.0,
        "calcium_mg": 37.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Chia Seeds",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 160.0},
        ],
        "calories": 486,
        "protein_g": 16.5,
        "carbs_g": 42.1,
        "fats_g": 30.7,
        "saturated_fats_g": 3.3,
        "fiber_g": 34.4,
        "sugar_g": 0.0,
        "potassium_mg": 407.0,
        "sodium_mg": 16.0,
        "iron_mg": 7.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 4.6,
        "magnesium_mg": 335.0,
        "calcium_mg": 631.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Flaxseeds (Whole)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 168.0},
        ],
        "calories": 534,
        "protein_g": 18.3,
        "carbs_g": 28.9,
        "fats_g": 42.2,
        "saturated_fats_g": 3.7,
        "fiber_g": 27.3,
        "sugar_g": 1.5,
        "potassium_mg": 813.0,
        "sodium_mg": 30.0,
        "iron_mg": 5.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 4.3,
        "magnesium_mg": 392.0,
        "calcium_mg": 255.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Hazelnuts (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 135.0},
            {"description": "1 nut", "equivalent_g": 1.3},
        ],
        "calories": 628,
        "protein_g": 15.0,
        "carbs_g": 16.7,
        "fats_g": 60.7,
        "saturated_fats_g": 4.5,
        "fiber_g": 9.7,
        "sugar_g": 4.3,
        "potassium_mg": 680.0,
        "sodium_mg": 0.0,
        "iron_mg": 4.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 2.4,
        "magnesium_mg": 163.0,
        "calcium_mg": 114.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Hemp Seeds (Hulled)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 150.0},
        ],
        "calories": 553,
        "protein_g": 31.6,
        "carbs_g": 8.7,
        "fats_g": 48.8,
        "saturated_fats_g": 4.6,
        "fiber_g": 4.0,
        "sugar_g": 1.5,
        "potassium_mg": 1200.0,
        "sodium_mg": 5.0,
        "iron_mg": 7.9,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 9.9,
        "magnesium_mg": 700.0,
        "calcium_mg": 70.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Macadamia Nuts (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 134.0},
            {"description": "1 nut", "equivalent_g": 2.5},
        ],
        "calories": 718,
        "protein_g": 7.9,
        "carbs_g": 13.8,
        "fats_g": 75.8,
        "saturated_fats_g": 12.0,
        "fiber_g": 8.6,
        "sugar_g": 4.6,
        "potassium_mg": 368.0,
        "sodium_mg": 5.0,
        "iron_mg": 3.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.3,
        "magnesium_mg": 130.0,
        "calcium_mg": 85.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Peanuts (Raw, Unsalted)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 146.0},
            {"description": "1 nut", "equivalent_g": 1.0},
        ],
        "calories": 567,
        "protein_g": 25.8,
        "carbs_g": 16.1,
        "fats_g": 49.2,
        "saturated_fats_g": 6.3,
        "fiber_g": 8.5,
        "sugar_g": 4.7,
        "potassium_mg": 705.0,
        "sodium_mg": 18.0,
        "iron_mg": 4.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 3.3,
        "magnesium_mg": 168.0,
        "calcium_mg": 92.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Pecans (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 109.0},
            {"description": "1 nut (half)", "equivalent_g": 1.5},
        ],
        "calories": 691,
        "protein_g": 9.2,
        "carbs_g": 13.9,
        "fats_g": 72.0,
        "saturated_fats_g": 6.2,
        "fiber_g": 9.6,
        "sugar_g": 4.0,
        "potassium_mg": 410.0,
        "sodium_mg": 0.0,
        "iron_mg": 2.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 4.5,
        "magnesium_mg": 121.0,
        "calcium_mg": 70.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Pine Nuts (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 135.0},
            {"description": "1 nut", "equivalent_g": 0.2},
        ],
        "calories": 673,
        "protein_g": 13.7,
        "carbs_g": 13.1,
        "fats_g": 68.4,
        "saturated_fats_g": 4.9,
        "fiber_g": 3.7,
        "sugar_g": 3.6,
        "potassium_mg": 597.0,
        "sodium_mg": 2.0,
        "iron_mg": 5.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 6.4,
        "magnesium_mg": 251.0,
        "calcium_mg": 16.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Pistachios (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 123.0},
            {"description": "1 nut", "equivalent_g": 0.7},
        ],
        "calories": 562,
        "protein_g": 20.2,
        "carbs_g": 27.2,
        "fats_g": 45.3,
        "saturated_fats_g": 5.9,
        "fiber_g": 10.6,
        "sugar_g": 7.7,
        "potassium_mg": 1025.0,
        "sodium_mg": 1.0,
        "iron_mg": 3.9,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 2.2,
        "magnesium_mg": 121.0,
        "calcium_mg": 105.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Pumpkin Seeds (Roasted, Unsalted)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 118.0},
        ],
        "calories": 574,
        "protein_g": 29.8,
        "carbs_g": 14.7,
        "fats_g": 49.1,
        "saturated_fats_g": 8.5,
        "fiber_g": 6.5,
        "sugar_g": 1.3,
        "potassium_mg": 788.0,
        "sodium_mg": 12.0,
        "iron_mg": 8.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 7.6,
        "magnesium_mg": 550.0,
        "calcium_mg": 43.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Sesame Seeds (Whole, Roasted)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 144.0},
        ],
        "calories": 573,
        "protein_g": 17.7,
        "carbs_g": 23.4,
        "fats_g": 49.7,
        "saturated_fats_g": 7.0,
        "fiber_g": 11.8,
        "sugar_g": 0.3,
        "potassium_mg": 468.0,
        "sodium_mg": 11.0,
        "iron_mg": 14.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 7.8,
        "magnesium_mg": 351.0,
        "calcium_mg": 975.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Sunflower Seeds (Hulled, Dry Roasted)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 128.0},
        ],
        "calories": 584,
        "protein_g": 20.8,
        "carbs_g": 20.0,
        "fats_g": 51.5,
        "saturated_fats_g": 4.5,
        "fiber_g": 8.6,
        "sugar_g": 2.6,
        "potassium_mg": 645.0,
        "sodium_mg": 9.0,
        "iron_mg": 5.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 5.1,
        "magnesium_mg": 325.0,
        "calcium_mg": 78.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Walnuts (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 117.0},
            {"description": "1 nut (half)", "equivalent_g": 2.0},
        ],
        "calories": 654,
        "protein_g": 15.2,
        "carbs_g": 13.7,
        "fats_g": 65.2,
        "saturated_fats_g": 6.1,
        "fiber_g": 6.7,
        "sugar_g": 2.6,
        "potassium_mg": 441.0,
        "sodium_mg": 2.0,
        "iron_mg": 2.9,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 3.1,
        "magnesium_mg": 158.0,
        "calcium_mg": 98.0,
        "cholesterol_mg": 0.0,
    },
]
