"""Pantry & Sweeteners entries for the global food database."""

PANTRY_AND_SWEETENERS = [
    {
        "name": "Brown Sugar",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 220.0},
            {"description": "1 tablespoon", "equivalent_g": 13.8},
            {"description": "1 teaspoon", "equivalent_g": 4.6},
        ],
        "calories": 380,
        "protein_g": 0.1,
        "carbs_g": 98.1,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 97.0,
        "potassium_mg": 133.0,
        "sodium_mg": 28.0,
        "iron_mg": 0.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 29.0,
        "calcium_mg": 83.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Cinnamon Powder",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 125.0},
            {"description": "1 tablespoon", "equivalent_g": 7.8},
            {"description": "1 teaspoon", "equivalent_g": 2.6},
        ],
        "calories": 247,
        "protein_g": 4.0,
        "carbs_g": 80.6,
        "fats_g": 1.2,
        "saturated_fats_g": 0.3,
        "fiber_g": 53.1,
        "sugar_g": 2.2,
        "potassium_mg": 431.0,
        "sodium_mg": 10.0,
        "iron_mg": 8.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.8,
        "magnesium_mg": 60.0,
        "calcium_mg": 1002.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Cocoa Powder (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 86.0},
            {"description": "1 tablespoon", "equivalent_g": 5.4},
            {"description": "1 teaspoon", "equivalent_g": 1.8},
        ],
        "calories": 228,
        "protein_g": 19.6,
        "carbs_g": 57.9,
        "fats_g": 13.7,
        "saturated_fats_g": 8.1,
        "fiber_g": 37.0,
        "sugar_g": 1.8,
        "potassium_mg": 1524.0,
        "sodium_mg": 21.0,
        "iron_mg": 13.9,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 6.8,
        "magnesium_mg": 499.0,
        "calcium_mg": 128.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Corn Starch",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 128.0},
            {"description": "1 tablespoon", "equivalent_g": 8.0},
            {"description": "1 teaspoon", "equivalent_g": 2.7},
        ],
        "calories": 381,
        "protein_g": 0.3,
        "carbs_g": 91.3,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.9,
        "sugar_g": 0.0,
        "potassium_mg": 3.0,
        "sodium_mg": 9.0,
        "iron_mg": 0.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 3.0,
        "calcium_mg": 2.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Honey",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 339.0},
            {"description": "1 tablespoon", "equivalent_g": 21.0},
            {"description": "1 teaspoon", "equivalent_g": 7.0},
        ],
        "calories": 304,
        "protein_g": 0.3,
        "carbs_g": 82.4,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.2,
        "sugar_g": 82.1,
        "potassium_mg": 52.0,
        "sodium_mg": 4.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 2.0,
        "calcium_mg": 6.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Maple Syrup (100% Pure, Full Sugar)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 315.0},
            {"description": "1 tablespoon", "equivalent_g": 20.0},
            {"description": "1 teaspoon", "equivalent_g": 6.7},
        ],
        "calories": 260,
        "protein_g": 0.0,
        "carbs_g": 67.0,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 60.4,
        "potassium_mg": 212.0,
        "sodium_mg": 12.0,
        "iron_mg": 0.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.5,
        "magnesium_mg": 21.0,
        "calcium_mg": 102.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Maple Syrup (Zero Sugar / Sugar Free)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 240.0},
            {"description": "1 tablespoon", "equivalent_g": 15.0},
            {"description": "1 teaspoon", "equivalent_g": 5.0},
        ],
        "calories": 20,
        "protein_g": 0.0,
        "carbs_g": 8.0,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 10.0,
        "sodium_mg": 180.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 2.0,
        "calcium_mg": 5.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "White Sugar (Granulated)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 200.0},
            {"description": "1 tablespoon", "equivalent_g": 12.5},
            {"description": "1 teaspoon", "equivalent_g": 4.2},
        ],
        "calories": 387,
        "protein_g": 0.0,
        "carbs_g": 100.0,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 100.0,
        "potassium_mg": 2.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 1.0,
        "cholesterol_mg": 0.0,
    },
]
