"""Poultry entries for the global food database."""

POULTRY = [
    {
        "name": "Chicken Breast (Cooked, Boneless, Skinless)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 165,
        "protein_g": 31.0,
        "carbs_g": 0.0,
        "fats_g": 3.6,
        "saturated_fats_g": 1.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 256.0,
        "sodium_mg": 74.0,
        "iron_mg": 1.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.0,
        "magnesium_mg": 29.0,
        "calcium_mg": 15.0,
        "cholesterol_mg": 85.0,
    },
    {
        "name": "Chicken Breast (Raw, Boneless, Skinless)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 120,
        "protein_g": 22.5,
        "carbs_g": 0.0,
        "fats_g": 2.6,
        "saturated_fats_g": 0.6,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 255.0,
        "sodium_mg": 45.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.8,
        "magnesium_mg": 28.0,
        "calcium_mg": 11.0,
        "cholesterol_mg": 73.0,
    },
    {
        "name": "Chicken Drumsticks (Cooked, Boneless, Skinless)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 stick", "equivalent_g": 28.0},
        ],
        "calories": 175,
        "protein_g": 28.0,
        "carbs_g": 0.0,
        "fats_g": 5.7,
        "saturated_fats_g": 1.5,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 249.0,
        "sodium_mg": 99.0,
        "iron_mg": 1.2,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 2.6,
        "magnesium_mg": 25.0,
        "calcium_mg": 14.0,
        "cholesterol_mg": 100.0,
    },
    {
        "name": "Chicken Drumsticks (Cooked, with Skin & Bone - Edible Yield)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 stick", "equivalent_g": 35.0},
        ],
        "calories": 216,
        "protein_g": 26.0,
        "carbs_g": 0.0,
        "fats_g": 11.0,
        "saturated_fats_g": 3.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 239.0,
        "sodium_mg": 95.0,
        "iron_mg": 1.2,
        "vitamin_d_mcg": 0.2,
        "zinc_mg": 2.2,
        "magnesium_mg": 23.0,
        "calcium_mg": 13.0,
        "cholesterol_mg": 105.0,
    },
    {
        "name": "Chicken Drumsticks (Raw, Boneless, Skinless)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 stick", "equivalent_g": 38.0},
        ],
        "calories": 120,
        "protein_g": 19.0,
        "carbs_g": 0.0,
        "fats_g": 4.0,
        "saturated_fats_g": 1.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 235.0,
        "sodium_mg": 84.0,
        "iron_mg": 0.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.8,
        "magnesium_mg": 22.0,
        "calcium_mg": 11.0,
        "cholesterol_mg": 80.0,
    },
    {
        "name": "Chicken Drumsticks (Raw, with Skin & Bone - Edible Yield)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 stick", "equivalent_g": 44.0},
        ],
        "calories": 161,
        "protein_g": 19.0,
        "carbs_g": 0.0,
        "fats_g": 8.9,
        "saturated_fats_g": 2.4,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 222.0,
        "sodium_mg": 81.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 1.6,
        "magnesium_mg": 21.0,
        "calcium_mg": 11.0,
        "cholesterol_mg": 82.0,
    },
    {
        "name": "Chicken Thighs (Cooked, Boneless, Skinless)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 thigh", "equivalent_g": 70.0},
        ],
        "calories": 209,
        "protein_g": 26.0,
        "carbs_g": 0.0,
        "fats_g": 10.9,
        "saturated_fats_g": 3.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 255.0,
        "sodium_mg": 95.0,
        "iron_mg": 1.2,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 2.3,
        "magnesium_mg": 24.0,
        "calcium_mg": 13.0,
        "cholesterol_mg": 105.0,
    },
    {
        "name": "Chicken Thighs (Cooked, with Skin & Bone - Edible Yield)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 thigh", "equivalent_g": 62.0},
        ],
        "calories": 247,
        "protein_g": 24.0,
        "carbs_g": 0.0,
        "fats_g": 16.0,
        "saturated_fats_g": 4.5,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 240.0,
        "sodium_mg": 90.0,
        "iron_mg": 1.3,
        "vitamin_d_mcg": 0.3,
        "zinc_mg": 2.1,
        "magnesium_mg": 22.0,
        "calcium_mg": 14.0,
        "cholesterol_mg": 109.0,
    },
    {
        "name": "Chicken Thighs (Raw, Boneless, Skinless)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 thigh", "equivalent_g": 90.0},
        ],
        "calories": 121,
        "protein_g": 19.0,
        "carbs_g": 0.0,
        "fats_g": 4.3,
        "saturated_fats_g": 1.1,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 236.0,
        "sodium_mg": 86.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.7,
        "magnesium_mg": 21.0,
        "calcium_mg": 11.0,
        "cholesterol_mg": 83.0,
    },
    {
        "name": "Chicken Thighs (Raw, with Skin & Bone - Edible Yield)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 thigh", "equivalent_g": 100.0},
        ],
        "calories": 211,
        "protein_g": 16.0,
        "carbs_g": 0.0,
        "fats_g": 15.0,
        "saturated_fats_g": 4.2,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 200.0,
        "sodium_mg": 80.0,
        "iron_mg": 0.9,
        "vitamin_d_mcg": 0.2,
        "zinc_mg": 1.5,
        "magnesium_mg": 20.0,
        "calcium_mg": 10.0,
        "cholesterol_mg": 85.0,
    },
    {
        "name": "Chicken Wings (Cooked, Boneless, Skinless)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 wing", "equivalent_g": 10.0},
        ],
        "calories": 203,
        "protein_g": 30.0,
        "carbs_g": 0.0,
        "fats_g": 8.1,
        "saturated_fats_g": 2.2,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 260.0,
        "sodium_mg": 90.0,
        "iron_mg": 1.1,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 1.6,
        "magnesium_mg": 25.0,
        "calcium_mg": 14.0,
        "cholesterol_mg": 95.0,
    },
    {
        "name": "Chicken Wings (Cooked, with Skin & Bone - Edible Yield)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 wing", "equivalent_g": 16.0},
        ],
        "calories": 288,
        "protein_g": 27.0,
        "carbs_g": 0.0,
        "fats_g": 19.0,
        "saturated_fats_g": 5.4,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 202.0,
        "sodium_mg": 82.0,
        "iron_mg": 1.2,
        "vitamin_d_mcg": 0.3,
        "zinc_mg": 1.7,
        "magnesium_mg": 19.0,
        "calcium_mg": 15.0,
        "cholesterol_mg": 100.0,
    },
    {
        "name": "Chicken Wings (Raw, Boneless, Skinless)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 wing", "equivalent_g": 15.0},
        ],
        "calories": 110,
        "protein_g": 20.0,
        "carbs_g": 0.0,
        "fats_g": 2.5,
        "saturated_fats_g": 0.6,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 240.0,
        "sodium_mg": 80.0,
        "iron_mg": 0.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.1,
        "magnesium_mg": 23.0,
        "calcium_mg": 12.0,
        "cholesterol_mg": 70.0,
    },
    {
        "name": "Chicken Wings (Raw, with Skin & Bone - Edible Yield)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 wing", "equivalent_g": 21.0},
        ],
        "calories": 211,
        "protein_g": 17.0,
        "carbs_g": 0.0,
        "fats_g": 15.0,
        "saturated_fats_g": 4.3,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 166.0,
        "sodium_mg": 73.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 0.2,
        "zinc_mg": 1.2,
        "magnesium_mg": 16.0,
        "calcium_mg": 11.0,
        "cholesterol_mg": 77.0,
    },
    {
        "name": "Turkey Breast (Cooked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 147,
        "protein_g": 30.1,
        "carbs_g": 0.0,
        "fats_g": 2.0,
        "saturated_fats_g": 0.6,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 293.0,
        "sodium_mg": 129.0,
        "iron_mg": 1.1,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 1.7,
        "magnesium_mg": 29.0,
        "calcium_mg": 14.0,
        "cholesterol_mg": 75.0,
    },
    {
        "name": "Turkey Breast (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [],
        "calories": 114,
        "protein_g": 23.7,
        "carbs_g": 0.0,
        "fats_g": 1.5,
        "saturated_fats_g": 0.4,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "potassium_mg": 249.0,
        "sodium_mg": 115.0,
        "iron_mg": 0.7,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 1.3,
        "magnesium_mg": 26.0,
        "calcium_mg": 12.0,
        "cholesterol_mg": 62.0,
    },
]
