"""Purees, Mashes, and Sauces entries for the global food database."""

PUREES_AND_MASHES = [
    {
        "name": "Apple Sauce (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 244.0},
            {"description": "1 pouch / snack size", "equivalent_g": 90.0},
        ],
        "calories": 42,
        "protein_g": 0.2,
        "carbs_g": 11.3,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.2,
        "sugar_g": 10.5,
        "potassium_mg": 74.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 3.0,
        "calcium_mg": 4.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Apple Sauce (Sweetened)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 255.0},
            {"description": "1 pouch / snack size", "equivalent_g": 90.0},
        ],
        "calories": 68,
        "protein_g": 0.2,
        "carbs_g": 18.9,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.1,
        "sugar_g": 16.5,
        "potassium_mg": 65.0,
        "sodium_mg": 3.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 2.0,
        "calcium_mg": 3.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Tomato Puree (Passata)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 250.0},
            {"description": "1 tablespoon", "equivalent_g": 16.0},
        ],
        "calories": 38,
        "protein_g": 1.6,
        "carbs_g": 8.4,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.0,
        "sugar_g": 4.0,
        "potassium_mg": 439.0,
        "sodium_mg": 10.0,
        "iron_mg": 1.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 18.0,
        "calcium_mg": 13.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Pumpkin Puree (Canned, 100% Pumpkin)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 245.0},
        ],
        "calories": 34,
        "protein_g": 1.1,
        "carbs_g": 8.0,
        "fats_g": 0.3,
        "saturated_fats_g": 0.1,
        "fiber_g": 2.9,
        "sugar_g": 3.2,
        "potassium_mg": 206.0,
        "sodium_mg": 5.0,
        "iron_mg": 1.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 23.0,
        "calcium_mg": 26.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Mashed Potatoes / Potato Puree (Prepared with Milk & Butter)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 210.0},
        ],
        "calories": 113,
        "protein_g": 2.0,
        "carbs_g": 15.0,
        "fats_g": 4.5,
        "saturated_fats_g": 2.8,
        "fiber_g": 1.5,
        "sugar_g": 1.0,
        "potassium_mg": 300.0,
        "sodium_mg": 320.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.1,
        "zinc_mg": 0.3,
        "magnesium_mg": 15.0,
        "calcium_mg": 25.0,
        "cholesterol_mg": 12.0,
    },
    {
        "name": "Sweet Potato Puree (Unsweetened)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 255.0},
        ],
        "calories": 86,
        "protein_g": 1.6,
        "carbs_g": 20.1,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 3.0,
        "sugar_g": 4.2,
        "potassium_mg": 337.0,
        "sodium_mg": 55.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 25.0,
        "calcium_mg": 30.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Mashed Cauliflower / Cauliflower Puree",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 200.0},
        ],
        "calories": 45,
        "protein_g": 2.0,
        "carbs_g": 5.0,
        "fats_g": 2.0,
        "saturated_fats_g": 1.0,
        "fiber_g": 2.0,
        "sugar_g": 2.0,
        "potassium_mg": 180.0,
        "sodium_mg": 210.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 10.0,
        "calcium_mg": 25.0,
        "cholesterol_mg": 5.0,
    },
]
