"""Supplements entries for the global food database."""

SUPPLEMENTS = [
    {
        "name": "Generic Whey Protein Powder",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 scoop", "equivalent_g": 30.0},
        ],
        "calories": 375,
        "protein_g": 80.0,
        "carbs_g": 6.0,
        "fats_g": 3.5,
        "saturated_fats_g": 1.5,
        "fiber_g": 0.0,
        "sugar_g": 2.5,
        "potassium_mg": 500.0,
        "sodium_mg": 250.0,
        "iron_mg": 1.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 50.0,
        "calcium_mg": 400.0,
        "cholesterol_mg": 100.0,
    },
    {
        "name": "Casein Protein Powder",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 scoop", "equivalent_g": 33.0},
        ],
        "calories": 360,
        "protein_g": 73.0,
        "carbs_g": 10.0,
        "fats_g": 1.5,
        "saturated_fats_g": 0.5,
        "fiber_g": 0.0,
        "sugar_g": 4.0,
        "potassium_mg": 280.0,
        "sodium_mg": 190.0,
        "iron_mg": 1.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.5,
        "magnesium_mg": 45.0,
        "calcium_mg": 2200.0,
        "cholesterol_mg": 15.0,
    },
    {
        "name": "Maltodextrin Powder (Carb Supplement)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 scoop", "equivalent_g": 50.0},
        ],
        "calories": 380,
        "protein_g": 0.0,
        "carbs_g": 95.0,
        "fats_g": 0.0,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 5.0,
        "potassium_mg": 0.0,
        "sodium_mg": 20.0,
        "iron_mg": 0.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.0,
        "magnesium_mg": 0.0,
        "calcium_mg": 0.0,
        "cholesterol_mg": 0.0,
    },
]
