"""Leafy Greens & Cruciferous entries for the global food database."""

VEGETABLES_LEAFY_AND_CRUCIFEROUS = [
    {
        "name": "Arugula / Rucola (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 20.0},
        ],
        "calories": 25,
        "protein_g": 2.6,
        "carbs_g": 3.7,
        "fats_g": 0.7,
        "saturated_fats_g": 0.1,
        "fiber_g": 1.6,
        "sugar_g": 2.1,
        "potassium_mg": 369.0,
        "sodium_mg": 27.0,
        "iron_mg": 1.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 47.0,
        "calcium_mg": 160.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Baby Spinach (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 30.0},
        ],
        "calories": 23,
        "protein_g": 2.9,
        "carbs_g": 3.6,
        "fats_g": 0.4,
        "saturated_fats_g": 0.1,
        "fiber_g": 2.2,
        "sugar_g": 0.4,
        "potassium_mg": 558.0,
        "sodium_mg": 79.0,
        "iron_mg": 2.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 79.0,
        "calcium_mg": 99.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Broccoli (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 91.0},
        ],
        "calories": 34,
        "protein_g": 2.8,
        "carbs_g": 6.6,
        "fats_g": 0.4,
        "saturated_fats_g": 0.1,
        "fiber_g": 2.6,
        "sugar_g": 1.7,
        "potassium_mg": 316.0,
        "sodium_mg": 33.0,
        "iron_mg": 0.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.4,
        "magnesium_mg": 21.0,
        "calcium_mg": 47.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Brussels Sprouts (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 88.0},
        ],
        "calories": 43,
        "protein_g": 3.4,
        "carbs_g": 9.0,
        "fats_g": 0.3,
        "saturated_fats_g": 0.1,
        "fiber_g": 3.8,
        "sugar_g": 2.2,
        "potassium_mg": 389.0,
        "sodium_mg": 25.0,
        "iron_mg": 1.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.4,
        "magnesium_mg": 23.0,
        "calcium_mg": 42.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Cabbage (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 89.0},
        ],
        "calories": 25,
        "protein_g": 1.3,
        "carbs_g": 5.8,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.5,
        "sugar_g": 3.2,
        "potassium_mg": 170.0,
        "sodium_mg": 18.0,
        "iron_mg": 0.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 12.0,
        "calcium_mg": 40.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Cauliflower (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 107.0},
        ],
        "calories": 25,
        "protein_g": 1.9,
        "carbs_g": 5.0,
        "fats_g": 0.3,
        "saturated_fats_g": 0.1,
        "fiber_g": 2.0,
        "sugar_g": 1.9,
        "potassium_mg": 299.0,
        "sodium_mg": 30.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 15.0,
        "calcium_mg": 22.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Iceberg Lettuce / Cabbage (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 72.0},
        ],
        "calories": 14,
        "protein_g": 0.9,
        "carbs_g": 3.0,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.2,
        "sugar_g": 2.0,
        "potassium_mg": 141.0,
        "sodium_mg": 10.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 7.0,
        "calcium_mg": 18.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Lettuce (Romaine/Green Leaf, Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 36.0},
        ],
        "calories": 15,
        "protein_g": 1.4,
        "carbs_g": 2.8,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.3,
        "sugar_g": 0.8,
        "potassium_mg": 194.0,
        "sodium_mg": 28.0,
        "iron_mg": 0.9,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 13.0,
        "calcium_mg": 36.0,
        "cholesterol_mg": 0.0,
    },
]
