"""Fruiting & Other Vegetables entries for the global food database."""

VEGETABLES_FRUITING_AND_OTHER = [
    {
        "name": "Asparagus (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 piece", "equivalent_g": 16.0},
        ],
        "calories": 20,
        "protein_g": 2.2,
        "carbs_g": 3.9,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.1,
        "sugar_g": 1.9,
        "potassium_mg": 202.0,
        "sodium_mg": 2.0,
        "iron_mg": 2.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 14.0,
        "calcium_mg": 24.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Bell Peppers (Raw, Red/Green)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 149.0},
            {"description": "1 pepper", "equivalent_g": 119.0},
        ],
        "calories": 20,
        "protein_g": 0.9,
        "carbs_g": 4.6,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.7,
        "sugar_g": 2.4,
        "potassium_mg": 175.0,
        "sodium_mg": 3.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 10.0,
        "calcium_mg": 10.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Celery (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 101.0},
        ],
        "calories": 14,
        "protein_g": 0.7,
        "carbs_g": 3.0,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.6,
        "sugar_g": 1.3,
        "potassium_mg": 260.0,
        "sodium_mg": 80.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 11.0,
        "calcium_mg": 40.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Cherry Tomatoes (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cherry", "equivalent_g": 17.0},
        ],
        "calories": 18,
        "protein_g": 0.9,
        "carbs_g": 3.9,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.2,
        "sugar_g": 2.6,
        "potassium_mg": 237.0,
        "sodium_mg": 5.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 11.0,
        "calcium_mg": 10.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Chili Pepper (Raw, Red or Green)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 150.0},
            {"description": "1 pepper", "equivalent_g": 45.0},
        ],
        "calories": 40,
        "protein_g": 2.0,
        "carbs_g": 8.8,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.5,
        "sugar_g": 5.3,
        "potassium_mg": 322.0,
        "sodium_mg": 7.0,
        "iron_mg": 1.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 25.0,
        "calcium_mg": 14.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Cucumber (Raw, with peel)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 104.0},
            {"description": "1 cucumber", "equivalent_g": 301.0},
        ],
        "calories": 15,
        "protein_g": 0.7,
        "carbs_g": 3.6,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 0.5,
        "sugar_g": 1.7,
        "potassium_mg": 147.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 13.0,
        "calcium_mg": 16.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Eggplant (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 82.0},
            {"description": "1 eggplant", "equivalent_g": 458.0},
        ],
        "calories": 25,
        "protein_g": 1.0,
        "carbs_g": 5.9,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 3.0,
        "sugar_g": 3.5,
        "potassium_mg": 229.0,
        "sodium_mg": 2.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 14.0,
        "calcium_mg": 9.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Green Beans (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 110.0},
        ],
        "calories": 31,
        "protein_g": 1.8,
        "carbs_g": 7.0,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.7,
        "sugar_g": 3.3,
        "potassium_mg": 211.0,
        "sodium_mg": 6.0,
        "iron_mg": 1.0,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 25.0,
        "calcium_mg": 37.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Mushrooms (White Button, Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 70.0},
            {"description": "1 piece", "equivalent_g": 10.0},
        ],
        "calories": 22,
        "protein_g": 3.1,
        "carbs_g": 3.3,
        "fats_g": 0.3,
        "saturated_fats_g": 0.1,
        "fiber_g": 1.0,
        "sugar_g": 2.0,
        "potassium_mg": 318.0,
        "sodium_mg": 5.0,
        "iron_mg": 0.5,
        "vitamin_d_mcg": 0.2,
        "zinc_mg": 0.5,
        "magnesium_mg": 9.0,
        "calcium_mg": 3.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Pickles (Cucumber, Dill/Sour)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 pickle", "equivalent_g": 35.0},
        ],
        "calories": 11,
        "protein_g": 0.3,
        "carbs_g": 2.3,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.2,
        "sugar_g": 1.1,
        "potassium_mg": 112.0,
        "sodium_mg": 1208.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.1,
        "magnesium_mg": 4.0,
        "calcium_mg": 0.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Sweetcorn (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 154.0},
            {"description": "1 cob", "equivalent_g": 103.0},
        ],
        "calories": 86,
        "protein_g": 3.3,
        "carbs_g": 18.7,
        "fats_g": 1.4,
        "saturated_fats_g": 0.2,
        "fiber_g": 2.0,
        "sugar_g": 6.3,
        "potassium_mg": 270.0,
        "sodium_mg": 15.0,
        "iron_mg": 0.5,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.5,
        "magnesium_mg": 37.0,
        "calcium_mg": 2.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Tomatoes (Raw, Red)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 large", "equivalent_g": 182.0},
            {"description": "1 medium", "equivalent_g": 123.0},
            {"description": "1 small", "equivalent_g": 91.0},
            {"description": "1 slice", "equivalent_g": 20.0},
        ],
        "calories": 18,
        "protein_g": 0.9,
        "carbs_g": 3.9,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.2,
        "sugar_g": 2.6,
        "potassium_mg": 237.0,
        "sodium_mg": 5.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 11.0,
        "calcium_mg": 10.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Zucchini (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 124.0},
            {"description": "1 zucchini", "equivalent_g": 196.0},
        ],
        "calories": 17,
        "protein_g": 1.2,
        "carbs_g": 3.1,
        "fats_g": 0.3,
        "saturated_fats_g": 0.1,
        "fiber_g": 1.0,
        "sugar_g": 2.5,
        "potassium_mg": 261.0,
        "sodium_mg": 8.0,
        "iron_mg": 0.4,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 18.0,
        "calcium_mg": 16.0,
        "cholesterol_mg": 0.0,
    },
]
