"""Roots & Tubers entries for the global food database."""

VEGETABLES_ROOTS_AND_TUBERS = [
    {
        "name": "Beetroot / Beet (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 136.0},
            {"description": "1 piece", "equivalent_g": 82.0},
        ],
        "calories": 43,
        "protein_g": 1.6,
        "carbs_g": 9.6,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.8,
        "sugar_g": 6.8,
        "potassium_mg": 325.0,
        "sodium_mg": 78.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.4,
        "magnesium_mg": 23.0,
        "calcium_mg": 16.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Carrots (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 128.0},
            {"description": "1 carrot", "equivalent_g": 61.0},
        ],
        "calories": 41,
        "protein_g": 0.9,
        "carbs_g": 9.6,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.8,
        "sugar_g": 4.7,
        "potassium_mg": 320.0,
        "sodium_mg": 69.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 12.0,
        "calcium_mg": 33.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Garlic (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 136.0},
            {"description": "1 garlic", "equivalent_g": 58.0},
            {"description": "1 piece (clove)", "equivalent_g": 3.0},
        ],
        "calories": 149,
        "protein_g": 6.4,
        "carbs_g": 33.1,
        "fats_g": 0.5,
        "saturated_fats_g": 0.1,
        "fiber_g": 2.1,
        "sugar_g": 1.0,
        "potassium_mg": 401.0,
        "sodium_mg": 17.0,
        "iron_mg": 1.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 1.2,
        "magnesium_mg": 25.0,
        "calcium_mg": 181.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Ginger Root (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 96.0},
        ],
        "calories": 80,
        "protein_g": 1.8,
        "carbs_g": 17.8,
        "fats_g": 0.8,
        "saturated_fats_g": 0.2,
        "fiber_g": 2.0,
        "sugar_g": 1.7,
        "potassium_mg": 415.0,
        "sodium_mg": 13.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 43.0,
        "calcium_mg": 16.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Onion (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 160.0},
            {"description": "1 onion", "equivalent_g": 110.0},
        ],
        "calories": 40,
        "protein_g": 1.1,
        "carbs_g": 9.3,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.7,
        "sugar_g": 4.2,
        "potassium_mg": 146.0,
        "sodium_mg": 4.0,
        "iron_mg": 0.2,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 10.0,
        "calcium_mg": 23.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Pumpkin (Cooked / Boiled)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 245.0},
            {"description": "1 slice", "equivalent_g": 116.0},
        ],
        "calories": 20,
        "protein_g": 0.7,
        "carbs_g": 4.9,
        "fats_g": 0.1,
        "saturated_fats_g": 0.1,
        "fiber_g": 1.1,
        "sugar_g": 2.1,
        "potassium_mg": 230.0,
        "sodium_mg": 1.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.2,
        "magnesium_mg": 9.0,
        "calcium_mg": 15.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Radish (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 cup", "equivalent_g": 116.0},
            {"description": "1 piece", "equivalent_g": 4.5},
        ],
        "calories": 16,
        "protein_g": 0.7,
        "carbs_g": 3.4,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.6,
        "sugar_g": 1.9,
        "potassium_mg": 233.0,
        "sodium_mg": 39.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 10.0,
        "calcium_mg": 25.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Sweet Potatoes (Baked)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 extra large", "equivalent_g": 300.0},
            {"description": "1 large", "equivalent_g": 180.0},
            {"description": "1 medium", "equivalent_g": 114.0},
            {"description": "1 small", "equivalent_g": 60.0},
        ],
        "calories": 90,
        "protein_g": 2.0,
        "carbs_g": 20.7,
        "fats_g": 0.2,
        "saturated_fats_g": 0.0,
        "fiber_g": 3.3,
        "sugar_g": 6.5,
        "potassium_mg": 475.0,
        "sodium_mg": 36.0,
        "iron_mg": 0.7,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 27.0,
        "calcium_mg": 38.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "Sweet Potatoes (Raw)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 extra large", "equivalent_g": 300.0},
            {"description": "1 large", "equivalent_g": 250.0},
            {"description": "1 medium", "equivalent_g": 130.0},
            {"description": "1 small", "equivalent_g": 60.0},
        ],
        "calories": 86,
        "protein_g": 1.6,
        "carbs_g": 20.1,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 3.0,
        "sugar_g": 4.2,
        "potassium_mg": 337.0,
        "sodium_mg": 55.0,
        "iron_mg": 0.6,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 25.0,
        "calcium_mg": 30.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "White Potatoes (Baked, with Skin)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 large", "equivalent_g": 299.0},
            {"description": "1 medium", "equivalent_g": 173.0},
            {"description": "1 small", "equivalent_g": 138.0},
        ],
        "calories": 93,
        "protein_g": 2.5,
        "carbs_g": 21.2,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.2,
        "sugar_g": 1.2,
        "potassium_mg": 535.0,
        "sodium_mg": 10.0,
        "iron_mg": 1.1,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 28.0,
        "calcium_mg": 15.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "White Potatoes (Boiled, without Skin)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 large", "equivalent_g": 299.0},
            {"description": "1 medium", "equivalent_g": 167.0},
            {"description": "1 small", "equivalent_g": 112.0},
        ],
        "calories": 87,
        "protein_g": 1.9,
        "carbs_g": 20.1,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 1.8,
        "sugar_g": 0.9,
        "potassium_mg": 328.0,
        "sodium_mg": 5.0,
        "iron_mg": 0.3,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 20.0,
        "calcium_mg": 5.0,
        "cholesterol_mg": 0.0,
    },
    {
        "name": "White Potatoes (Raw, with Skin)",
        "serving_size": 100.0,
        "serving_unit": "g",
        "custom_servings": [
            {"description": "1 large", "equivalent_g": 299.0},
            {"description": "1 medium", "equivalent_g": 213.0},
            {"description": "1 small", "equivalent_g": 170.0},
        ],
        "calories": 77,
        "protein_g": 2.0,
        "carbs_g": 17.5,
        "fats_g": 0.1,
        "saturated_fats_g": 0.0,
        "fiber_g": 2.2,
        "sugar_g": 0.8,
        "potassium_mg": 421.0,
        "sodium_mg": 6.0,
        "iron_mg": 0.8,
        "vitamin_d_mcg": 0.0,
        "zinc_mg": 0.3,
        "magnesium_mg": 23.0,
        "calcium_mg": 12.0,
        "cholesterol_mg": 0.0,
    },
]
